//! rawposix syscall dispatcher table
//! Source of truth for syscall numbers: Linux x86_64 syscall table
//! https://github.com/torvalds/linux/blob/v6.16-rc1/arch/x86/entry/syscalls/syscall_64.tbl
//! https://filippo.io/linux-syscall-table/
//! Keep these in sync with glibc's lind_syscall_num.h
use super::fs_calls::{
    access_syscall, brk_syscall, chdir_syscall, chmod_syscall, clock_gettime_syscall,
    close_syscall, dup2_syscall, dup3_syscall, dup_syscall, fchdir_syscall, fchmod_syscall,
    fcntl_syscall, fdatasync_syscall, flock_syscall, fstat_syscall, fstatfs_syscall, fsync_syscall,
    ftruncate_syscall, futex_syscall, getcwd_syscall, getdents_syscall, getrandom_syscall,
    ioctl_syscall, link_syscall, lseek_syscall, mkdir_syscall, mknod_syscall, mmap_syscall,
    mprotect_syscall, munmap_syscall, nanosleep_time64_syscall, open_syscall, openat_syscall,
    pipe2_syscall, pipe_syscall, pread_syscall, preadv_syscall, pwrite_syscall, pwritev_syscall,
    read_syscall, readlink_syscall, readlinkat_syscall, readv_syscall, rename_syscall,
    rmdir_syscall, shmat_syscall, shmctl_syscall, shmdt_syscall, shmget_syscall, stat_syscall,
    statfs_syscall, sync_file_range_syscall, truncate_syscall, unlink_syscall, unlinkat_syscall,
    write_syscall, writev_syscall,
    ioctl_syscall, link_syscall, lseek_syscall, lstat_syscall, mkdir_syscall, mknod_syscall,
    mmap_syscall, mprotect_syscall, munmap_syscall, nanosleep_time64_syscall, open_syscall,
    openat_syscall, pipe2_syscall, pipe_syscall, pread_syscall, pwrite_syscall, read_syscall,
    readlink_syscall, readlinkat_syscall, readv_syscall, rename_syscall, rmdir_syscall,
    shmat_syscall, shmctl_syscall, shmdt_syscall, shmget_syscall, stat_syscall, statfs_syscall,
    symlink_syscall, symlinkat_syscall, sync_file_range_syscall, truncate_syscall, unlink_syscall,
    unlinkat_syscall, write_syscall, writev_syscall,
};
use super::init::RawCallFunc;
use super::net_calls::{
    accept4_syscall, accept_syscall, bind_syscall, connect_syscall, epoll_create1_syscall,
    epoll_create_syscall, epoll_ctl_syscall, epoll_wait_syscall, gethostname_syscall,
    getpeername_syscall, getsockname_syscall, getsockopt_syscall, listen_syscall, poll_syscall,
    recvfrom_syscall, recvmsg_syscall, select_syscall, sendmsg_syscall, sendto_syscall,
    setsockopt_syscall, shutdown_syscall, socket_syscall, socketpair_syscall,
};
use super::sys_calls::{
    exec_syscall, exit_group_syscall, exit_syscall, fork_syscall, getegid_syscall, geteuid_syscall,
    getgid_syscall, getpid_syscall, getppid_syscall, getuid_syscall, kill_syscall,
    prlimit64_syscall, sched_yield_syscall, setitimer_syscall, sigaction_syscall,
    sigprocmask_syscall, waitpid_syscall,
};
use sysdefs::constants::syscall_const;

pub const SYSCALL_TABLE: &[(u64, RawCallFunc)] = &[
    (syscall_const::READ_SYSCALL as u64, read_syscall),
    (syscall_const::WRITE_SYSCALL as u64, write_syscall),
    (syscall_const::OPEN_SYSCALL as u64, open_syscall),
    (syscall_const::CLOSE_SYSCALL as u64, close_syscall),
    (syscall_const::POLL_SYSCALL as u64, poll_syscall),
    (syscall_const::STAT_SYSCALL as u64, stat_syscall),
    (syscall_const::FSTAT_SYSCALL as u64, fstat_syscall),
    (syscall_const::LSTAT_SYSCALL as u64, lstat_syscall),
    (syscall_const::LSEEK_SYSCALL as u64, lseek_syscall),
    (syscall_const::MMAP_SYSCALL as u64, mmap_syscall),
    (syscall_const::MPROTECT_SYSCALL as u64, mprotect_syscall),
    (syscall_const::MUNMAP_SYSCALL as u64, munmap_syscall),
    (syscall_const::BRK_SYSCALL as u64, brk_syscall),
    (syscall_const::SIGACTION_SYSCALL as u64, sigaction_syscall),
    (
        syscall_const::SIGPROCMASK_SYSCALL as u64,
        sigprocmask_syscall,
    ),
    (syscall_const::IOCTL_SYSCALL as u64, ioctl_syscall),
    (syscall_const::PREAD_SYSCALL as u64, pread_syscall),
    (syscall_const::PWRITE_SYSCALL as u64, pwrite_syscall),
    (syscall_const::READV_SYSCALL as u64, readv_syscall),
    (syscall_const::WRITEV_SYSCALL as u64, writev_syscall),
    (syscall_const::ACCESS_SYSCALL as u64, access_syscall),
    (syscall_const::PIPE_SYSCALL as u64, pipe_syscall),
    (syscall_const::SELECT_SYSCALL as u64, select_syscall),
    (
        syscall_const::SCHED_YIELD_SYSCALL as u64,
        sched_yield_syscall,
    ),
    (syscall_const::SHMGET_SYSCALL as u64, shmget_syscall),
    (syscall_const::SHMAT_SYSCALL as u64, shmat_syscall),
    (syscall_const::SHMCTL_SYSCALL as u64, shmctl_syscall),
    (syscall_const::DUP_SYSCALL as u64, dup_syscall),
    (syscall_const::DUP2_SYSCALL as u64, dup2_syscall),
    (
        syscall_const::NANOSLEEP_SYSCALL as u64,
        nanosleep_time64_syscall,
    ),
    (syscall_const::SETITIMER_SYSCALL as u64, setitimer_syscall),
    (syscall_const::GETPID_SYSCALL as u64, getpid_syscall),
    (syscall_const::SOCKET_SYSCALL as u64, socket_syscall),
    (syscall_const::CONNECT_SYSCALL as u64, connect_syscall),
    (syscall_const::ACCEPT_SYSCALL as u64, accept_syscall),
    (syscall_const::SENDTO_SYSCALL as u64, sendto_syscall),
    (syscall_const::RECVFROM_SYSCALL as u64, recvfrom_syscall),
    (syscall_const::SENDMSG_SYSCALL as u64, sendmsg_syscall),
    (syscall_const::RECVMSG_SYSCALL as u64, recvmsg_syscall),
    (syscall_const::SHUTDOWN_SYSCALL as u64, shutdown_syscall),
    (syscall_const::BIND_SYSCALL as u64, bind_syscall),
    (syscall_const::LISTEN_SYSCALL as u64, listen_syscall),
    (
        syscall_const::GETSOCKNAME_SYSCALL as u64,
        getsockname_syscall,
    ),
    (
        syscall_const::GETPEERNAME_SYSCALL as u64,
        getpeername_syscall,
    ),
    (syscall_const::SOCKETPAIR_SYSCALL as u64, socketpair_syscall),
    (syscall_const::SETSOCKOPT_SYSCALL as u64, setsockopt_syscall),
    (syscall_const::GETSOCKOPT_SYSCALL as u64, getsockopt_syscall),
    (syscall_const::CLONE_SYSCALL as u64, fork_syscall),
    (syscall_const::EXEC_SYSCALL as u64, exec_syscall),
    (syscall_const::EXIT_SYSCALL as u64, exit_syscall),
    (syscall_const::WAITPID_SYSCALL as u64, waitpid_syscall),
    (syscall_const::KILL_SYSCALL as u64, kill_syscall),
    (syscall_const::SHMDT_SYSCALL as u64, shmdt_syscall),
    (syscall_const::FCNTL_SYSCALL as u64, fcntl_syscall),
    (syscall_const::FLOCK_SYSCALL as u64, flock_syscall),
    (syscall_const::FSYNC_SYSCALL as u64, fsync_syscall),
    (syscall_const::FDATASYNC_SYSCALL as u64, fdatasync_syscall),
    (syscall_const::TRUNCATE_SYSCALL as u64, truncate_syscall),
    (syscall_const::FTRUNCATE_SYSCALL as u64, ftruncate_syscall),
    (syscall_const::GETDENTS_SYSCALL as u64, getdents_syscall),
    (syscall_const::GETCWD_SYSCALL as u64, getcwd_syscall),
    (syscall_const::CHDIR_SYSCALL as u64, chdir_syscall),
    (syscall_const::FCHDIR_SYSCALL as u64, fchdir_syscall),
    (syscall_const::RENAME_SYSCALL as u64, rename_syscall),
    (syscall_const::MKDIR_SYSCALL as u64, mkdir_syscall),
    (syscall_const::RMDIR_SYSCALL as u64, rmdir_syscall),
    (syscall_const::LINK_SYSCALL as u64, link_syscall),
    (syscall_const::UNLINK_SYSCALL as u64, unlink_syscall),
    (syscall_const::SYMLINK_SYSCALL as u64, symlink_syscall),
    (syscall_const::READLINK_SYSCALL as u64, readlink_syscall),
    (syscall_const::CHMOD_SYSCALL as u64, chmod_syscall),
    (syscall_const::FCHMOD_SYSCALL as u64, fchmod_syscall),
    (syscall_const::GETUID_SYSCALL as u64, getuid_syscall),
    (syscall_const::GETGID_SYSCALL as u64, getgid_syscall),
    (syscall_const::GETEUID_SYSCALL as u64, geteuid_syscall),
    (syscall_const::GETEGID_SYSCALL as u64, getegid_syscall),
    (syscall_const::GETPPID_SYSCALL as u64, getppid_syscall),
    (syscall_const::MKNOD_SYSCALL as u64, mknod_syscall),
    (syscall_const::STATFS_SYSCALL as u64, statfs_syscall),
    (syscall_const::FSTATFS_SYSCALL as u64, fstatfs_syscall),
    (
        syscall_const::GETHOSTNAME_SYSCALL as u64,
        gethostname_syscall,
    ),
    (syscall_const::FUTEX_SYSCALL as u64, futex_syscall),
    (
        syscall_const::EPOLL_CREATE_SYSCALL as u64,
        epoll_create_syscall,
    ),
    (
        syscall_const::CLOCK_GETTIME_SYSCALL as u64,
        clock_gettime_syscall,
    ),
    (syscall_const::EXIT_GROUP_SYSCALL as u64, exit_group_syscall),
    (syscall_const::EPOLL_WAIT_SYSCALL as u64, epoll_wait_syscall),
    (syscall_const::EPOLL_CTL_SYSCALL as u64, epoll_ctl_syscall),
    (syscall_const::OPENAT_SYSCALL as u64, openat_syscall),
    (syscall_const::UNLINKAT_SYSCALL as u64, unlinkat_syscall),
    (syscall_const::SYMLINKAT_SYSCALL as u64, symlinkat_syscall),
    (syscall_const::READLINKAT_SYSCALL as u64, readlinkat_syscall),
    (
        syscall_const::SYNC_FILE_RANGE_SYSCALL as u64,
        sync_file_range_syscall,
    ),
    (syscall_const::ACCEPT4_SYSCALL as u64, accept4_syscall),
    (syscall_const::PREADV_SYSCALL as u64, preadv_syscall),
    (syscall_const::PWRITEV_SYSCALL as u64, pwritev_syscall),
    (
        syscall_const::EPOLL_CREATE1_SYSCALL as u64,
        epoll_create1_syscall,
    ),
    (syscall_const::DUP3_SYSCALL as u64, dup3_syscall),
    (syscall_const::PIPE2_SYSCALL as u64, pipe2_syscall),
    (syscall_const::PRLIMIT64_SYSCALL as u64, prlimit64_syscall),
    (syscall_const::GETRANDOM_SYSCALL as u64, getrandom_syscall),
];
