#!/bin/bash
set -ex

export HOME_DIR="/home/lind/lind-wasm"
export LLVM_SRC="$HOME_DIR/llvm-project"
export INSTALL_DIR="$HOME_DIR/compiler-rt-install-wasm32"
export BUILD_DIR="$HOME_DIR/compiler-rt-build-wasm32"
export TOOLCHAIN_FILE="$HOME_DIR/Toolchain-WASI-wasm32.cmake"

echo "HOME_DIR=$HOME_DIR"
echo "LLVM_SRC=$LLVM_SRC"
echo "INSTALL_DIR=$INSTALL_DIR"
echo "BUILD_DIR=$BUILD_DIR"
echo "TOOLCHAIN_FILE=$TOOLCHAIN_FILE"

test -d "$HOME_DIR"
test -d "$LLVM_SRC/compiler-rt"
test -f "$TOOLCHAIN_FILE"
test -d "$HOME_DIR/build/sysroot"
command -v cmake
command -v ninja

rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

cmake -G Ninja "$LLVM_SRC/compiler-rt" \
  -DCMAKE_TOOLCHAIN_FILE="$TOOLCHAIN_FILE" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
  -DCOMPILER_RT_BUILD_BUILTINS=ON \
  -DCOMPILER_RT_BUILD_CRT=ON \
  -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON \
  -DCOMPILER_RT_INCLUDE_TESTS=OFF \
  -DCOMPILER_RT_BUILD_SANITIZERS=OFF \
  -DCOMPILER_RT_BUILD_XRAY=OFF \
  -DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
  -DCOMPILER_RT_BUILD_PROFILE=OFF \
  -DCOMPILER_RT_BUILD_MEMPROF=OFF \
  -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY

grep -E 'CMAKE_SYSTEM_NAME|CMAKE_SYSTEM_PROCESSOR|CMAKE_(C|CXX|ASM)_COMPILER_TARGET|COMPILER_RT_BUILD_CRT|COMPILER_RT_DEFAULT_TARGET_ONLY' \
  "$BUILD_DIR/CMakeCache.txt"

ninja
ninja install