#!/bin/bash
set -e

export ROOT_DIR=$(pwd)
export LLVM_SRC="$ROOT_DIR/llvm-project"
export INSTALL_PREFIX="$ROOT_DIR/libcxx-wasi-install"

mkdir -p libcxx-build

cmake -B libcxx-build -S "$LLVM_SRC/runtimes" \
  -DCMAKE_TOOLCHAIN_FILE="$ROOT_DIR/Toolchain-WASI.cmake" \
  -DLLVM_PATH="$LLVM_SRC/llvm" \
  -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
  -DLLVM_TARGETS_TO_BUILD="X86" \
  -DLLVM_DEFAULT_TARGET_TRIPLE="x86_64-unknown-linux-gnu" \
  -DLLVM_HOST_TRIPLE="wasm32-unknown-wasi" \
  -DLIBCXX_ENABLE_SHARED=OFF \
  -DLIBCXX_ENABLE_STATIC=ON \
  -DLIBCXX_ENABLE_EXCEPTIONS=OFF \
  -DLIBCXX_USE_COMPILER_RT=ON \
  -DLIBCXX_ENABLE_RTTI=ON \
  -DLIBCXXABI_ENABLE_SHARED=OFF \
  -DLIBCXXABI_ENABLE_STATIC=ON \
  -DLIBCXXABI_ENABLE_EXCEPTIONS=OFF \
  -DLIBCXXABI_USE_LLVM_UNWINDER=OFF \
  -DLIBCXXABI_ENABLE_STATIC_UNWINDER=OFF \
  -DLIBCXX_ENABLE_UNWIND_TABLES=OFF \
  -DLIBCXX_ENABLE_TIME_ZONE_DATABASE=OFF \
  -DLIBCXXABI_ENABLE_UNWIND_TABLES=OFF \
  -DLIBCXXABI_USE_COMPILER_RT=ON \
  -DLIBCXXABI_ENABLE_RTTI=ON \
  -DLIBCXXABI_LIBCXX_PATH="$LLVM_SRC/libcxx" \
  -DLIBCXX_HAS_MUSL_LIBC:BOOL=OFF \
  -DLIBCXXABI_ENABLE_EXCEPTIONS:BOOL=OFF \
  -DLIBCXXABI_USE_LLVM_UNWINDER:BOOL=OFF \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" \
  -DCMAKE_CXX_COMPILER_WORKS=1 \
  -DCMAKE_C_COMPILER_WORKS=1

cmake --build libcxx-build --target install
