#!/usr/bin/env bash
# Generate libm.marshal.json: argument-marshalling inference for the functions
# exported by the built libm. Best-effort, library-side.
#
# NOTE on export list: scraped via llvm-nm from the actual linked libm.so
# (src/glibc/sysroot/lib/wasm32-wasi/libm.so -- the pre-lind-wasm-opt object
# scripts/make_shared_libm.sh's `wasm-ld` step produces, NOT lindfs/lib/
# libm.so, which has gone through lind-wasm-opt's binaryen passes and is no
# longer parseable by llvm-nm at all ["invalid function export"]). This used
# to scrape math/Versions instead (glibc's own textual symbol-versioning
# manifest, listing every symbol libm has EVER exported across ALL glibc
# history/configurations) on the theory that it was "the same source of
# truth the real libm.so build uses" -- confirmed FALSE: math/Versions
# includes ~81 GLIBC_2.15-2.31 `_finite`-suffixed compat symbols
# (__acos_finite, __exp_finite, ...) that are SHLIB_COMPAT-gated behind
# `#ifdef SHARED`, which this project's build never defines when compiling
# libm objects -- so those symbols don't exist in the real .so at all
# (verified: absent from both the recompiled .bc's LLVM IR and the shipped
# .so's own export table), yet math/Versions listed them as "exported"
# unconditionally, permanently inflating the "missing" count with symbols
# that were never real. It also listed pure DATA symbols (_LIB_VERSION,
# signgam, __fpu_control) as if they were functions. Scraping the real .so's
# symbol table (`$2=="T"`, defined-in-code only) sidesteps both problems for
# free -- it can only ever list what's actually callable in the shipped
# library, exactly matching infer_libc.sh's own approach for libc.so.
#
# NOTE on compile flags: math/ sources reach considerably deeper into glibc's
# private-header chain than typical libc sources (math-underflow.h,
# fenv_private.h, ...). Verified against build/config.make (the project's
# actual resolved CFLAGS) and fixed two real gaps found by trial compilation:
#   - -O2 (not -O1) and -DLIND_EH_SETJMP, matching config.make exactly.
#   - -I../math must come AFTER -I../include, not before: glibc's
#     include/fenv.h is an internal "override" wrapper that only injects the
#     private declarations (__feraiseexcept, struct rm_ctx, ...) if IT is the
#     file that transitively #includes the real math/fenv.h; putting -I../math
#     first makes `#include <fenv.h>` resolve straight to the public header,
#     silently skipping the private declarations math/ internals require.
#
# Pipeline:
#   1. export list  = defined functions in the real, linked libm.so (llvm-nm)
#   2. TU list      = glibc sources that were compiled (from build/*.o[.dt]) --
#                     math/ compiles under the same "libc" module in this
#                     build, so this reuses the exact same TU superset as
#                     infer_libc.sh (math/ TUs are already included in it).
#   3. emit wasm32 bitcode (+DWARF) per TU, in parallel (skip TUs that don't build)
#   4. marshal-infer over all bitcode, filtered to the export list -> JSON
#
# Usage: tools/marshal-infer/infer_libm.sh [out.json]
# Output default: <repo>/libm.marshal.json
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
GLIBC="${REPO_ROOT}/src/glibc"
BUILD="${GLIBC}/build"
MI="${SCRIPT_DIR}/build/marshal-infer"
LIBM_SO="${GLIBC}/sysroot/lib/wasm32-wasi/libm.so"
OUT="${1:-${REPO_ROOT}/libm.marshal.json}"
JOBS="$(nproc)"

# Runtime/toolchain plumbing, not application-facing library API -- excluded
# from the export list so it never counts as "missing coverage". Two flavors:
#   - wasm-ld link-time synthesized symbols (__wasm_*): generated by the
#     LINKER ITSELF from relocation/TLS/ctor records, never from any C
#     translation unit (confirmed: zero matches for any of these names across
#     the whole glibc source tree, declarations included). No DWARF, no
#     DISubprogram, nothing a grate could ever wrap.
#   - __get_aligned_tls_size: DOES have real C source
#     (lind_syscall/lind_utils.c) and real DWARF -- not a linker synthetic --
#     but it's a lind-runtime-startup helper queried by the wasm host before/
#     during module instantiation (TLS block sizing), the same role as the
#     __wasm_* symbols even though it isn't literally linker-generated.
# Either way: none of these run as part of normal application code reachable
# through a grate, so excluding them corrects the list to describe only
# symbols a grate could plausibly need to interpose.
# Keep this list in sync with infer_libc.sh's copy if you add to it.
TOOLCHAIN_BUILTINS='^(__wasm_(call_ctors|apply_data_relocs|apply_global_relocs|apply_tls_relocs|init_tls|init_memory)|__get_aligned_tls_size)$'

[[ -x "${MI}" ]] || { echo "build marshal-infer first: tools/marshal-infer/build.sh" >&2; exit 1; }
[[ -d "${BUILD}" ]] || { echo "glibc build dir missing: ${BUILD}" >&2; exit 1; }
[[ -f "${LIBM_SO}" ]] || { echo "libm.so missing: ${LIBM_SO} (run scripts/make_shared_libm.sh first)" >&2; exit 1; }

WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT
BCDIR="${WORK}/bc"; mkdir -p "${BCDIR}"

echo "[1/4] export list from libm.so"
llvm-nm "${LIBM_SO}" 2>/dev/null | awk '$2=="T"{print $3}' | sort -u \
  | grep -Ev "${TOOLCHAIN_BUILTINS}" > "${WORK}/exports.txt"
echo "      $(wc -l < "${WORK}/exports.txt") exported functions"

echo "[2/4] enumerate compiled translation units"
# (a) exact sources from dependency files (handles sysdeps overrides). Scans
# BOTH *.o.dt (a lind-custom tracking file, generated for only a subset of
# targets -- 666 of them in a representative build) AND *.o.d (glibc's own
# standard -MMD dependency file, generated for far more targets -- 1974 in
# the same build; many sysdeps overrides, e.g. s_copysign.c/s_frexp.c/
# s_scalbn.c/s_isnan.c/s_modf.c, are ONLY tracked via .o.d, never .o.dt, and
# were silently invisible to this enumeration before .o.d was added here).
# Either file's own paths are relative to ${BUILD} (e.g. "../sysdeps/
# ieee754/dbl-64/s_sin.c") -- prefix with ${BUILD}/ so the existence check
# below resolves correctly regardless of this script's own cwd. Without
# this, every TU only reachable via a sysdeps override (s_sin.c, e_sqrt.c,
# ...) silently vanishes here rather than in step 3, since (b)'s build/
# <rel>.o -> src/glibc/<rel>.c path-mapping only catches sources that live
# at the SAME relative path as their .o (never true for a sysdeps override,
# whose .o still lands in the generic dir, e.g. build/math/s_sin.o but the
# source is under sysdeps/ieee754/dbl-64/, not math/).
{ find "${BUILD}" -name '*.o.dt' -print0; find "${BUILD}" -name '*.o.d' -print0; } \
    2>/dev/null | while IFS= read -r -d '' dt; do
  rel="$(sed -e ':a;N;$!ba;s/\\\n//g' "$dt" 2>/dev/null | sed 's/^[^:]*://' \
    | tr ' \t' '\n\n' | grep -m1 '\.c$' || true)"
  [[ -z "$rel" ]] && continue
  # Older-style .o.d files leave $(common-objpfx) UNEXPANDED as literal text
  # for generated wrapper TUs that live directly under ${BUILD} (e.g. math/
  # gen-libm-templates.py's math-type-macros-double.h-based wrappers like
  # math/s_ldexp.c -- itself generated INTO the build dir, not the source
  # tree). Confirmed: for these files common-objpfx really does expand to
  # exactly "${BUILD}/" (the object genuinely sits at ${BUILD}/math/s_ldexp.o).
  rel="${rel#\$(common-objpfx)}"
  [[ "$rel" = /* ]] && echo "$rel" || echo "${BUILD}/${rel}"
done > "${WORK}/srcs.raw"
# (b) path-map remaining objects: build/<rel>.o -> src/glibc/<rel>.c
find "${BUILD}" -name '*.o' -printf '%P\n' 2>/dev/null | sed 's/\.o$/.c/' \
  | while read -r rel; do [[ -f "${GLIBC}/${rel}" ]] && echo "${GLIBC}/${rel}" || true; done \
  >> "${WORK}/srcs.raw" || true
sort -u "${WORK}/srcs.raw" | grep -E '\.c$' \
  | while read -r s; do [[ -f "$s" ]] && echo "$s" || true; done \
  > "${WORK}/srcs.txt" || true
echo "      $(wc -l < "${WORK}/srcs.txt") unique source TUs"

echo "[3/4] emit wasm32 bitcode (parallel x${JOBS}; failures skipped)"
RESOURCE_DIR="$(clang --target=wasm32-unknown-wasi -print-resource-dir)"
export GLIBC BUILD BCDIR RESOURCE_DIR
emit_one() {
  local src="$1"
  local name; name="$(echo "${src#"${GLIBC}/"}" | tr '/' '_')"
  local out="${BCDIR}/${name}.bc"
  local FLAGS=(--target=wasm32-unknown-wasi -Wno-int-conversion -DNO_HIDDEN -std=gnu11
    -fgnu89-inline -matomics -mbulk-memory -O2 -g -fPIC -fno-stack-protector
    -fno-common -Wp,-U_FORTIFY_SOURCE -fmath-errno -ftls-model=local-exec -DLIND_EH_SETJMP)
  local INC=(-I../include -I../math -I"${BUILD}/nptl" -I"${BUILD}" -I../sysdeps/lind -I../lind_syscall
    -I../sysdeps/unix/sysv/linux/i386/i686 -I../sysdeps/unix/sysv/linux/i386
    -I../sysdeps/unix/sysv/linux/x86/include -I../sysdeps/unix/sysv/linux/x86
    -I../sysdeps/x86/nptl -I../sysdeps/i386/nptl -I../sysdeps/unix/sysv/linux/include
    -I../sysdeps/unix/sysv/linux -I../sysdeps/nptl -I../sysdeps/pthread -I../sysdeps/gnu
    -I../sysdeps/unix/inet -I../sysdeps/unix/sysv -I../sysdeps/unix/i386 -I../sysdeps/unix
    -I../sysdeps/posix -I../sysdeps/i386/fpu -I../sysdeps/x86/fpu -I../sysdeps/i386
    -I../sysdeps/x86/include -I../sysdeps/x86 -I../sysdeps/wordsize-32
    -I../sysdeps/ieee754/float128 -I../sysdeps/ieee754/ldbl-96/include
    -I../sysdeps/ieee754/ldbl-96 -I../sysdeps/ieee754/dbl-64 -I../sysdeps/ieee754/flt-32
    -I../sysdeps/ieee754 -I../sysdeps/generic -I.. -I../libio -I.)
  # sysdeps/lind/Implies now points long double at ieee754/ldbl-128 (see
  # issues/ldbl96-vs-fp128-abi-mismatch.md), so any TU sourced from there
  # needs that dir on the include path too -- but ONLY for those TUs:
  # ldbl-128/math_ldbl.h #defines _Float128 as `long double`, which corrupts
  # _Generic-based dispatch (__MATH_TG in math.h) in ordinary double-only
  # files if it's on the path globally. Prepending it just for this src
  # keeps dbl-64 files unaffected.
  case "$src" in
    */ieee754/ldbl-128/*) INC=(-I../sysdeps/ieee754/ldbl-128 "${INC[@]}") ;;
  esac
  local SYSINC=(-nostdinc -isystem "${RESOURCE_DIR}/include" -isystem /usr/i686-linux-gnu/include)
  local DEF=(-D_LIBC_REENTRANT -include "${BUILD}/libc-modules.h" -DMODULE_NAME=libc
    -include ../include/libc-symbols.h -DPIC -DTOP_NAMESPACE=glibc)
  ( cd "${BUILD}" && timeout 60 clang "${FLAGS[@]}" "${INC[@]}" "${SYSINC[@]}" "${DEF[@]}" \
      -emit-llvm -c "$src" -o "$out" ) 2>/dev/null || { rm -f "$out"; return 0; }
}
export -f emit_one
xargs -a "${WORK}/srcs.txt" -P "${JOBS}" -I{} bash -c 'emit_one "$@"' _ {} || true
NBC=$(find "${BCDIR}" -name '*.bc' | wc -l)
echo "      ${NBC} TUs emitted bitcode"

echo "[4/4] infer + filter to exports -> ${OUT}"
# Single invocation (flattened .bc names have no spaces) so -o isn't overwritten
# by an xargs split.
# shellcheck disable=SC2046
"${MI}" --json --module libm --exports "${WORK}/exports.txt" -o "${OUT}" \
  $(find "${BCDIR}" -name '*.bc')
echo "OK: ${OUT}"
