[package]
name = "typemap"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
fdtables = { path = "../fdtables", default-features = false }
cage = { path = "../cage" }
sysdefs = { path = "../sysdefs" }

[features]
default = ["fast"]
fast = []
secure = []

[dev-dependencies]
dashmap = "5.1"
parking_lot = "0.12"