// lind_marshal.h — Automated argument marshalling for Lind grates (Stage 1 + 3).
//
// Include this header in a grate for automatic copy-in/copy-out marshalling.
// The grate registers a raw handler (generated by LIND_DEFINE_MARSHAL_HANDLER)
// and provides a lind_marshal_spec describing each argument.  The runtime does
// the rest: shadow allocation, copy-in, handler call, copy-out, return translation.
//
// --- Argument kinds ---
//   LIND_ARG_SCALAR  — pass value directly; no memory copy
//   LIND_ARG_PTR     — shadow buffer; direction + size_kind control copy behavior
//                      NULL → passed through as-is, no alloc/copy
//   LIND_ARG_HANDLE  — opaque token; value translated through handle table; pointee never copied
//
// --- Size kinds (for LIND_ARG_PTR) ---
//   LIND_SIZE_CONST           — const_size bytes
//   LIND_SIZE_FROM_ARG        — scalar value of raw_args[size_arg_index]
//                               (in struct context: sibling field at fields[size_arg_index])
//   LIND_SIZE_FROM_ARG_POINTEE— *(uint32_t at raw_args[size_arg_index]) (e.g. compress2 *destLen)
//   LIND_SIZE_CSTR            — scan for '\0', capped at LIND_MARSHAL_CSTR_CAP
//
// --- Return kinds ---
//   LIND_RET_VOID             — return 0
//   LIND_RET_SCALAR           — handler return value directly
//   LIND_RET_PTR_ALIAS_ARG    — original source-cage ptr of arg[alias_arg_index]
//   LIND_RET_PTR_INTO_ARG     — pointer offset inside arg[alias_arg_index]'s shadow
//   LIND_RET_HANDLE           — register handler's return as a new handle; return app_token
//   LIND_RET_FORCE_LOCAL      — not marshalable remotely; runtime runs Local
//
// --- Nested structs ---
//   Set lind_arg_spec.layout to a lind_layout describing the struct.
//   Fields with touched=1 are marshalled recursively.  Pointer fields in the struct
//   use the same arg_spec recursion; size_arg_index refers to a sibling field index.
//
// --- Handle table (per-grate static) ---
//   lind_register_handle(class, real_ptr) → app_token
//   lind_translate_handle(class, app_token) → real_ptr (or 0 if not found)
//   lind_release_handle(class, app_token)
//
// --- Handler signature ---
//   All handlers must have the uniform lind_handler6_t signature (WASM type-check).
//   Use LIND_AS_PTR / LIND_AS_SIZE / LIND_AS_INT / LIND_RET_PTR / LIND_RET_INT helpers.

#pragma once

#include <lind_syscall.h>
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>

// ---------------------------------------------------------------------------
// Handler argument / return cast helpers
// ---------------------------------------------------------------------------

#define LIND_AS_PTR(u)    ((void *)(uintptr_t)(u))
#define LIND_AS_CPTR(u)   ((const void *)(uintptr_t)(u))
#define LIND_AS_STR(u)    ((char *)(uintptr_t)(u))
#define LIND_AS_CSTR(u)   ((const char *)(uintptr_t)(u))
#define LIND_AS_SIZE(u)   ((size_t)(u))
#define LIND_AS_INT(u)    ((int)(u))
#define LIND_AS_UINT(u)   ((unsigned int)(u))
#define LIND_AS_LONG(u)   ((long)(u))
#define LIND_AS_ULONG(u)  ((unsigned long)(u))

#define LIND_RET_PTR(p)   ((uint64_t)(uintptr_t)(p))
#define LIND_RET_INT(v)   ((uint64_t)(uint32_t)(int)(v))
#define LIND_RET_LONG(v)  ((uint64_t)(long)(v))
#define LIND_RET_ULONG(v) ((uint64_t)(unsigned long)(v))

// All handlers passed to lind_marshal_dispatch must match this signature.
typedef uint64_t (*lind_handler6_t)(uint64_t, uint64_t, uint64_t,
                                    uint64_t, uint64_t, uint64_t);

// ---------------------------------------------------------------------------
// Metadata types
// ---------------------------------------------------------------------------

// Forward declarations for mutual recursion between lind_arg_spec / lind_layout.
struct lind_arg_spec;
struct lind_layout;

enum lind_arg_kind {
    LIND_ARG_SCALAR = 0,
    LIND_ARG_PTR    = 1,
    LIND_ARG_HANDLE = 2,   // opaque token; translate via handle table, never deep-copy
};

enum lind_ptr_direction {
    LIND_PTR_IN    = 0,
    LIND_PTR_OUT   = 1,
    LIND_PTR_INOUT = 2,
};

enum lind_size_kind {
    LIND_SIZE_NONE              = 0,
    LIND_SIZE_CONST             = 1,  // const_size bytes
    LIND_SIZE_FROM_ARG          = 2,  // value of raw_args[i] (top-level) or sibling field[i] (struct)
    LIND_SIZE_FROM_ARG_POINTEE  = 3,  // *(uint32_t at raw_args[i]) — two-pass, read from source cage
    LIND_SIZE_CSTR              = 4,  // scan for '\0', capped at LIND_MARSHAL_CSTR_CAP
};

enum lind_return_kind {
    LIND_RET_VOID          = 0,
    LIND_RET_SCALAR        = 1,
    LIND_RET_PTR_ALIAS_ARG = 2,  // return original source-cage ptr of arg[alias_arg_index]
    LIND_RET_PTR_INTO_ARG  = 3,  // return ptr offset inside arg[alias_arg_index]'s shadow (memchr)
    LIND_RET_HANDLE        = 4,  // register handler's return as new handle; return app_token
    LIND_RET_FORCE_LOCAL   = 5,  // not marshalable remotely; ensure Local placement
};

// Struct field for recursive lind_layout.
struct lind_field {
    uint32_t              offset;   // byte offset within the record
    struct lind_arg_spec *spec;     // recursive: a field may be ptr/handle/scalar
    uint8_t               touched;  // KSplit projection: marshal only if 1
};

// Pointee layout descriptor.  NULL layout = opaque bytes (flat buffer).
enum lind_layout_kind { LIND_LO_BYTES = 0, LIND_LO_STRUCT = 1, LIND_LO_UNION = 2 };

struct lind_layout {
    enum lind_layout_kind kind;
    uint32_t              nfields;
    struct lind_field    *fields;
    uint32_t              discriminator_field;  // UNION only: field index that selects the arm
    uint32_t              struct_size;          // total bytes (largest arm for unions)
};

struct lind_arg_spec {
    enum lind_arg_kind      kind;
    // PTR fields:
    enum lind_ptr_direction ptr_direction;
    enum lind_size_kind     size_kind;
    uint64_t                const_size;
    uint32_t                size_arg_index;  // arg index (top) or sibling field index (struct)
    struct lind_layout     *layout;          // NULL = flat buffer; non-NULL = structured pointee
    // HANDLE fields:
    uint32_t                handle_class;
    uint32_t                flags;
};

struct lind_return_spec {
    enum lind_return_kind kind;
    uint32_t              alias_arg_index;  // PTR_ALIAS_ARG / PTR_INTO_ARG / HANDLE
    uint32_t              handle_class;     // RET_HANDLE: class for new handle registration
};

struct lind_marshal_spec {
    uint32_t              nargs;
    struct lind_arg_spec  args[16];
    struct lind_return_spec ret;
};

// ---------------------------------------------------------------------------
// Current-call cage ID accessors (valid inside handler invocation)
// ---------------------------------------------------------------------------

static uint64_t _lind_marshal_source_cage = 0;
static uint64_t _lind_marshal_grate_cage  = 0;

#define LIND_SOURCE_CAGE() (_lind_marshal_source_cage)
#define LIND_GRATE_CAGE()  (_lind_marshal_grate_cage)

// ---------------------------------------------------------------------------
// C-string scan cap
// ---------------------------------------------------------------------------

#ifndef LIND_MARSHAL_CSTR_CAP
#define LIND_MARSHAL_CSTR_CAP 4096
#endif

// ---------------------------------------------------------------------------
// Shadow memory bump allocator
// ---------------------------------------------------------------------------

#define LIND_MARSHAL_ARENA_SIZE (128 * 1024)

static char   _lind_marshal_arena[LIND_MARSHAL_ARENA_SIZE];
static size_t _lind_marshal_arena_used = 0;

static inline void *_lind_marshal_alloc(size_t size) {
    size_t aligned = (size + 7u) & ~7u;
    if (_lind_marshal_arena_used + aligned > LIND_MARSHAL_ARENA_SIZE)
        return NULL;
    void *ptr = _lind_marshal_arena + _lind_marshal_arena_used;
    _lind_marshal_arena_used += aligned;
    return ptr;
}

static inline void _lind_marshal_reset(void) {
    _lind_marshal_arena_used = 0;
}

// ---------------------------------------------------------------------------
// Handle table (per-grate, C-owned)
// ---------------------------------------------------------------------------

#define LIND_HANDLE_TABLE_SIZE 64

struct _lind_handle_entry {
    uint64_t app_token;    // opaque index returned to source cage (never 0)
    uint64_t real_object;  // real pointer in handler cage
    uint32_t handle_class;
    uint8_t  in_use;
};

static struct _lind_handle_entry _lind_handle_table[LIND_HANDLE_TABLE_SIZE];
static uint64_t _lind_next_token = 1;

static inline uint64_t lind_register_handle(uint32_t cls, uint64_t real_obj) {
    for (int i = 0; i < LIND_HANDLE_TABLE_SIZE; i++) {
        if (!_lind_handle_table[i].in_use) {
            _lind_handle_table[i].app_token   = _lind_next_token++;
            _lind_handle_table[i].real_object  = real_obj;
            _lind_handle_table[i].handle_class = cls;
            _lind_handle_table[i].in_use       = 1;
            return _lind_handle_table[i].app_token;
        }
    }
    return 0;  // table full
}

static inline uint64_t lind_translate_handle(uint32_t cls, uint64_t app_token) {
    for (int i = 0; i < LIND_HANDLE_TABLE_SIZE; i++) {
        if (_lind_handle_table[i].in_use &&
            _lind_handle_table[i].app_token   == app_token &&
            _lind_handle_table[i].handle_class == cls)
            return _lind_handle_table[i].real_object;
    }
    return 0;
}

static inline void lind_release_handle(uint32_t cls, uint64_t app_token) {
    for (int i = 0; i < LIND_HANDLE_TABLE_SIZE; i++) {
        if (_lind_handle_table[i].in_use &&
            _lind_handle_table[i].app_token   == app_token &&
            _lind_handle_table[i].handle_class == cls) {
            _lind_handle_table[i].in_use = 0;
            return;
        }
    }
}

// ---------------------------------------------------------------------------
// C-string scan: measures length (including '\0') in source cage, capped.
// ---------------------------------------------------------------------------

static inline size_t _lind_measure_cstr(uint64_t src_ptr,
                                         uint64_t source_cage,
                                         uint64_t grate_cage) {
    char chunk[64];
    size_t total = 0;
    while (total < LIND_MARSHAL_CSTR_CAP) {
        size_t to_copy = sizeof(chunk);
        if (total + to_copy > LIND_MARSHAL_CSTR_CAP)
            to_copy = LIND_MARSHAL_CSTR_CAP - total;
        copy_data_between_cages(grate_cage, source_cage,
            src_ptr + (uint64_t)total, source_cage,
            (uint64_t)(uintptr_t)chunk, grate_cage,
            (uint64_t)to_copy, 0);
        for (size_t i = 0; i < to_copy; i++) {
            if (chunk[i] == '\0') return total + i + 1;  // include '\0'
        }
        total += to_copy;
    }
    return LIND_MARSHAL_CSTR_CAP;  // cap reached, no '\0' found
}

// ---------------------------------------------------------------------------
// Shadow tracking (flat buffers and nested structs)
// ---------------------------------------------------------------------------

// Per-pointer-field tracking entry used when marshalling structs.
struct _lind_ptr_field_track {
    uint32_t  offset;           // byte offset of this field within the parent struct
    uint64_t  orig_src_ptr;     // original source-cage ptr stored in this field
    uint8_t  *shadow_start;     // start of the child shadow buffer
    const struct lind_arg_spec *spec;  // field spec (for recursive post-call)
};

struct _lind_shadow {
    uint32_t               arg_index;
    uint64_t               source_ptr;
    void                  *shadow_ptr;
    size_t                 size;
    enum lind_ptr_direction direction;
    // Nested struct support (NULL layout = flat buffer):
    const struct lind_layout      *layout;
    struct _lind_ptr_field_track  *ptr_fields;
    uint32_t               n_ptr_fields;
};

// ---------------------------------------------------------------------------
// Forward declarations for recursive functions
// ---------------------------------------------------------------------------

static void *_lind_pre_ptr(uint64_t src_ptr, const struct lind_arg_spec *as,
                            uint64_t source_cage, uint64_t grate_cage,
                            const uint64_t *raw_args_or_sibling_shadow,
                            int in_struct_context,
                            struct _lind_ptr_field_track **out_ptr_fields,
                            uint32_t *out_n_ptr_fields);

static void _lind_post_struct(const struct _lind_shadow *s,
                               uint64_t source_cage, uint64_t grate_cage);

// ---------------------------------------------------------------------------
// Compute size for a PTR arg given context.
//   raw_or_sibling: top-level → raw_args array; struct → shadow of parent struct
//   in_struct      : 0 = top-level, 1 = inside struct field
// ---------------------------------------------------------------------------

static inline size_t _lind_compute_size(
    const struct lind_arg_spec *as,
    const uint64_t *raw_or_sibling,
    int in_struct,
    uint64_t source_cage, uint64_t grate_cage)
{
    switch (as->size_kind) {
        case LIND_SIZE_CONST:
            return (size_t)as->const_size;

        case LIND_SIZE_FROM_ARG:
            if (!in_struct)
                return (size_t)raw_or_sibling[as->size_arg_index];
            // In struct context: sibling field value is already in shadow at its offset.
            // The sibling is assumed to be a uint32_t scalar.
            return (size_t)(*(uint32_t *)((const uint8_t *)raw_or_sibling + as->size_arg_index));

        case LIND_SIZE_FROM_ARG_POINTEE: {
            // Read uint32_t from source cage at the address stored in raw_args[i].
            uint32_t size_val = 0;
            if (!in_struct) {
                copy_data_between_cages(grate_cage, source_cage,
                    raw_or_sibling[as->size_arg_index], source_cage,
                    (uint64_t)(uintptr_t)&size_val, grate_cage,
                    sizeof(uint32_t), 0);
            }
            return (size_t)size_val;
        }

        case LIND_SIZE_CSTR:
            // Caller must handle CSTR separately (needs src_ptr).
            return 0;

        default:
            return 0;
    }
}

// ---------------------------------------------------------------------------
// Pre-call: marshal one PTR argument (flat or structured).
// Returns the shadow pointer placed in handler_args.
// Stores nested ptr-field tracking in out_ptr_fields/out_n_ptr_fields (arena).
// ---------------------------------------------------------------------------

static void *_lind_pre_ptr(uint64_t src_ptr, const struct lind_arg_spec *as,
                            uint64_t source_cage, uint64_t grate_cage,
                            const uint64_t *raw_or_sibling, int in_struct,
                            struct _lind_ptr_field_track **out_ptr_fields,
                            uint32_t *out_n_ptr_fields)
{
    if (out_ptr_fields) *out_ptr_fields  = NULL;
    if (out_n_ptr_fields) *out_n_ptr_fields = 0;

    if (src_ptr == 0) return NULL;

    // Compute size
    size_t size;
    if (as->size_kind == LIND_SIZE_CSTR) {
        size = _lind_measure_cstr(src_ptr, source_cage, grate_cage);
    } else {
        size = _lind_compute_size(as, raw_or_sibling, in_struct, source_cage, grate_cage);
        if (size == 0 && as->layout == NULL) {
            // No size and no layout: treat as opaque, pass through.
            return (void *)(uintptr_t)src_ptr;
        }
    }

    // Determine allocation size: structured types use layout->struct_size.
    size_t alloc_size = (as->layout != NULL) ? as->layout->struct_size : size;
    if (alloc_size == 0) alloc_size = size;

    void *shadow = _lind_marshal_alloc(alloc_size);
    if (!shadow) return (void *)(uintptr_t)src_ptr;  // arena exhausted fallback

    // Copy-in for IN and INOUT (copy the raw bytes first).
    if (as->ptr_direction == LIND_PTR_IN || as->ptr_direction == LIND_PTR_INOUT) {
        copy_data_between_cages(grate_cage, source_cage,
            src_ptr, source_cage,
            (uint64_t)(uintptr_t)shadow, grate_cage,
            (uint64_t)alloc_size, 0);
    }

    // If there's a structured layout, walk it recursively.
    if (as->layout != NULL && as->layout->kind == LIND_LO_STRUCT) {
        const struct lind_layout *lo = as->layout;
        uint32_t max_ptr_fields = lo->nfields;
        struct _lind_ptr_field_track *ptf =
            (struct _lind_ptr_field_track *)_lind_marshal_alloc(
                max_ptr_fields * sizeof(struct _lind_ptr_field_track));
        uint32_t n = 0;

        for (uint32_t f = 0; f < lo->nfields; f++) {
            const struct lind_field *field = &lo->fields[f];
            if (!field->touched) continue;
            const struct lind_arg_spec *fspec = field->spec;

            if (fspec->kind == LIND_ARG_SCALAR) {
                // Already copied in the raw blit above.
                continue;
            }

            if (fspec->kind == LIND_ARG_HANDLE) {
                // Translate handle value in place.
                uint32_t tok = *(uint32_t *)((uint8_t *)shadow + field->offset);
                uint64_t real = lind_translate_handle(fspec->handle_class, (uint64_t)tok);
                *(uint32_t *)((uint8_t *)shadow + field->offset) = (uint32_t)real;
                continue;
            }

            if (fspec->kind == LIND_ARG_PTR) {
                // Read the source-cage ptr from the shadow (copied from source struct).
                uint32_t child_src_u32 =
                    *(uint32_t *)((uint8_t *)shadow + field->offset);
                uint64_t child_src = (uint64_t)child_src_u32;
                if (child_src == 0) continue;

                // Size uses shadow as "sibling" context.
                size_t child_size;
                if (fspec->size_kind == LIND_SIZE_CSTR) {
                    child_size = _lind_measure_cstr(child_src, source_cage, grate_cage);
                } else if (fspec->size_kind == LIND_SIZE_FROM_ARG) {
                    // Sibling field at index = size_arg_index; read uint32 from shadow.
                    uint32_t sib_off = lo->fields[fspec->size_arg_index].offset;
                    child_size = (size_t)(*(uint32_t *)((uint8_t *)shadow + sib_off));
                } else {
                    child_size = _lind_compute_size(fspec, NULL, 0, source_cage, grate_cage);
                    if (child_size == 0 && fspec->layout == NULL) {
                        // No size: leave field as-is.
                        continue;
                    }
                }
                if (child_size == 0) continue;

                void *child_shadow = _lind_marshal_alloc(child_size);
                if (!child_shadow) continue;

                if (fspec->ptr_direction == LIND_PTR_IN ||
                    fspec->ptr_direction == LIND_PTR_INOUT) {
                    copy_data_between_cages(grate_cage, source_cage,
                        child_src, source_cage,
                        (uint64_t)(uintptr_t)child_shadow, grate_cage,
                        (uint64_t)child_size, 0);
                }

                // Overwrite the field in the shadow with the child shadow address.
                *(uint32_t *)((uint8_t *)shadow + field->offset) =
                    (uint32_t)(uintptr_t)child_shadow;

                // Record for post-call fixup.
                if (ptf && n < max_ptr_fields) {
                    ptf[n].offset        = field->offset;
                    ptf[n].orig_src_ptr  = child_src;
                    ptf[n].shadow_start  = (uint8_t *)child_shadow;
                    ptf[n].spec          = fspec;
                    n++;
                }
            }
        }

        if (out_ptr_fields)   *out_ptr_fields   = ptf;
        if (out_n_ptr_fields) *out_n_ptr_fields  = n;
    }

    return shadow;
}

// ---------------------------------------------------------------------------
// Post-call: copy-back for a nested-struct shadow.
// ---------------------------------------------------------------------------

static void _lind_post_struct(const struct _lind_shadow *s,
                               uint64_t source_cage, uint64_t grate_cage)
{
    if (s->direction != LIND_PTR_OUT && s->direction != LIND_PTR_INOUT)
        return;

    const struct lind_layout *lo = s->layout;

    // Step 1: copy the child pointer data back to source cage, then fix up ptr fields.
    for (uint32_t p = 0; p < s->n_ptr_fields; p++) {
        const struct _lind_ptr_field_track *ptf = &s->ptr_fields[p];
        if (ptf->spec->ptr_direction == LIND_PTR_OUT ||
            ptf->spec->ptr_direction == LIND_PTR_INOUT) {

            // Determine the size to copy back.
            // Read current shadow ptr from the struct shadow at this field's offset.
            uint32_t cur_shadow_u32 =
                *(uint32_t *)((uint8_t *)s->shadow_ptr + ptf->offset);
            uint8_t *cur_shadow_ptr = (uint8_t *)(uintptr_t)cur_shadow_u32;

            // How many bytes to copy: from original shadow_start up to wherever
            // the handler left the pointer (may be advanced for INOUT buffers).
            size_t copy_back_size;
            if (cur_shadow_ptr >= ptf->shadow_start) {
                copy_back_size = (size_t)(cur_shadow_ptr - ptf->shadow_start);
            } else {
                copy_back_size = 0;
            }

            // Always copy at least the originally-allocated child buffer data back.
            // Use the field's size if we can infer it.
            if (copy_back_size == 0 && lo != NULL) {
                // Find the sibling size field if available.
                const struct lind_field *fld = NULL;
                for (uint32_t f = 0; f < lo->nfields; f++) {
                    if (lo->fields[f].offset == ptf->offset) { fld = &lo->fields[f]; break; }
                }
                if (fld && ptf->spec->size_kind == LIND_SIZE_FROM_ARG) {
                    uint32_t sib_off = lo->fields[ptf->spec->size_arg_index].offset;
                    copy_back_size = (size_t)(*(uint32_t *)((uint8_t *)s->shadow_ptr + sib_off));
                } else if (ptf->spec->size_kind == LIND_SIZE_CONST) {
                    copy_back_size = (size_t)ptf->spec->const_size;
                }
            }

            if (copy_back_size > 0) {
                copy_data_between_cages(grate_cage, source_cage,
                    (uint64_t)(uintptr_t)ptf->shadow_start, grate_cage,
                    ptf->orig_src_ptr, source_cage,
                    (uint64_t)copy_back_size, 0);
            }
        }
    }

    // Step 2: copy the whole struct shadow back to source (writes scalar fields +
    //         whatever ptr values the handler left).
    copy_data_between_cages(grate_cage, source_cage,
        (uint64_t)(uintptr_t)s->shadow_ptr, grate_cage,
        s->source_ptr, source_cage,
        (uint64_t)s->size, 0);

    // Step 3: fix up ptr fields — overwrite with source-cage addresses, not shadow addrs.
    for (uint32_t p = 0; p < s->n_ptr_fields; p++) {
        const struct _lind_ptr_field_track *ptf = &s->ptr_fields[p];

        // Compute delta = how far the handler advanced the ptr.
        uint32_t cur_shadow_u32 =
            *(uint32_t *)((uint8_t *)s->shadow_ptr + ptf->offset);
        uint8_t *cur_shadow_ptr = (uint8_t *)(uintptr_t)cur_shadow_u32;
        int64_t delta = (int64_t)(cur_shadow_ptr - ptf->shadow_start);

        // New source-cage ptr = original + delta.
        uint32_t new_src_u32 = (uint32_t)(int32_t)
            ((int64_t)(int32_t)(uint32_t)ptf->orig_src_ptr + delta);

        copy_data_between_cages(grate_cage, source_cage,
            (uint64_t)(uintptr_t)&new_src_u32, grate_cage,
            s->source_ptr + ptf->offset, source_cage,
            sizeof(uint32_t), 0);
    }
}

// ---------------------------------------------------------------------------
// Core dispatch
// ---------------------------------------------------------------------------

static inline uint64_t lind_marshal_dispatch(
    void                           *typed_handler,
    const struct lind_marshal_spec *spec,
    uint64_t                        source_cage,
    uint64_t                        grate_cage,
    uint64_t                       *raw_args,
    uint32_t                        nargs)
{
    _lind_marshal_reset();
    _lind_marshal_source_cage = source_cage;
    _lind_marshal_grate_cage  = grate_cage;

    uint64_t handler_args[16] = {0};
    struct _lind_shadow shadows[16];
    uint32_t nshadows = 0;

    // --- Pre-call ---
    for (uint32_t i = 0; i < nargs && i < spec->nargs; i++) {
        const struct lind_arg_spec *as = &spec->args[i];

        switch (as->kind) {
            case LIND_ARG_SCALAR:
                handler_args[i] = raw_args[i];
                break;

            case LIND_ARG_HANDLE:
                handler_args[i] = lind_translate_handle(as->handle_class, raw_args[i]);
                break;

            case LIND_ARG_PTR: {
                uint64_t src_ptr = raw_args[i];
                if (src_ptr == 0) { handler_args[i] = 0; break; }

                struct _lind_ptr_field_track *ptf = NULL;
                uint32_t n_ptf = 0;
                void *shadow = _lind_pre_ptr(src_ptr, as,
                                              source_cage, grate_cage,
                                              raw_args, 0,
                                              &ptf, &n_ptf);
                handler_args[i] = (uint64_t)(uintptr_t)shadow;

                size_t shadow_size = (as->layout != NULL)
                    ? as->layout->struct_size
                    : _lind_compute_size(as, raw_args, 0, source_cage, grate_cage);
                if (as->size_kind == LIND_SIZE_CSTR && shadow_size == 0)
                    shadow_size = _lind_measure_cstr(src_ptr, source_cage, grate_cage);

                if (shadow != (void *)(uintptr_t)src_ptr) {
                    shadows[nshadows].arg_index    = i;
                    shadows[nshadows].source_ptr   = src_ptr;
                    shadows[nshadows].shadow_ptr   = shadow;
                    shadows[nshadows].size         = shadow_size;
                    shadows[nshadows].direction    = as->ptr_direction;
                    shadows[nshadows].layout       = as->layout;
                    shadows[nshadows].ptr_fields   = ptf;
                    shadows[nshadows].n_ptr_fields = n_ptf;
                    nshadows++;
                }
                break;
            }
        }
    }

    // --- Handler ---
    uint64_t handler_ret = ((lind_handler6_t)typed_handler)(
        handler_args[0], handler_args[1], handler_args[2],
        handler_args[3], handler_args[4], handler_args[5]);

    // --- Post-call ---
    for (uint32_t s = 0; s < nshadows; s++) {
        if (shadows[s].layout != NULL) {
            _lind_post_struct(&shadows[s], source_cage, grate_cage);
        } else if (shadows[s].direction == LIND_PTR_OUT ||
                   shadows[s].direction == LIND_PTR_INOUT) {
            copy_data_between_cages(grate_cage, source_cage,
                (uint64_t)(uintptr_t)shadows[s].shadow_ptr, grate_cage,
                shadows[s].source_ptr, source_cage,
                (uint64_t)shadows[s].size, 0);
        }
    }

    // --- Return translation ---
    uint64_t result;
    switch (spec->ret.kind) {
        case LIND_RET_VOID:
            result = 0;
            break;

        case LIND_RET_PTR_ALIAS_ARG:
            result = raw_args[spec->ret.alias_arg_index];
            break;

        case LIND_RET_PTR_INTO_ARG: {
            // handler_ret is a pointer into a shadow buffer.
            // Translate: result = source_ptr + (handler_ret - shadow_ptr).
            uint32_t idx = spec->ret.alias_arg_index;
            if (handler_ret == 0) {
                result = 0;  // NULL return (not found)
                break;
            }
            for (uint32_t s = 0; s < nshadows; s++) {
                if (shadows[s].arg_index == idx) {
                    int64_t off = (int64_t)handler_ret
                                - (int64_t)(uintptr_t)shadows[s].shadow_ptr;
                    result = (uint64_t)((int64_t)(int32_t)(uint32_t)shadows[s].source_ptr
                                       + off);
                    goto done;
                }
            }
            result = handler_ret;  // fallback
            break;
        }

        case LIND_RET_HANDLE:
            result = lind_register_handle(spec->ret.handle_class, handler_ret);
            break;

        case LIND_RET_FORCE_LOCAL:
        case LIND_RET_SCALAR:
        default:
            result = handler_ret;
            break;
    }
done:
    _lind_marshal_reset();
    return result;
}

// ---------------------------------------------------------------------------
// Macro: generate raw handler wrapper for register_lib_handler.
// Defines: int lind_mh_##name(uint64_t cageid, u64 a1, u64 a1c, ...)
// Source cage inferred from first non-zero argNcage.
// ---------------------------------------------------------------------------

#define LIND_DEFINE_MARSHAL_HANDLER(name, spec_ptr, typed_fn)                  \
static int lind_mh_##name(                                                      \
    uint64_t _cageid,                                                           \
    uint64_t _a1, uint64_t _a1c,                                                \
    uint64_t _a2, uint64_t _a2c,                                                \
    uint64_t _a3, uint64_t _a3c,                                                \
    uint64_t _a4, uint64_t _a4c,                                                \
    uint64_t _a5, uint64_t _a5c,                                                \
    uint64_t _a6, uint64_t _a6c)                                                \
{                                                                               \
    uint64_t _raw[6]   = { _a1, _a2, _a3, _a4, _a5, _a6 };                    \
    uint64_t _cages[6] = { _a1c, _a2c, _a3c, _a4c, _a5c, _a6c };              \
    uint64_t _src_cage = 0;                                                     \
    for (int _i = 0; _i < 6 && _src_cage == 0; _i++)                           \
        _src_cage = _cages[_i];                                                 \
    return (int)lind_marshal_dispatch(                                          \
        (void *)(uintptr_t)(typed_fn),                                          \
        (spec_ptr), _src_cage, _cageid, _raw,                                   \
        (spec_ptr)->nargs);                                                     \
}
