// lind_marshal.h — Automated argument marshalling for Lind grates (Stage 1 + 3).
//
// Include this header in a grate for automatic copy-in/copy-out marshalling.
// The grate registers a raw handler (generated by LIND_DEFINE_MARSHAL_HANDLER)
// and provides a lind_marshal_spec describing each argument.  The runtime does
// the rest: shadow allocation, copy-in, handler call, copy-out, return translation.
//
// Fail-closed: a marshalling contract violation (unrecognized/unconfigured
// pointer size, shadow-arena exhaustion, a failed cross-cage copy, or an
// invalid/exhausted handle) traps immediately (see _lind_marshal_abort)
// rather than ever handing the handler a foreign-cage pointer or an
// unvalidated field.
//
// --- Argument kinds ---
//   LIND_ARG_SCALAR  — pass value directly; no memory copy
//   LIND_ARG_PTR     — shadow buffer; direction + size_kind control copy behavior
//                      NULL → passed through as-is, no alloc/copy
//   LIND_ARG_HANDLE  — opaque token; value translated through handle table; pointee never copied
//                      0 → passed through as-is (no handle); a nonzero token
//                      that fails to translate traps
//
// --- Size kinds (for LIND_ARG_PTR) ---
//   LIND_SIZE_CONST           — const_size bytes
//   LIND_SIZE_FROM_ARG        — scalar value of raw_args[size_arg_index]
//                               (in struct context: sibling field at fields[size_arg_index])
//   LIND_SIZE_FROM_ARG_POINTEE— *(uint32_t at raw_args[size_arg_index]) (e.g. compress2 *destLen)
//   LIND_SIZE_CSTR            — scan for '\0', capped at LIND_MARSHAL_CSTR_CAP
//   LIND_SIZE_EXPR            — size_expr's evaluated lind_extent_expr tree value (bytes)
//
// --- Return kinds ---
//   LIND_RET_VOID             — return 0
//   LIND_RET_SCALAR           — handler return value directly
//   LIND_RET_PTR_ALIAS_ARG    — original source-cage ptr of arg[alias_arg_index]
//   LIND_RET_PTR_INTO_ARG     — pointer offset inside arg[alias_arg_index]'s shadow
//   LIND_RET_HANDLE           — register handler's return as a new handle; return app_token
//   LIND_RET_FORCE_LOCAL      — not marshalable remotely; runtime runs Local
//
// --- Nested structs ---
//   Set lind_arg_spec.layout to a lind_layout describing the struct.
//   Fields with touched=1 are marshalled recursively.  Pointer fields in the struct
//   use the same arg_spec recursion; size_arg_index refers to a sibling field index.
//
// --- Handle table (per-grate static) ---
//   lind_register_handle(class, real_ptr) → app_token (0 = table full)
//   lind_translate_handle(class, app_token) → real_ptr (or 0 if not found)
//   lind_translate_handle_checked(class, app_token, &found) → real_ptr,
//     with *found distinguishing lookup failure from a genuine 0 result
//   lind_release_handle(class, app_token)
//
// --- Handler signature ---
//   All handlers must have the uniform lind_handler6_t signature (WASM type-check).
//   Use LIND_AS_PTR / LIND_AS_SIZE / LIND_AS_INT / LIND_RET_PTR / LIND_RET_INT helpers.

#pragma once

#include <lind_syscall.h>
#include <stdint.h>
#include <stddef.h>
// string.h/stdio.h are not used by this header itself; a grate that interposes
// libc functions defines LIND_MARSHAL_NO_LIBC_HEADERS to skip them, so it can
// `extern`-declare libc symbols without prototype conflicts.
#ifndef LIND_MARSHAL_NO_LIBC_HEADERS
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#endif

// ---------------------------------------------------------------------------
// Handler argument / return cast helpers
// ---------------------------------------------------------------------------

#define LIND_AS_PTR(u)    ((void *)(uintptr_t)(u))
#define LIND_AS_CPTR(u)   ((const void *)(uintptr_t)(u))
#define LIND_AS_STR(u)    ((char *)(uintptr_t)(u))
#define LIND_AS_CSTR(u)   ((const char *)(uintptr_t)(u))
#define LIND_AS_SIZE(u)   ((size_t)(u))
#define LIND_AS_INT(u)    ((int)(u))
#define LIND_AS_UINT(u)   ((unsigned int)(u))
#define LIND_AS_LONG(u)   ((long)(u))
#define LIND_AS_ULONG(u)  ((unsigned long)(u))

#define LIND_RET_PTR(p)   ((uint64_t)(uintptr_t)(p))
#define LIND_RET_INT(v)   ((uint64_t)(uint32_t)(int)(v))
#define LIND_RET_LONG(v)  ((uint64_t)(long)(v))
#define LIND_RET_ULONG(v) ((uint64_t)(unsigned long)(v))

// All handlers passed to lind_marshal_dispatch must match this signature.
typedef uint64_t (*lind_handler6_t)(uint64_t, uint64_t, uint64_t,
                                    uint64_t, uint64_t, uint64_t);

// ---------------------------------------------------------------------------
// Metadata types
// ---------------------------------------------------------------------------

// Forward declarations for mutual recursion between lind_arg_spec / lind_layout.
struct lind_arg_spec;
struct lind_layout;

enum lind_arg_kind {
    LIND_ARG_SCALAR = 0,
    LIND_ARG_PTR    = 1,
    LIND_ARG_HANDLE = 2,   // opaque token; translate via handle table, never deep-copy
};

enum lind_ptr_direction {
    LIND_PTR_IN    = 0,
    LIND_PTR_OUT   = 1,
    LIND_PTR_INOUT = 2,
};

enum lind_size_kind {
    LIND_SIZE_NONE              = 0,
    LIND_SIZE_CONST             = 1,  // const_size bytes
    LIND_SIZE_FROM_ARG          = 2,  // value of raw_args[i] (top-level) or sibling field[i] (struct)
    LIND_SIZE_FROM_ARG_POINTEE  = 3,  // *(uint32_t at raw_args[i]) — two-pass, read from source cage
    LIND_SIZE_CSTR              = 4,  // scan for '\0', capped at LIND_MARSHAL_CSTR_CAP
    LIND_SIZE_PTR_ARRAY         = 5,  // NULL-terminated array of pointers (argv); `element` describes each
    // Strided vector: bytes = (1 + (n-1)*stride) * const_size, where n and
    // stride are each evaluated per their own lind_extent_operand (a direct
    // argument value, a value loaded through a pointer argument, or a
    // compile-time constant baked into the spec itself -- see that struct's
    // doc), and const_size is the element size. n<=0 sizes to 0 (an empty
    // vector, not an error); a negative stride read from the plain
    // operand is rejected (fail closed) rather than mishandled -- a
    // caller that has actually proven a magnitude-based envelope is safe
    // (e.g. a library whose own wrapper rebases its base pointer forward
    // before walking backward) represents that proof via the *_expr form
    // instead, with an explicit ABS node -- see _lind_compute_size's doc
    // for both.
    // Plain n*const_size (LIND_SIZE_FROM_ARG) undercounts any call whose
    // stride isn't 1: only every stride'th element is itself touched, but
    // the elements in between are still part of the buffer the real
    // function may read or write. A plain contiguous walk (stride==1, the
    // common case for an ordinary `x[i]` loop with no separate increment
    // argument at all) still goes through this same kind, with its stride
    // operand sourced as LIND_EXTENT_CONSTANT rather than read from an
    // argument.
    LIND_SIZE_STRIDE_VECTOR     = 6,
    // Byte count IS a general lind_extent_expr tree's own evaluated value
    // (see that type's own doc) -- e.g. a packed-matrix footprint
    // (`n*(n+1)/2*elem_size`) or a leading-dimension-scaled envelope
    // (`lda*max(m,n)*elem_size`) that no single lind_extent_operand leaf
    // can represent. `size_expr` points at the tree; evaluated via
    // _lind_eval_extent_expr, which already enforces the non-negative/
    // size_t-range final checks this kind needs -- unlike
    // LIND_SIZE_STRIDE_VECTOR's own n/stride sub-operands below, this
    // value already IS the complete byte count, not an intermediate one.
    LIND_SIZE_EXPR              = 7,
};

// One scalar input to a size computation (currently: LIND_SIZE_STRIDE_VECTOR's
// n and stride): the argument's own value, an i32 loaded through the
// pointer at that argument via the checked cross-cage copy path (for
// calling conventions that pass scalars by reference, e.g. Fortran's,
// where a length or stride argument is a pointer to the value, not the
// value itself), or a value baked into the spec at generation time with no
// argument behind it at all (a genuine compile-time-constant stride, e.g.
// an ordinary `x[i]` loop with no separate increment parameter). `source`
// is intentionally its own dimension, independent of arg_index, so a new
// load shape (a different width, or a different byte layout) extends this
// enum without touching the spec field that names which argument the
// value comes from.
enum lind_extent_source {
    LIND_EXTENT_VALUE       = 0,  // raw_args[arg_index] is the value
    LIND_EXTENT_POINTEE_I32 = 1,  // raw_args[arg_index] is a pointer to it
    LIND_EXTENT_CONSTANT    = 2,  // const_value IS the value; arg_index unused
};

struct lind_extent_operand {
    uint32_t                 arg_index;   // meaningful for VALUE/POINTEE_I32 only
    enum lind_extent_source  source;
    uint32_t                 const_value; // meaningful for CONSTANT only
};

// ---------------------------------------------------------------------------
// General bounded extent-expression tree.
//
// lind_extent_operand above is a single leaf: a direct argument value, a
// value loaded through a pointer argument, or a spec-time constant. Some
// real extent formulas this transport needs to carry are not a single
// leaf -- a packed-matrix footprint ("n*(n+1)/2"), or a leading-dimension-
// scaled envelope ("lda*max(m,n)"). This type is the general form both of
// those (and lind_extent_operand's own three leaf shapes) are instances
// of: a small, explicitly depth-bounded expression tree, evaluated to a
// single non-negative size at dispatch time by _lind_eval_extent_expr.
//
// Every leaf kind here has the exact same semantics as the matching
// lind_extent_operand source (LIND_EXPR_ARG_VALUE == LIND_EXTENT_VALUE,
// LIND_EXPR_ARG_POINTEE_I32 == LIND_EXTENT_POINTEE_I32): both ultimately
// read through _lind_read_arg_leaf_i64, the one place that actually
// touches cross-cage memory for an extent leaf, so there is exactly one
// implementation of that read, not two that could drift apart.
//
// A plain "divide" (exact division, not rounding) has no node of its own:
// every currently-known caller needing division is a packed-storage
// footprint of the form n*(n+1)/2, where the dividend is always even, so
// ceiling and exact division agree -- see LIND_EXPR_CEIL_DIVIDE's own doc.
// There is likewise no "subtract" node: nothing this transport currently
// accepts needs one. Both are deliberate, narrow omissions, not oversights
// -- widen this enum, and the shared evaluator below, if a future input
// genuinely needs either.
enum lind_extent_expr_kind {
    LIND_EXPR_CONSTANT        = 0,  // const_value is the value (0 <= const_value <= INT64_MAX)
    LIND_EXPR_ARG_VALUE       = 1,  // raw_args[arg_index] is the value
    LIND_EXPR_ARG_POINTEE_I32 = 2,  // raw_args[arg_index] is a pointer to it
    LIND_EXPR_ABS             = 3,  // |lhs|
    // A real BLAS/LAPACK-style callee always validates every scalar
    // dimension argument before ever touching the array whose size one
    // of these formulas computes -- that is the entire point of the
    // XERBLA convention such libraries document and real conformance
    // test suites rely on (e.g. OpenBLAS's own CBLAS conformance suite
    // deliberately calls `cblas_dsymv(..., n=-1, ...)` specifically to
    // prove the real function rejects it gracefully). So a negative
    // dimension reaching this evaluator is never a request this
    // marshaller should itself service with real memory -- but it is
    // equally never a reason to abort the whole process pre-emptively,
    // since the real callee was always going to reject it anyway, more
    // gracefully, the moment it is actually called. PRODUCT/MAX/ADD
    // therefore TAINT (see _lind_eval_extent_expr_depth's own
    // `tainted` parameter) rather than abort when an operand is
    // negative, and the tree's final value resolves to byte count 0 --
    // an empty, harmless shadow -- once any taint anywhere in the tree
    // is detected, the same outcome as a direct non-positive final
    // value. Checking only the ROOT's final numeric value is not
    // enough on its own: e.g. product(-2, -3) computes to a
    // deceptively-positive 6 even though both individual "sizes" were
    // already nonsensical -- the explicit taint flag catches that
    // case, which a plain final-value sign check would miss.
    LIND_EXPR_PRODUCT         = 4,  // lhs * rhs, overflow-checked
    LIND_EXPR_MAX             = 5,  // max(lhs, rhs)
    LIND_EXPR_ADD             = 6,  // lhs + rhs, overflow-checked
    // Ceiling division: ceil(lhs / rhs). A negative lhs taints the same
    // way PRODUCT/MAX/ADD's operands do (see above) -- every currently-
    // known use (packed-storage n*(n+1)/2) feeds lhs from a real
    // dimension argument, exactly the shape a conformance test can feed
    // a deliberate negative value. rhs stays a hard requirement (abort
    // if non-positive): every currently-known use sources rhs from a
    // literal constant baked into the formula itself (e.g. "divide by
    // 2"), never from a caller-supplied argument, so a non-positive rhs
    // is a malformed SPEC, not a deliberately-invalid call worth
    // tolerating -- and this operator's own truncating-division
    // semantics do not degrade a negative lhs to a non-positive result
    // the way PRODUCT's multiplication does, so letting lhs through
    // unchecked here (rather than tainting) could otherwise yield a
    // small, deceptively-positive result from a genuinely invalid
    // dimension.
    LIND_EXPR_CEIL_DIVIDE     = 7,
};

// Hard ceiling on tree depth, enforced at evaluation time regardless of
// what generation-time validation already did: a recursive evaluator
// walking a sufficiently deep tree risks exhausting the real (wasm) call
// stack, which is a resource bound independent of whether the tree's
// VALUES are otherwise well-formed. Chosen generously relative to any
// currently-known extent formula this transport carries (the deepest is
// 4 levels: ceil_divide(product(n, add(n, 1)), 2)).
#define LIND_EXTENT_EXPR_MAX_DEPTH 16

// Hard ceiling on the TOTAL number of nodes visited evaluating one tree --
// independent of, and in addition to, the depth bound above. Depth alone
// bounds how deep the recursion goes, not how much WORK one evaluation
// does: a full binary tree only 16 levels deep can still require on the
// order of 2^16 node visits (and, if any of those are
// LIND_EXPR_ARG_POINTEE_I32 leaves, that many cross-cage reads), so a
// generated or malformed tree that is wide rather than deep would sail
// past the depth check entirely. Enforced here at evaluation time
// regardless of what generation-time validation already did, the same
// reasoning as the depth bound. Chosen generously relative to any
// currently-known extent formula (the packed-storage formula below needs
// 7 nodes).
#define LIND_EXTENT_EXPR_MAX_NODES 64

// The concrete ABI width/signedness of a LIND_EXPR_ARG_VALUE leaf's raw
// argument slot. Required rather than assumed: raw_args[] entries are
// passed at whatever real width/signedness the interposed function's own
// parameter has (a plain `int` is i32, but a `long`/pointer-sized count or
// an explicitly unsigned parameter is not), and guessing wrong silently
// corrupts the value, not just its label -- the same reasoning
// wasm_scalar_ctype (gen_v2_adapter.py) already applies to a V2 adapter's
// own parameters. Meaningful for LIND_EXPR_ARG_VALUE only;
// LIND_EXPR_ARG_POINTEE_I32 is always a 4-byte signed int pointee, named
// for exactly that width (ignores this field entirely).
enum lind_extent_leaf_type {
    LIND_EXTENT_LEAF_I32 = 0,  // sign-extend the low 32 bits (default: a
                               // plain C `int`, the common case)
    LIND_EXTENT_LEAF_U32 = 1,  // zero-extend the low 32 bits
    LIND_EXTENT_LEAF_I64 = 2,  // the full 64-bit slot, reinterpreted signed
    // The full 64-bit slot, reinterpreted unsigned -- representable only
    // when its value fits int64_t's non-negative range (top bit clear):
    // this evaluator's entire internal representation is int64_t (see
    // this struct's own doc), so a genuinely huge u64 value -- one no
    // real extent needs -- is rejected rather than silently wrapped into
    // a negative number.
    LIND_EXTENT_LEAF_U64 = 3,
};

// A node in the tree. Leaf fields (arg_index/const_value/leaf_type) are
// meaningful only for the three leaf kinds (leaf_type for ARG_VALUE
// only); lhs/rhs are meaningful only for the operator kinds (ABS uses lhs
// only, and ignores rhs). A NULL lhs/rhs on an operator node is a
// malformed spec, caught by _lind_eval_extent_expr rather than assumed
// well-formed -- the same fail-closed posture as every other
// lind_marshal.h structure.
struct lind_extent_expr {
    enum lind_extent_expr_kind      kind;
    uint32_t                        arg_index;
    enum lind_extent_leaf_type      leaf_type;
    uint64_t                        const_value;
    const struct lind_extent_expr  *lhs;
    const struct lind_extent_expr  *rhs;
};

enum lind_return_kind {
    LIND_RET_VOID          = 0,
    LIND_RET_SCALAR        = 1,
    LIND_RET_PTR_ALIAS_ARG = 2,  // return original source-cage ptr of arg[alias_arg_index]
    LIND_RET_PTR_INTO_ARG  = 3,  // return ptr offset inside arg[alias_arg_index]'s shadow (memchr)
    LIND_RET_HANDLE        = 4,  // register handler's return as new handle; return app_token
    LIND_RET_FORCE_LOCAL   = 5,  // not marshalable remotely; ensure Local placement
};

// Struct field for recursive lind_layout.
struct lind_field {
    uint32_t              offset;   // byte offset within the record
    struct lind_arg_spec *spec;     // recursive: a field may be ptr/handle/scalar
    uint8_t               touched;  // KSplit projection: marshal only if 1
};

// Pointee layout descriptor.  NULL layout = opaque bytes (flat buffer).
enum lind_layout_kind { LIND_LO_BYTES = 0, LIND_LO_STRUCT = 1, LIND_LO_UNION = 2 };

struct lind_layout {
    enum lind_layout_kind kind;
    uint32_t              nfields;
    struct lind_field    *fields;
    uint32_t              discriminator_field;  // UNION only: field index that selects the arm
    uint32_t              struct_size;          // total bytes (largest arm for unions)
};

struct lind_arg_spec {
    enum lind_arg_kind      kind;
    // PTR fields:
    enum lind_ptr_direction ptr_direction;
    enum lind_size_kind     size_kind;
    uint64_t                const_size;
    uint32_t                size_arg_index;  // arg index (top) or sibling field index (struct)
    // LIND_SIZE_STRIDE_VECTOR only: the count (n) and stride operands.
    // Independent of size_arg_index above (which LIND_SIZE_FROM_ARG and
    // LIND_SIZE_FROM_ARG_POINTEE keep their own, unrelated meaning for).
    struct lind_extent_operand size_operand;
    struct lind_extent_operand stride_operand;
    // LIND_SIZE_STRIDE_VECTOR only, optional: when non-NULL, each overrides
    // the matching single-leaf operand above with a general lind_extent_expr
    // tree (e.g. `abs(incx)` for a stride that must be positive regardless
    // of the real argument's sign) -- needed for a formula no single leaf
    // can represent. NULL keeps the plain lind_extent_operand behavior
    // above unchanged; a non-NULL size_operand_expr/stride_operand_expr
    // always takes precedence over size_operand/stride_operand when
    // computing that same slot, never blended with it.
    const struct lind_extent_expr *size_operand_expr;
    const struct lind_extent_expr *stride_operand_expr;
    // LIND_SIZE_EXPR only: the complete byte count (see that enum value's
    // own doc).
    const struct lind_extent_expr *size_expr;
    struct lind_layout     *layout;          // NULL = flat buffer; non-NULL = structured pointee
    // PTR_ARRAY: describes each element of a NULL-terminated pointer array (argv).
    struct lind_arg_spec   *element;
    // HANDLE fields:
    uint32_t                handle_class;
    // OUT pointer-to-pointer that aliases an argument (strtol's char** endptr):
    // this is an OUT ptr to a 4-byte slot; the value the callee writes there is a
    // pointer INTO arg[out_ptr_into_arg1 - 1]. On copy-back, translate that inner
    // pointer from grate-shadow offset to the source cage's buffer.
    // 1-based so the designated-init default (0) means "not applicable".
    uint32_t                out_ptr_into_arg1;
    // Bitmask -- see LIND_ARGSPEC_ALLOW_ONE_PAST. Zero-initializes to "no
    // flags set" under designated init, so an unset spec gets the strict
    // (one-past rejected) default.
    uint32_t                flags;
};

// A callee-written pointer landing exactly at base+len ("one-past-the-end",
// a valid pointer VALUE per C semantics even though it can't be
// dereferenced) is the normal, expected outcome for some APIs -- a
// cursor-advance OUT buffer that ends up completely filled (zlib's
// next_out) -- but meaningless or never legitimately reachable for others
// (a memchr-style scan, whose one-past result would be the byte just past
// the searched region, never a matched byte). Whether one-past is even
// possible depends entirely on the specific pointer relationship the spec
// describes, so it is never assumed: a field/arg/return spec must opt in
// explicitly via this flag, or a genuinely-one-past value from the callee
// is rejected as being outside its shadow the same as anything else out of
// range.
#define LIND_ARGSPEC_ALLOW_ONE_PAST 0x1u

struct lind_return_spec {
    enum lind_return_kind kind;
    uint32_t              alias_arg_index;  // PTR_ALIAS_ARG / PTR_INTO_ARG / HANDLE
    uint32_t              handle_class;     // RET_HANDLE: class for new handle registration
    uint32_t               flags;           // LIND_ARGSPEC_ALLOW_ONE_PAST (PTR_INTO_ARG only)
};

struct lind_marshal_spec {
    uint32_t              nargs;
    struct lind_arg_spec  args[16];
    struct lind_return_spec ret;
};

// ---------------------------------------------------------------------------
// Current-call cage ID accessors (valid inside handler invocation)
// ---------------------------------------------------------------------------

static uint64_t _lind_marshal_source_cage = 0;
static uint64_t _lind_marshal_grate_cage  = 0;

#define LIND_SOURCE_CAGE() (_lind_marshal_source_cage)
#define LIND_GRATE_CAGE()  (_lind_marshal_grate_cage)

// ---------------------------------------------------------------------------
// C-string scan cap
// ---------------------------------------------------------------------------

#ifndef LIND_MARSHAL_CSTR_CAP
#define LIND_MARSHAL_CSTR_CAP 4096
#endif

// ---------------------------------------------------------------------------
// Shadow memory bump allocator
// ---------------------------------------------------------------------------

// Must be large enough to hold every shadow buffer a single real call
// might need AT ONCE, not just the largest individual one -- a function
// that marshals two or more independently-sized buffers (e.g. a matrix-
// copy extension's separate source and destination matrices) needs the
// SUM of their sizes live simultaneously, reset only once the whole call
// returns. 128KiB proved too small for a real call this corpus already
// generates a V2 handler for (OpenBLAS's `domatcopy_`/`somatcopy_`
// family copying two independent ~100x100 double matrices, ~80000 bytes
// each): a request that would otherwise marshal correctly instead found
// the arena already exhausted by the first matrix and aborted. 1MiB
// gives real headroom above every two-matrix case the current corpus
// produces while staying a trivial static reservation for a wasm32
// grate's linear memory.
#ifndef LIND_MARSHAL_ARENA_SIZE
#define LIND_MARSHAL_ARENA_SIZE (1024 * 1024)
#endif

static char   _lind_marshal_arena[LIND_MARSHAL_ARENA_SIZE];
static size_t _lind_marshal_arena_used = 0;

static inline void *_lind_marshal_alloc(size_t size) {
    // size + 7u can overflow for a size near SIZE_MAX, wrapping `aligned`
    // to a small value and letting a huge request pass the space check as
    // if it were tiny. Reject that first, then compare against the actual
    // remaining space via subtraction (not used+aligned, which could
    // itself overflow) -- _lind_marshal_arena_used <= LIND_MARSHAL_ARENA_SIZE
    // is an invariant this function maintains, so the subtraction is safe.
    if (size > (size_t)-1 - 7u) return NULL;
    size_t aligned = (size + 7u) & ~(size_t)7u;
    if (aligned > LIND_MARSHAL_ARENA_SIZE - _lind_marshal_arena_used)
        return NULL;
    void *ptr = _lind_marshal_arena + _lind_marshal_arena_used;
    _lind_marshal_arena_used += aligned;
    return ptr;
}

static inline void _lind_marshal_reset(void) {
    _lind_marshal_arena_used = 0;
}

// ---------------------------------------------------------------------------
// Fail-closed abort.
//
// A marshalling contract violation -- an unrecognized/unconfigured pointer
// size, shadow-arena exhaustion, a failed cross-cage copy, or an invalid or
// exhausted handle -- must never let a foreign-cage pointer, an
// unvalidated field, or partial data reach the handler. There is no
// generic, per-function-safe way to report this back to the calling cage
// (every real function has its own error-return convention), so fail
// closed: trap immediately rather than ever guessing.
// ---------------------------------------------------------------------------

static inline void _lind_marshal_abort(const char *reason) {
    (void)reason;  // for readability at call sites; not logged (no libc
                    // header dependency assumed at this point in the file)
    __builtin_trap();
}

// Wraps copy_data_between_cages() with the fail-closed check every call
// site needs: a failed cross-cage copy must never be treated as if it
// succeeded (stale/partial shadow data reaching the handler, or a silently
// lost copy-back). See threei::copy_data_between_cages' doc: returns
// destaddr on success, ELINDAPIABORTED on failure -- truncated to the C
// `int` ABI this import uses, well above any real wasm32 address in this
// port's linear memory, so a straight equality check is unambiguous.
#define LIND_API_ABORTED ((int)0xE0010001)

static inline void _lind_copy_or_abort(
    uint64_t thiscage, uint64_t targetcage,
    uint64_t srcaddr, uint64_t srccage,
    uint64_t destaddr, uint64_t destcage,
    uint64_t len, uint64_t copytype)
{
    int ret = copy_data_between_cages(thiscage, targetcage, srcaddr, srccage,
                                       destaddr, destcage, len, copytype);
    if (ret == LIND_API_ABORTED) {
        _lind_marshal_abort("copy_data_between_cages failed");
    }
}

// ---------------------------------------------------------------------------
// Shadow pointer provenance (post-call: validating what the interposed
// library wrote or returned)
//
// Every OUT-direction shadow buffer this dispatch call creates is owned by
// it alone; the ONLY legitimate values a callee may leave behind in a
// pointer-typed shadow field, or return through a LIND_RET_PTR_INTO_ARG
// return, are addresses within that specific allocation -- from `base`
// (the interior) up to and including `base + len` (one-past-the-end, valid
// as a pointer VALUE per C semantics even though it can't be dereferenced).
// A buggy or adversarial library returning anything else -- an address
// before base, past one-past-the-end, or belonging to a different shadow
// entirely -- must never be translated and hand back a fabricated or
// out-of-bounds source-cage address; every call site below fails closed via
// _lind_marshal_abort instead.
// ---------------------------------------------------------------------------

// Validates that `candidate` lies within [base, base+len) of a shadow
// allocation -- or, if `allow_one_past` is set, within [base, base+len]
// (see LIND_ARGSPEC_ALLOW_ONE_PAST's doc). Guards the base+len computation
// itself against overflow (a real allocation's bounds can never wrap the
// address space, so an overflow here means `base`/`len` themselves are
// bogus). Returns 1 and sets *out_offset on success; returns 0 without
// touching *out_offset otherwise.
static inline int _lind_validate_shadow_offset(uintptr_t base, size_t len,
                                                uintptr_t candidate,
                                                int allow_one_past,
                                                uint64_t *out_offset)
{
    if (len > (size_t)-1 - base)
        return 0;
    uintptr_t end = base + len;
    if (candidate < base) return 0;
    if (candidate == end) {
        if (!allow_one_past) return 0;
    } else if (candidate > end) {
        return 0;
    }
    *out_offset = (uint64_t)(candidate - base);
    return 1;
}

// Every wasm32 address (this port's only target) fits in 32 bits; both a
// candidate pointer VALUE from the callee and a source-cage address this
// module itself computed must fit before either takes part in pointer
// arithmetic. Skipping this and narrowing straight to uintptr_t (32-bit
// here) would let a fabricated 64-bit candidate with high bits set alias
// into a valid shadow range purely by truncation, and would let a bogus
// source_ptr make an overflow check that subtracts it from UINT32_MAX wrap
// instead of catching it.
static inline void _lind_check_fits_wasm32_addr(uint64_t v, const char *reason) {
    if (v > (uint64_t)UINT32_MAX)
        _lind_marshal_abort(reason);
}

// Every shadow allocation belongs to exactly the (source_cage, grate_cage)
// pair this dispatch call was invoked with -- the arena is reset at the top
// of every lind_marshal_dispatch call (_lind_marshal_reset), so today this
// can only ever fail if a record were somehow read across two different
// dispatch calls. Checked anyway, unconditionally, at every site that
// trusts a shadow/ptr_field_track record: the record itself carries no
// other proof of which call created it, and that stops being a paper
// guarantee the moment any future change relaxes the per-call arena reset
// (e.g. concurrent dispatch, or shadows outliving a single call).
static inline void _lind_check_shadow_owner(uint64_t rec_source_cage,
                                             uint64_t rec_grate_cage,
                                             uint64_t source_cage,
                                             uint64_t grate_cage,
                                             const char *reason)
{
    if (rec_source_cage != source_cage || rec_grate_cage != grate_cage)
        _lind_marshal_abort(reason);
}

// Translates a grate-shadow pointer VALUE the callee wrote or returned into
// its equivalent source-cage address, aborting if it doesn't resolve to a
// valid position within the given shadow allocation. NULL is a legitimate
// value at every call site this is used from (e.g. strtol's endptr when no
// conversion happened, or a "not found" return) and always passes through
// unchanged, bypassing provenance validation entirely -- there is no shadow
// offset to compute for it.
static inline uint64_t _lind_translate_shadow_ptr_or_abort(
    uintptr_t base, size_t len, int allow_one_past, uint64_t source_ptr,
    uint64_t candidate, const char *reason)
{
    if (candidate == 0)
        return 0;
    _lind_check_fits_wasm32_addr(candidate, reason);
    _lind_check_fits_wasm32_addr(source_ptr, reason);
    uint64_t offset;
    if (!_lind_validate_shadow_offset(base, len, (uintptr_t)candidate, allow_one_past, &offset))
        _lind_marshal_abort(reason);
    if (offset > (uint64_t)UINT32_MAX - source_ptr)
        _lind_marshal_abort("translated pointer overflows the source cage's address space");
    return source_ptr + offset;
}

// ---------------------------------------------------------------------------
// Handle table (per-grate, C-owned)
// ---------------------------------------------------------------------------

#define LIND_HANDLE_TABLE_SIZE 64

struct _lind_handle_entry {
    uint64_t app_token;    // opaque index returned to source cage (never 0)
    uint64_t real_object;  // real pointer in handler cage
    uint32_t handle_class;
    uint8_t  in_use;
};

static struct _lind_handle_entry _lind_handle_table[LIND_HANDLE_TABLE_SIZE];
static uint64_t _lind_next_token = 1;

static inline uint64_t lind_register_handle(uint32_t cls, uint64_t real_obj) {
    for (int i = 0; i < LIND_HANDLE_TABLE_SIZE; i++) {
        if (!_lind_handle_table[i].in_use) {
            _lind_handle_table[i].app_token   = _lind_next_token++;
            _lind_handle_table[i].real_object  = real_obj;
            _lind_handle_table[i].handle_class = cls;
            _lind_handle_table[i].in_use       = 1;
            return _lind_handle_table[i].app_token;
        }
    }
    return 0;  // table full
}

// *found distinguishes "translates to a real object of 0" (never happens in
// practice -- handles register real pointers -- but not assumed) from
// "lookup failed" (stale/forged/wrong-class token), so callers that must
// fail closed on a bad token can tell the two apart rather than silently
// treating a failed lookup as if it were a valid NULL.
static inline uint64_t lind_translate_handle_checked(uint32_t cls, uint64_t app_token, int *found) {
    for (int i = 0; i < LIND_HANDLE_TABLE_SIZE; i++) {
        if (_lind_handle_table[i].in_use &&
            _lind_handle_table[i].app_token   == app_token &&
            _lind_handle_table[i].handle_class == cls) {
            *found = 1;
            return _lind_handle_table[i].real_object;
        }
    }
    *found = 0;
    return 0;
}

static inline uint64_t lind_translate_handle(uint32_t cls, uint64_t app_token) {
    int found;
    return lind_translate_handle_checked(cls, app_token, &found);
}

static inline void lind_release_handle(uint32_t cls, uint64_t app_token) {
    for (int i = 0; i < LIND_HANDLE_TABLE_SIZE; i++) {
        if (_lind_handle_table[i].in_use &&
            _lind_handle_table[i].app_token   == app_token &&
            _lind_handle_table[i].handle_class == cls) {
            _lind_handle_table[i].in_use = 0;
            return;
        }
    }
}

// ---------------------------------------------------------------------------
// C-string scan: measures length (including '\0') in source cage, capped.
// ---------------------------------------------------------------------------

static inline size_t _lind_measure_cstr(uint64_t src_ptr,
                                         uint64_t source_cage,
                                         uint64_t grate_cage) {
    char chunk[64];
    size_t total = 0;
    while (total < LIND_MARSHAL_CSTR_CAP) {
        size_t to_copy = sizeof(chunk);
        if (total + to_copy > LIND_MARSHAL_CSTR_CAP)
            to_copy = LIND_MARSHAL_CSTR_CAP - total;
        _lind_copy_or_abort(grate_cage, source_cage,
            src_ptr + (uint64_t)total, source_cage,
            (uint64_t)(uintptr_t)chunk, grate_cage,
            (uint64_t)to_copy, 0);
        for (size_t i = 0; i < to_copy; i++) {
            if (chunk[i] == '\0') return total + i + 1;  // include '\0'
        }
        total += to_copy;
    }
    return LIND_MARSHAL_CSTR_CAP;  // cap reached, no '\0' found
}

// ---------------------------------------------------------------------------
// Shadow tracking (flat buffers and nested structs)
// ---------------------------------------------------------------------------

// Per-pointer-field tracking entry used when marshalling structs.
struct _lind_ptr_field_track {
    uint32_t  offset;           // byte offset of this field within the parent struct
    uint64_t  orig_src_ptr;     // original source-cage ptr stored in this field
    uint8_t  *shadow_start;     // start of the child shadow buffer
    size_t    shadow_len;       // allocated length of the child shadow buffer --
                                 // the only trustworthy bound on how far the
                                 // callee may legitimately advance a pointer
                                 // into it (see _lind_validate_shadow_offset)
    uint64_t  source_cage;      // cages this allocation belongs to -- see
    uint64_t  grate_cage;       // _lind_check_shadow_owner's doc
    const struct lind_arg_spec *spec;  // field spec (for recursive post-call)
};

struct _lind_shadow {
    uint32_t               arg_index;
    uint64_t               source_ptr;
    void                  *shadow_ptr;
    size_t                 size;
    enum lind_ptr_direction direction;
    uint64_t                source_cage;  // cages this allocation belongs to
    uint64_t                grate_cage;   // -- see _lind_check_shadow_owner
    // Nested struct support (NULL layout = flat buffer):
    const struct lind_layout      *layout;
    struct _lind_ptr_field_track  *ptr_fields;
    uint32_t               n_ptr_fields;
};

// ---------------------------------------------------------------------------
// Forward declarations for recursive functions
// ---------------------------------------------------------------------------

static void *_lind_pre_ptr(uint64_t src_ptr, const struct lind_arg_spec *as,
                            uint64_t source_cage, uint64_t grate_cage,
                            const uint64_t *raw_args_or_sibling_shadow,
                            uint32_t nargs,
                            int in_struct_context,
                            struct _lind_ptr_field_track **out_ptr_fields,
                            uint32_t *out_n_ptr_fields);

static void _lind_post_struct(const struct _lind_shadow *s,
                               uint64_t source_cage, uint64_t grate_cage);

static void *_lind_pre_ptr_array(uint64_t src_ptr, const struct lind_arg_spec *elem,
                                  uint64_t source_cage, uint64_t grate_cage);

// The V1 fixed-arity dispatch transport (lind_marshal_dispatch,
// LIND_DEFINE_MARSHAL_HANDLER's `_raw[6]`) carries at most this many raw
// wasm-level argument slots; a spec claiming more than this many top-level
// args can never be dispatched through that path -- see
// lind_marshal_dispatch's own check. It is NOT the bound used to validate a
// size_arg_index/extent arg_index against a specific call's raw_args array:
// those are checked against that call's own actual `nargs` (passed
// explicitly to _lind_eval_extent_operand/_lind_compute_size/_lind_pre_ptr),
// since a V2 (variable-width) caller's raw_args array can legitimately be
// longer than LIND_RAW_ARGS_MAX. V1 and V2 share these exact bound checks
// (see _lind_marshal_prepare_arg/_lind_marshal_finish_shadow/
// _lind_marshal_translate_return below) rather than each maintaining its
// own pointer/handle safety logic.
#define LIND_RAW_ARGS_MAX 6

// Reads raw_args[arg_index] directly (interpreted per `leaf_type`), or an
// i32 loaded through the pointer AT that argument via the checked
// cross-cage copy path (for calling conventions that pass scalars by
// reference, e.g. Fortran's, where a length or stride argument is a
// pointer to the value, not the value itself) -- always sign-extended to
// int64_t for the pointee case (ARG_POINTEE_I32 is always a 4-byte signed
// int pointee; `leaf_type` is not consulted there at all). This is the one
// place that actually touches cross-cage memory for an extent leaf (the
// pointee case's _lind_copy_or_abort call) or needs the real per-call
// `nargs` bounds check; a CONSTANT leaf (in either lind_extent_operand or
// lind_extent_expr) bypasses this function entirely, since it has no
// argument to read. Shared by _lind_eval_extent_operand (always passing
// LIND_EXTENT_LEAF_I32, matching lind_extent_operand's own fixed width)
// and _lind_eval_extent_expr's own leaf cases, so this one cross-cage read
// path has exactly one implementation, not two that could drift apart.
static inline int64_t _lind_read_arg_leaf_i64(
    int is_pointee, uint32_t arg_index, enum lind_extent_leaf_type leaf_type,
    const uint64_t *raw_args, uint32_t nargs,
    uint64_t source_cage, uint64_t grate_cage,
    const char *reason)
{
    if (arg_index >= nargs)
        _lind_marshal_abort(reason);
    uint64_t raw = raw_args[arg_index];
    if (!is_pointee) {
        switch (leaf_type) {
            case LIND_EXTENT_LEAF_I32:
                return (int64_t)(int32_t)(uint32_t)raw;
            case LIND_EXTENT_LEAF_U32:
                return (int64_t)(uint32_t)raw;
            case LIND_EXTENT_LEAF_I64:
                return (int64_t)raw;
            case LIND_EXTENT_LEAF_U64:
                if (raw > (uint64_t)INT64_MAX)
                    _lind_marshal_abort(reason);
                return (int64_t)raw;
            default:
                _lind_marshal_abort(reason);
                return 0; // unreachable (abort traps)
        }
    }

    if (raw == 0)
        _lind_marshal_abort(reason);
    if (raw > (uint64_t)UINT32_MAX)
        _lind_marshal_abort(reason);
    uint32_t val = 0;
    _lind_copy_or_abort(grate_cage, source_cage,
        raw, source_cage,
        (uint64_t)(uintptr_t)&val, grate_cage,
        sizeof(uint32_t), 0);
    return (int64_t)(int32_t)val;
}

// Evaluates one lind_extent_operand: the argument's own value, an i32
// loaded through a pointer argument (see lind_extent_operand's own doc for
// why a by-reference source exists), or a value baked into the spec
// itself with no argument lookup at all. A thin wrapper over
// _lind_read_arg_leaf_i64 for the two argument-sourced cases (always as
// LIND_EXTENT_LEAF_I32, lind_extent_operand's own fixed width) -- narrowing
// its int64_t result back to int32_t here is lossless, since every value
// that function can produce for I32 already fits in int32_t (the wider
// int64_t return, and the other leaf_type choices, exist for
// lind_extent_expr's own benefit -- see that type's own doc). The constant
// case never touches raw_args or that shared function at all, since it has
// no argument to read: checked and range-limited at generation time
// (gen_grate.py), not here.
static inline int32_t _lind_eval_extent_operand(
    const struct lind_extent_operand *op,
    const uint64_t *raw_args, uint32_t nargs,
    uint64_t source_cage, uint64_t grate_cage,
    const char *reason)
{
    if (op->source == LIND_EXTENT_CONSTANT)
        return (int32_t)op->const_value;
    if (op->source != LIND_EXTENT_VALUE && op->source != LIND_EXTENT_POINTEE_I32)
        _lind_marshal_abort(reason);
    return (int32_t)_lind_read_arg_leaf_i64(
        op->source == LIND_EXTENT_POINTEE_I32, op->arg_index, LIND_EXTENT_LEAF_I32,
        raw_args, nargs, source_cage, grate_cage, reason);
}

// ---------------------------------------------------------------------------
// General extent-expression tree evaluation (see struct lind_extent_expr's
// own doc).
// ---------------------------------------------------------------------------

// Records that some operand, somewhere in the tree, was negative --
// shared by PRODUCT/ADD/MAX's operand checks and CEIL_DIVIDE's dividend
// check (see LIND_EXPR_PRODUCT's own doc for why this taints rather than
// aborts, and why a flag threaded through the whole evaluation, not just
// the final value, is what actually catches a double-negative
// cancellation). Returns `v` unchanged either way -- the caller still
// needs it for its own (possibly now-irrelevant, since the result is
// tainted) arithmetic.
static inline int64_t _lind_taint_if_negative(int64_t v, int *tainted) {
    if (v < 0)
        *tainted = 1;
    return v;
}

// Recursive worker: evaluates `e` to a signed int64_t, tracking recursion
// depth AND total node count explicitly (not relying on the C call stack,
// or any bound on depth alone, to limit the work one evaluation can do --
// see LIND_EXTENT_EXPR_MAX_DEPTH/_MAX_NODES's own docs: a tree can be wide
// rather than deep). `*nodes_remaining` is shared across the whole
// evaluation (decremented here, threaded through every recursive call),
// not reset per subtree -- `*tainted` likewise (see LIND_EXPR_PRODUCT's
// own doc on why a negative operand anywhere in the tree must taint the
// WHOLE evaluation, not just the subtree it appears in). Every leaf and
// every operator result is a genuine int64_t value strictly between
// INT64_MIN and INT64_MAX (never exactly INT64_MIN: a leaf is a sign-
// extended/zero-extended value or a const_value already checked <=
// INT64_MAX, and PRODUCT/ADD are checked against overflowing into that
// range), so ABS's plain negation can never itself overflow.
static int64_t _lind_eval_extent_expr_depth(
    const struct lind_extent_expr *e,
    const uint64_t *raw_args, uint32_t nargs,
    uint64_t source_cage, uint64_t grate_cage,
    uint32_t depth, uint32_t *nodes_remaining, int *tainted)
{
    if (e == NULL)
        _lind_marshal_abort("extent expression: null node");
    if (depth >= LIND_EXTENT_EXPR_MAX_DEPTH)
        _lind_marshal_abort("extent expression: exceeds maximum depth");
    if (*nodes_remaining == 0)
        _lind_marshal_abort("extent expression: exceeds maximum node count");
    (*nodes_remaining)--;

    switch (e->kind) {
        case LIND_EXPR_CONSTANT:
            if (e->const_value > (uint64_t)INT64_MAX)
                _lind_marshal_abort("extent expression: constant exceeds representable range");
            return (int64_t)e->const_value;

        case LIND_EXPR_ARG_VALUE:
            return _lind_read_arg_leaf_i64(0, e->arg_index, e->leaf_type, raw_args, nargs,
                source_cage, grate_cage, "extent expression: invalid argument_value index");

        case LIND_EXPR_ARG_POINTEE_I32:
            return _lind_read_arg_leaf_i64(1, e->arg_index, LIND_EXTENT_LEAF_I32, raw_args, nargs,
                source_cage, grate_cage, "extent expression: invalid argument_pointee_i32 index");

        case LIND_EXPR_ABS: {
            int64_t v = _lind_eval_extent_expr_depth(e->lhs, raw_args, nargs,
                source_cage, grate_cage, depth + 1, nodes_remaining, tainted);
            return v < 0 ? -v : v;
        }

        case LIND_EXPR_PRODUCT: {
            int64_t a = _lind_taint_if_negative(_lind_eval_extent_expr_depth(e->lhs, raw_args, nargs,
                source_cage, grate_cage, depth + 1, nodes_remaining, tainted), tainted);
            int64_t b = _lind_taint_if_negative(_lind_eval_extent_expr_depth(e->rhs, raw_args, nargs,
                source_cage, grate_cage, depth + 1, nodes_remaining, tainted), tainted);
            int64_t result;
            if (__builtin_mul_overflow(a, b, &result))
                _lind_marshal_abort("extent expression: product overflow");
            return result;
        }

        case LIND_EXPR_ADD: {
            int64_t a = _lind_taint_if_negative(_lind_eval_extent_expr_depth(e->lhs, raw_args, nargs,
                source_cage, grate_cage, depth + 1, nodes_remaining, tainted), tainted);
            int64_t b = _lind_taint_if_negative(_lind_eval_extent_expr_depth(e->rhs, raw_args, nargs,
                source_cage, grate_cage, depth + 1, nodes_remaining, tainted), tainted);
            int64_t result;
            if (__builtin_add_overflow(a, b, &result))
                _lind_marshal_abort("extent expression: add overflow");
            return result;
        }

        case LIND_EXPR_MAX: {
            int64_t a = _lind_taint_if_negative(_lind_eval_extent_expr_depth(e->lhs, raw_args, nargs,
                source_cage, grate_cage, depth + 1, nodes_remaining, tainted), tainted);
            int64_t b = _lind_taint_if_negative(_lind_eval_extent_expr_depth(e->rhs, raw_args, nargs,
                source_cage, grate_cage, depth + 1, nodes_remaining, tainted), tainted);
            return a > b ? a : b;
        }

        case LIND_EXPR_CEIL_DIVIDE: {
            int64_t a = _lind_taint_if_negative(_lind_eval_extent_expr_depth(e->lhs, raw_args, nargs,
                source_cage, grate_cage, depth + 1, nodes_remaining, tainted), tainted);
            int64_t b = _lind_eval_extent_expr_depth(e->rhs, raw_args, nargs,
                source_cage, grate_cage, depth + 1, nodes_remaining, tainted);
            if (b <= 0)
                _lind_marshal_abort("extent expression: ceil_divide by non-positive divisor");
            if (a < 0)
                return 0;  // tainted already set above; this node's own value is moot.
            // a/b + (a%b != 0), not (a+b-1)/b: the latter can itself
            // overflow when a is near INT64_MAX, for no benefit (both
            // formulas are exact for every valid a>=0, b>0).
            int64_t q = a / b;
            return (a % b != 0) ? q + 1 : q;
        }

        default:
            _lind_marshal_abort("extent expression: unrecognized node kind");
            return 0; // unreachable (abort traps)
    }
}

// Evaluates a general extent-expression tree to a final, checked size_t:
// a tainted tree (see LIND_EXPR_PRODUCT's own doc -- some dimension
// argument feeding the formula was negative, the shape a real BLAS/
// LAPACK-style callee's own XERBLA-style argument validation exists to
// reject, not something this marshaller needs to pre-empt) resolves to
// byte count 0 -- an empty, harmless shadow the real callee will reject
// before ever touching -- same as a direct non-positive final value.
// An UNTAINTED result must still fit the real wasm32 target's size_t
// range (64-bit evaluation throughout can succeed while still being too
// large for a 32-bit size_t -- checked here the same way
// _lind_compute_size's own LIND_SIZE_STRIDE_VECTOR case already does for
// its own final value) -- that remains a hard abort: an untainted
// request this large is a genuine overflow/malformed-spec concern, not
// a deliberately-invalid argument this evaluator can safely absorb.
// Returns the tree's raw evaluated value directly, in whatever unit
// (element count or byte count) the caller's own size_kind assigns to it
// -- the same division of responsibility _lind_eval_extent_operand already
// has relative to _lind_compute_size's LIND_SIZE_STRIDE_VECTOR case.
static inline size_t _lind_eval_extent_expr(
    const struct lind_extent_expr *e,
    const uint64_t *raw_args, uint32_t nargs,
    uint64_t source_cage, uint64_t grate_cage)
{
    uint32_t nodes_remaining = LIND_EXTENT_EXPR_MAX_NODES;
    int tainted = 0;
    int64_t result = _lind_eval_extent_expr_depth(
        e, raw_args, nargs, source_cage, grate_cage, 0, &nodes_remaining, &tainted);
    if (tainted || result < 0)
        return 0;
    if ((uint64_t)result > (uint64_t)(size_t)-1)
        _lind_marshal_abort("extent expression: final extent exceeds size_t range");
    return (size_t)result;
}

// Evaluates a general extent-expression tree to a signed int64_t WITHOUT
// _lind_eval_extent_expr's own final size_t-range check -- for a tree
// that computes one intermediate sub-operand of a larger size
// computation (LIND_SIZE_STRIDE_VECTOR's own size_operand_expr/
// stride_operand_expr below), not a complete byte count in its own
// right. A tainted tree (see LIND_EXPR_PRODUCT's own doc) resolves to -1
// regardless of its raw numeric result, so that a caller's own "<=0
// means empty/invalid" domain check (e.g. LIND_SIZE_STRIDE_VECTOR's own
// count operand, which legitimately treats any non-positive value as an
// empty, zero-size vector) still catches a double-negative cancellation
// inside this sub-expression the same way _lind_eval_extent_expr's own
// final check does for a complete byte count. An UNTAINTED result is
// returned exactly as evaluated, negative or not: the caller applies
// whatever domain check that specific sub-operand actually needs (e.g.
// LIND_SIZE_STRIDE_VECTOR's own stride operand still may not be
// negative at all -- see that call site's own doc).
static inline int64_t _lind_eval_extent_expr_signed(
    const struct lind_extent_expr *e,
    const uint64_t *raw_args, uint32_t nargs,
    uint64_t source_cage, uint64_t grate_cage)
{
    uint32_t nodes_remaining = LIND_EXTENT_EXPR_MAX_NODES;
    int tainted = 0;
    int64_t result = _lind_eval_extent_expr_depth(
        e, raw_args, nargs, source_cage, grate_cage, 0, &nodes_remaining, &tainted);
    return tainted ? -1 : result;
}

// ---------------------------------------------------------------------------
// Compute size for a top-level PTR arg from the raw_args array.
//
// (There is no in-struct variant of this function: a nested field's sibling
// size lives at a *field-table index*, not a raw_args slot -- see the
// LIND_SIZE_FROM_ARG case in _lind_pre_ptr's struct walk below, which is
// the only place nested sibling sizes are actually computed.)
// ---------------------------------------------------------------------------

static inline size_t _lind_compute_size(
    const struct lind_arg_spec *as,
    const uint64_t *raw_args, uint32_t nargs,
    uint64_t source_cage, uint64_t grate_cage)
{
    switch (as->size_kind) {
        case LIND_SIZE_CONST:
            return (size_t)as->const_size;

        case LIND_SIZE_FROM_ARG:
            if (as->size_arg_index >= nargs)
                _lind_marshal_abort("size_arg_index out of range");
            return (size_t)raw_args[as->size_arg_index];

        case LIND_SIZE_FROM_ARG_POINTEE: {
            // Read uint32_t from source cage at the address stored in raw_args[i].
            if (as->size_arg_index >= nargs)
                _lind_marshal_abort("size_arg_index out of range");
            uint32_t size_val = 0;
            _lind_copy_or_abort(grate_cage, source_cage,
                raw_args[as->size_arg_index], source_cage,
                (uint64_t)(uintptr_t)&size_val, grate_cage,
                sizeof(uint32_t), 0);
            return (size_t)size_val;
        }

        case LIND_SIZE_CSTR:
            // Caller must handle CSTR separately (needs src_ptr).
            return 0;

        case LIND_SIZE_STRIDE_VECTOR: {
            // For a non-negative stride, the pointee spans elements at
            // 0, stride, 2*stride, ..., (n-1)*stride from the passed
            // pointer -- byte footprint (1 + (n-1)*stride) * elem_size, not
            // n*elem_size (which only holds for the contiguous stride==1
            // case and silently undersizes every other call, corrupting
            // whichever elements fall between the touched ones).
            //
            // A negative stride walks the vector backwards, which shifts
            // the touched span to BEFORE the passed pointer, not after it
            // -- shadow allocation here, like every other pointer arg,
            // always treats the passed address as the start of the copied
            // region. Handling a negative stride correctly would mean
            // copying from (and translating pointers relative to) an
            // address computed behind the one the callee passed, which no
            // other lind_arg_spec kind does and this one doesn't attempt:
            // fail closed rather than copy the wrong bytes or expose an
            // address outside the real buffer.
            //
            // This is a GENERIC primitive with no knowledge of any
            // particular library's calling convention -- it cannot tell a
            // real backward walk (where the fail-closed rejection below is
            // the only safe answer) from a library whose own wrapper
            // rebases the base pointer forward before doing its own
            // backward walk internally (where the touched region,
            // relative to the ORIGINAL pointer this marshaller sees, is
            // actually the ordinary forward envelope sized by the
            // stride's magnitude -- e.g. real BLAS/LAPACK's Level-1
            // routines). A caller that has actually PROVEN the latter
            // (not merely assumed it) represents that proof explicitly, as
            // an extent-expression tree whose stride operand is wrapped in
            // LIND_EXPR_ABS (stride_operand_expr, not the plain
            // stride_operand below) -- see tools/marshal-infer's own
            // LlmPrompt.cpp for the exact proof obligation ("the caller
            // REBASES the base pointer... so the touched region is
            // exactly this shape") and import_openblas_inference.py's
            // lower_operand_tree for where that proof becomes this tree.
            // By the time a stride reaches this plain-operand path at all,
            // no such proof exists for it, so there is nothing safe to do
            // with a negative value but reject it.
            // A non-NULL *_expr field always takes precedence over the
            // matching plain lind_extent_operand -- see
            // size_operand_expr/stride_operand_expr's own doc on
            // lind_arg_spec. Uses the "signed, no final checks" evaluator:
            // this n/stride value is an intermediate sub-operand of the
            // overall byte count below, not a complete extent in its own
            // right, so the domain checks immediately following (n<=0,
            // stride<0) apply here exactly as they already do for the
            // plain-operand path, not _lind_eval_extent_expr's own
            // (different) final-value checks -- a tree that has already
            // proven a non-negative magnitude (via its own ABS node) never
            // trips the stride<0 check below; one that hasn't is rejected
            // here exactly like an unproven plain operand would be.
            int64_t n = as->size_operand_expr
                ? _lind_eval_extent_expr_signed(as->size_operand_expr, raw_args, nargs,
                                                 source_cage, grate_cage)
                : (int64_t)_lind_eval_extent_operand(
                      &as->size_operand, raw_args, nargs, source_cage, grate_cage,
                      "strided vector: invalid count operand");
            // n<=0 sizes to 0 (nothing touched), not an error.
            if (n <= 0)
                return 0;
            int64_t stride = as->stride_operand_expr
                ? _lind_eval_extent_expr_signed(as->stride_operand_expr, raw_args, nargs,
                                                 source_cage, grate_cage)
                : (int64_t)_lind_eval_extent_operand(
                      &as->stride_operand, raw_args, nargs, source_cage, grate_cage,
                      "strided vector: invalid stride operand");
            if (stride < 0)
                _lind_marshal_abort("strided vector: negative stride not supported");

            uint64_t ustride = (uint64_t)stride;
            uint64_t elem_size = as->const_size;
            uint64_t n_minus_1 = (uint64_t)(n - 1);
            if (ustride != 0 && n_minus_1 > (uint64_t)-1 / ustride)
                _lind_marshal_abort("strided vector size overflow");
            uint64_t span = n_minus_1 * ustride;
            if (span > (uint64_t)-1 - 1)
                _lind_marshal_abort("strided vector size overflow");
            span += 1;
            if (elem_size != 0 && span > (uint64_t)-1 / elem_size)
                _lind_marshal_abort("strided vector size overflow");
            uint64_t total = span * elem_size;
            // The 64-bit computation above can succeed while still being
            // too large for size_t on this port's real target: the grate
            // is wasm32, where size_t is 32 bits, so a value that fits in
            // uint64_t can still silently truncate on the cast below (e.g.
            // 4294967304 truncates to 8) unless checked against the
            // narrower type first.
            if (total > (uint64_t)(size_t)-1)
                _lind_marshal_abort("strided vector size overflow");
            return (size_t)total;
        }

        case LIND_SIZE_EXPR:
            return _lind_eval_extent_expr(as->size_expr, raw_args, nargs, source_cage, grate_cage);

        default:
            return 0;
    }
}

// ---------------------------------------------------------------------------
// Pre-call: marshal one PTR argument (flat or structured).
// Returns the shadow pointer placed in handler_args.
// Stores nested ptr-field tracking in out_ptr_fields/out_n_ptr_fields (arena).
// ---------------------------------------------------------------------------

static void *_lind_pre_ptr(uint64_t src_ptr, const struct lind_arg_spec *as,
                            uint64_t source_cage, uint64_t grate_cage,
                            const uint64_t *raw_or_sibling, uint32_t nargs,
                            int in_struct,
                            struct _lind_ptr_field_track **out_ptr_fields,
                            uint32_t *out_n_ptr_fields)
{
    if (out_ptr_fields) *out_ptr_fields  = NULL;
    if (out_n_ptr_fields) *out_n_ptr_fields = 0;

    if (src_ptr == 0) return NULL;

    // NULL-terminated array of pointers (argv): scan + marshal each element.
    if (as->size_kind == LIND_SIZE_PTR_ARRAY) {
        return _lind_pre_ptr_array(src_ptr, as->element, source_cage, grate_cage);
    }

    // Compute size. A pointer arg's size_kind must be one the marshaller
    // actually knows how to size; anything else means the spec is
    // incomplete or corrupt, with no safe way to know how much to copy --
    // fail closed rather than ever handing the handler a source-cage
    // pointer. A recognized kind computing to a genuine runtime 0 (e.g. an
    // empty buffer) is not an error: it still gets a real, grate-owned
    // shadow below, just with nothing copied into it.
    size_t size;
    switch (as->size_kind) {
        case LIND_SIZE_CSTR:
            size = _lind_measure_cstr(src_ptr, source_cage, grate_cage);
            break;
        case LIND_SIZE_CONST:
        case LIND_SIZE_FROM_ARG:
        case LIND_SIZE_FROM_ARG_POINTEE:
        case LIND_SIZE_STRIDE_VECTOR:
        case LIND_SIZE_EXPR:
            size = _lind_compute_size(as, raw_or_sibling, nargs, source_cage, grate_cage);
            break;
        default:
            _lind_marshal_abort("pointer arg has no computable size");
            return NULL;  // unreachable (abort traps)
    }

    // Determine allocation size: structured types use layout->struct_size.
    size_t alloc_size = (as->layout != NULL) ? as->layout->struct_size : size;
    if (alloc_size == 0) alloc_size = size;

    void *shadow = _lind_marshal_alloc(alloc_size);
    if (!shadow) _lind_marshal_abort("shadow arena exhausted");

    // Copy-in for IN and INOUT (copy the raw bytes first). Skip for a
    // genuinely empty buffer -- nothing to copy, and a 0-length request
    // isn't a copy failure worth aborting over.
    if (alloc_size > 0 &&
        (as->ptr_direction == LIND_PTR_IN || as->ptr_direction == LIND_PTR_INOUT)) {
        _lind_copy_or_abort(grate_cage, source_cage,
            src_ptr, source_cage,
            (uint64_t)(uintptr_t)shadow, grate_cage,
            (uint64_t)alloc_size, 0);
    }

    // If there's a structured layout, walk it recursively.
    if (as->layout != NULL && as->layout->kind == LIND_LO_STRUCT) {
        const struct lind_layout *lo = as->layout;
        uint32_t max_ptr_fields = lo->nfields;
        // nfields comes from the spec, not the calling cage, but an
        // unchecked allocation failure here would silently disable
        // pointer-field tracking -- and with it, OUT/INOUT copy-back for
        // every nested pointer field -- rather than failing the call.
        // Guard the multiplication too: it's a size_t computation on a
        // wasm32 (32-bit size_t) target, so a large-enough nfields could
        // overflow it before _lind_marshal_alloc ever sees the request.
        if (max_ptr_fields > (size_t)-1 / sizeof(struct _lind_ptr_field_track))
            _lind_marshal_abort("pointer-field tracking count overflow");
        struct _lind_ptr_field_track *ptf =
            (struct _lind_ptr_field_track *)_lind_marshal_alloc(
                (size_t)max_ptr_fields * sizeof(struct _lind_ptr_field_track));
        if (!ptf) _lind_marshal_abort("pointer-field tracking arena exhausted");
        uint32_t n = 0;

        for (uint32_t f = 0; f < lo->nfields; f++) {
            const struct lind_field *field = &lo->fields[f];
            if (!field->touched) continue;
            const struct lind_arg_spec *fspec = field->spec;

            // field->offset comes from the spec, not the calling cage, but
            // a misconfigured/corrupt spec must not turn into an
            // out-of-bounds read/write of this struct's own shadow buffer.
            // Every field below is read/written as a uint32_t (a raw
            // pointer, handle token, or scalar slot).
            if (fspec->kind != LIND_ARG_SCALAR &&
                (size_t)field->offset + sizeof(uint32_t) > alloc_size) {
                _lind_marshal_abort("struct field offset out of range");
            }

            if (fspec->kind == LIND_ARG_SCALAR) {
                // Already copied in the raw blit above.
                continue;
            }

            if (fspec->kind == LIND_ARG_HANDLE) {
                // Translate handle value in place. A 0 token is "no handle"
                // (like a NULL pointer) and passes through; a nonzero token
                // that fails to translate is a stale/forged/wrong-class
                // token -- fail closed rather than silently hand the
                // handler a 0 it can't distinguish from a real NULL.
                uint32_t tok = *(uint32_t *)((uint8_t *)shadow + field->offset);
                if (tok != 0) {
                    int found;
                    uint64_t real = lind_translate_handle_checked(fspec->handle_class, (uint64_t)tok, &found);
                    if (!found) _lind_marshal_abort("nested handle field: invalid token");
                    *(uint32_t *)((uint8_t *)shadow + field->offset) = (uint32_t)real;
                }
                continue;
            }

            if (fspec->kind == LIND_ARG_PTR) {
                // Read the source-cage ptr from the shadow (copied from source struct).
                uint32_t child_src_u32 =
                    *(uint32_t *)((uint8_t *)shadow + field->offset);
                uint64_t child_src = (uint64_t)child_src_u32;
                if (child_src == 0) continue;

                // Size uses shadow as "sibling" context. An unrecognized
                // size_kind here is a spec bug -- fail closed rather than
                // leave this field holding the raw source-cage pointer that
                // was copied in by the struct's initial raw blit above.
                size_t child_size;
                switch (fspec->size_kind) {
                    case LIND_SIZE_CSTR:
                        child_size = _lind_measure_cstr(child_src, source_cage, grate_cage);
                        break;
                    case LIND_SIZE_FROM_ARG: {
                        // Sibling field at index = size_arg_index; read uint32 from shadow.
                        // Both the field-table index and the resulting byte
                        // offset come from the spec, not the calling cage,
                        // but a misconfigured/corrupt spec must not turn
                        // into an out-of-bounds read of this struct's own
                        // shadow -- fail closed rather than guess.
                        if (fspec->size_arg_index >= lo->nfields)
                            _lind_marshal_abort("nested size_arg_index out of range");
                        uint32_t sib_off = lo->fields[fspec->size_arg_index].offset;
                        if ((size_t)sib_off + sizeof(uint32_t) > alloc_size)
                            _lind_marshal_abort("nested sibling field offset out of range");
                        child_size = (size_t)(*(uint32_t *)((uint8_t *)shadow + sib_off));
                        break;
                    }
                    case LIND_SIZE_CONST:
                        child_size = (size_t)fspec->const_size;
                        break;
                    case LIND_SIZE_FROM_ARG_POINTEE:
                        // Not supported for nested fields: there is no
                        // raw_args array to index in this context (only
                        // top-level args have one). Fail closed rather
                        // than dereference a NULL/garbage pointer.
                        _lind_marshal_abort("nested pointer field: FROM_ARG_POINTEE unsupported");
                        return NULL;  // unreachable (abort traps)
                    default:
                        _lind_marshal_abort("nested pointer field has no computable size");
                        return NULL;  // unreachable (abort traps)
                }

                void *child_shadow = _lind_marshal_alloc(child_size);
                if (!child_shadow) _lind_marshal_abort("nested shadow arena exhausted");

                if (child_size > 0 &&
                    (fspec->ptr_direction == LIND_PTR_IN ||
                     fspec->ptr_direction == LIND_PTR_INOUT)) {
                    _lind_copy_or_abort(grate_cage, source_cage,
                        child_src, source_cage,
                        (uint64_t)(uintptr_t)child_shadow, grate_cage,
                        (uint64_t)child_size, 0);
                }

                // Overwrite the field in the shadow with the child shadow address.
                *(uint32_t *)((uint8_t *)shadow + field->offset) =
                    (uint32_t)(uintptr_t)child_shadow;

                // Record for post-call fixup.
                if (ptf && n < max_ptr_fields) {
                    ptf[n].offset        = field->offset;
                    ptf[n].orig_src_ptr  = child_src;
                    ptf[n].shadow_start  = (uint8_t *)child_shadow;
                    ptf[n].shadow_len    = child_size;
                    ptf[n].source_cage   = source_cage;
                    ptf[n].grate_cage    = grate_cage;
                    ptf[n].spec          = fspec;
                    n++;
                }
            }
        }

        if (out_ptr_fields)   *out_ptr_fields   = ptf;
        if (out_n_ptr_fields) *out_n_ptr_fields  = n;
    }

    return shadow;
}

// ---------------------------------------------------------------------------
// Pre-call: marshal a NULL-terminated array of pointers (argv-style).
//   src_ptr : source-cage address of the pointer array (p0, p1, ..., NULL)
//   elem    : spec describing each element (typically a cstr pointer)
// Builds a grate-local array of marshalled element shadows, NULL-terminated.
// IN-only (argv is read, not written) — no copy-back.
// ---------------------------------------------------------------------------

#define LIND_PTR_ARRAY_MAX 1024

static void *_lind_pre_ptr_array(uint64_t src_ptr, const struct lind_arg_spec *elem,
                                  uint64_t source_cage, uint64_t grate_cage)
{
    // Scan the source-cage array of 4-byte pointers until a NULL terminator.
    uint32_t elems[LIND_PTR_ARRAY_MAX];
    uint32_t n = 0;
    while (n < LIND_PTR_ARRAY_MAX) {
        uint32_t p = 0;
        _lind_copy_or_abort(grate_cage, source_cage,
            src_ptr + (uint64_t)n * 4, source_cage,
            (uint64_t)(uintptr_t)&p, grate_cage, 4, 0);
        if (p == 0) break;
        elems[n++] = p;
    }

    // Allocate the shadow array: n element pointers + a NULL terminator.
    uint32_t *shadow = (uint32_t *)_lind_marshal_alloc((size_t)(n + 1) * 4);
    if (!shadow) _lind_marshal_abort("pointer-array shadow arena exhausted");

    // Marshal each element per its spec (e.g. each is a cstr pointer -> copy the string).
    for (uint32_t i = 0; i < n; i++) {
        // nargs=0: an array element has no raw_args array of its own to
        // index at all (only top-level args do) -- FROM_ARG/FROM_ARG_POINTEE/
        // STRIDE_VECTOR sizing is unreachable in practice for an element
        // spec (CSTR/CONST are the only kinds that make sense here), and
        // nargs=0 turns an accidental one into a clean abort rather than an
        // out-of-bounds/NULL read of a nonexistent raw_args array.
        void *child = elem
            ? _lind_pre_ptr((uint64_t)elems[i], elem, source_cage, grate_cage,
                            NULL, 0, 0, NULL, NULL)
            : (void *)(uintptr_t)elems[i];
        shadow[i] = (uint32_t)(uintptr_t)child;
    }
    shadow[n] = 0;  // NULL terminator
    return shadow;
}

// ---------------------------------------------------------------------------
// Post-call: copy-back for a nested-struct shadow.
// ---------------------------------------------------------------------------

static void _lind_post_struct(const struct _lind_shadow *s,
                               uint64_t source_cage, uint64_t grate_cage)
{
    if (s->direction != LIND_PTR_OUT && s->direction != LIND_PTR_INOUT)
        return;
    _lind_check_shadow_owner(s->source_cage, s->grate_cage, source_cage, grate_cage,
                              "struct shadow does not belong to this call's cages");

    const struct lind_layout *lo = s->layout;
    uint32_t nptf = s->n_ptr_fields;

    // Phase 1 (validate + compute only -- no writes to the source cage
    // yet): for every tracked pointer field, confirm its shadow ownership
    // and the position the callee left it at, then compute both its
    // copy-back size and its translated source-cage value into scratch
    // memory. A callee that corrupts one field must never be able to leak
    // another field's -- or its own -- raw grate pointer into caller memory
    // before the abort catches it, so nothing is written to the source
    // cage until every field here has validated.
    size_t   *copy_back_size = NULL;
    uint32_t *new_src        = NULL;
    if (nptf > 0) {
        if (nptf > (size_t)-1 / sizeof(size_t) || nptf > (size_t)-1 / sizeof(uint32_t))
            _lind_marshal_abort("pointer-field post-validation count overflow");
        copy_back_size = (size_t *)_lind_marshal_alloc(nptf * sizeof(size_t));
        new_src        = (uint32_t *)_lind_marshal_alloc(nptf * sizeof(uint32_t));
        if (!copy_back_size || !new_src)
            _lind_marshal_abort("post-call field validation arena exhausted");
    }

    for (uint32_t p = 0; p < nptf; p++) {
        const struct _lind_ptr_field_track *ptf = &s->ptr_fields[p];
        _lind_check_shadow_owner(ptf->source_cage, ptf->grate_cage, source_cage, grate_cage,
                                  "struct field shadow does not belong to this call's cages");

        // cur_shadow_u32 is whatever the callee left in this field --
        // entirely untrusted. 0 is a legitimate "no output here" value
        // (e.g. an optional nested out-pointer the library chose not to
        // fill) and passes straight through with no copy-back and no
        // provenance check; anything else must land within this field's
        // own shadow allocation (up to one-past-the-end only if the field's
        // spec opts into LIND_ARGSPEC_ALLOW_ONE_PAST).
        uint32_t cur_shadow_u32 =
            *(uint32_t *)((uint8_t *)s->shadow_ptr + ptf->offset);
        if (cur_shadow_u32 == 0) {
            copy_back_size[p] = 0;
            new_src[p] = 0;
            continue;
        }

        int allow_one_past = (ptf->spec->flags & LIND_ARGSPEC_ALLOW_ONE_PAST) != 0;
        uint64_t adv_offset;
        if (!_lind_validate_shadow_offset((uintptr_t)ptf->shadow_start,
                                           ptf->shadow_len,
                                           (uintptr_t)cur_shadow_u32,
                                           allow_one_past,
                                           &adv_offset))
            _lind_marshal_abort("struct field: OUT pointer left outside its own shadow buffer");

        // How many bytes to copy back: from shadow_start up to wherever the
        // handler left the pointer (may be advanced for INOUT/cursor
        // buffers, e.g. zlib's next_out). Only meaningful for OUT/INOUT
        // fields -- an IN-only field's data was never meant to be written
        // back, though its pointer is still translated below like any
        // other tracked field.
        size_t cbsize = 0;
        if (ptf->spec->ptr_direction == LIND_PTR_OUT ||
            ptf->spec->ptr_direction == LIND_PTR_INOUT) {
            cbsize = (size_t)adv_offset;

            // Unchanged pointer: fall back to the field's nominal size
            // instead of copying back zero bytes. That size may itself
            // come from a sibling field the callee could also have
            // modified during the call (e.g. reporting a bogus "bytes
            // written" count without ever advancing the pointer) -- clamp
            // to the buffer's actual allocated length so a stationary
            // pointer can never trigger an oversized copy either,
            // regardless of what the callee claims.
            if (cbsize == 0 && lo != NULL) {
                const struct lind_field *fld = NULL;
                for (uint32_t f = 0; f < lo->nfields; f++) {
                    if (lo->fields[f].offset == ptf->offset) { fld = &lo->fields[f]; break; }
                }
                if (fld && ptf->spec->size_kind == LIND_SIZE_FROM_ARG) {
                    uint32_t sib_off = lo->fields[ptf->spec->size_arg_index].offset;
                    cbsize = (size_t)(*(uint32_t *)((uint8_t *)s->shadow_ptr + sib_off));
                } else if (ptf->spec->size_kind == LIND_SIZE_CONST) {
                    cbsize = (size_t)ptf->spec->const_size;
                }
                if (cbsize > ptf->shadow_len)
                    cbsize = ptf->shadow_len;
            }
        }
        copy_back_size[p] = cbsize;

        _lind_check_fits_wasm32_addr(ptf->orig_src_ptr,
            "struct field: source pointer overflows the source cage's address space");
        if (adv_offset > (uint64_t)UINT32_MAX - ptf->orig_src_ptr)
            _lind_marshal_abort("struct field: translated pointer overflows the source cage's address space");
        new_src[p] = (uint32_t)(ptf->orig_src_ptr + adv_offset);
    }

    // Phase 2 (still no cage writes): sanitize the struct shadow IN
    // GRATE-LOCAL MEMORY, replacing each tracked pointer field's raw grate
    // address with its already-validated, translated source-cage
    // equivalent. Only this dispatch call's own shadow buffer is touched.
    for (uint32_t p = 0; p < nptf; p++) {
        const struct _lind_ptr_field_track *ptf = &s->ptr_fields[p];
        *(uint32_t *)((uint8_t *)s->shadow_ptr + ptf->offset) = new_src[p];
    }

    // Phase 3: every field has validated and the struct shadow now holds
    // only sanitized pointer values, so it's finally safe to write to the
    // source cage -- each child buffer's data, then the whole struct in a
    // single copy (which also carries the sanitized pointers and any plain
    // scalar fields the handler updated). No raw grate pointer is ever
    // written to caller memory at any point in this function.
    for (uint32_t p = 0; p < nptf; p++) {
        const struct _lind_ptr_field_track *ptf = &s->ptr_fields[p];
        if (copy_back_size[p] > 0) {
            _lind_copy_or_abort(grate_cage, source_cage,
                (uint64_t)(uintptr_t)ptf->shadow_start, grate_cage,
                ptf->orig_src_ptr, source_cage,
                (uint64_t)copy_back_size[p], 0);
        }
    }
    if (s->size > 0) {
        _lind_copy_or_abort(grate_cage, source_cage,
            (uint64_t)(uintptr_t)s->shadow_ptr, grate_cage,
            s->source_ptr, source_cage,
            (uint64_t)s->size, 0);
    }
}

// ---------------------------------------------------------------------------
// Debug-only execution trace (issue #22's OpenBLAS inference-to-runtime
// integration, Gate 5: "strict execution oracle"). A test that merely gets
// the right NUMERIC answer never proves a call actually crossed the grate
// -- a silent fallback to the real, uninterposed library can produce the
// identical result. Building a grate with -DLIND_MARSHAL_DEBUG makes every
// dispatched call (V1's lind_marshal_dispatch and every V2 generated
// adapter alike, both funneling through this one pair of hooks) print a
// line naming the real function, plus one further line per marshalled
// pointer argument naming its selected size_kind and the exact byte count
// _lind_compute_size settled on for it -- a harness can `grep -c` the
// first for a per-symbol call count, or diff the second against a
// baseline run to catch a sizing regression that happens to still produce
// the right numeric answer. Parseable without printf (a static/freestanding
// grate may not link one): plain write(2, ...) and hand-rolled hex/string
// formatting, mirroring every other low-level helper in this file.
//
// _lind_dbg_call/_lind_dbg_ptr_size are declared UNCONDITIONALLY (not
// themselves wrapped in #ifdef at their call sites) so every caller --
// lind_marshal_dispatch, _lind_marshal_prepare_arg, and every V2 generated
// adapter alike -- can call them directly with no conditional-compilation
// noise of its own; only THIS definition differs between a debug and a
// normal build, compiling to a true no-op (dead-code-eliminated) in the
// latter.
#ifdef LIND_MARSHAL_DEBUG
#ifdef LIND_MARSHAL_NO_LIBC_HEADERS
// <unistd.h> isn't included in this mode (see this file's own top-of-file
// doc on LIND_MARSHAL_NO_LIBC_HEADERS) -- hand-declare write() the same
// way every other libc symbol a freestanding grate needs is declared.
extern long write(long, const void *, long);
#endif

static void _lind_dbg_hex(char *b, int *p, uint64_t v) {
    for (int i = 60; i >= 0; i -= 4) {
        int n = (int)((v >> i) & 0xf);
        b[(*p)++] = (char)(n < 10 ? '0' + n : 'a' + n - 10);
    }
}

static const char *_lind_dbg_size_kind_name(enum lind_size_kind sk) {
    switch (sk) {
        case LIND_SIZE_NONE:             return "none";
        case LIND_SIZE_CONST:            return "const";
        case LIND_SIZE_FROM_ARG:         return "from_arg";
        case LIND_SIZE_FROM_ARG_POINTEE: return "from_arg_pointee";
        case LIND_SIZE_CSTR:             return "cstr";
        case LIND_SIZE_PTR_ARRAY:        return "ptr_array";
        case LIND_SIZE_STRIDE_VECTOR:    return "stride_vector";
        case LIND_SIZE_EXPR:             return "expr";
        default:                         return "?";
    }
}

static void _lind_dbg_call(const char *name) {
    char b[160]; int p = 0;
    for (const char *s = "[lind-trace] call "; *s; s++) b[p++] = *s;
    for (const char *s = name; *s && p < 150; s++) b[p++] = *s;
    b[p++] = '\n';
    write(2, b, p);
}

static void _lind_dbg_ptr_size(const char *name, enum lind_size_kind sk, uint64_t bytes) {
    char b[200]; int p = 0;
    for (const char *s = "[lind-trace] "; *s; s++) b[p++] = *s;
    for (const char *s = name; *s && p < 100; s++) b[p++] = *s;
    for (const char *s = " ptr size_kind="; *s; s++) b[p++] = *s;
    for (const char *s = _lind_dbg_size_kind_name(sk); *s; s++) b[p++] = *s;
    for (const char *s = " bytes=0x"; *s; s++) b[p++] = *s;
    _lind_dbg_hex(b, &p, bytes);
    b[p++] = '\n';
    write(2, b, p);
}
#else
static inline void _lind_dbg_call(const char *name) { (void)name; }
static inline void _lind_dbg_ptr_size(const char *name, enum lind_size_kind sk, uint64_t bytes) {
    (void)name; (void)sk; (void)bytes;
}
#endif

// ---------------------------------------------------------------------------
// Shared per-call marshalling primitives.
//
// Each function below handles exactly one argument or one shadow at a time,
// parameterized by the real argument count (nargs) rather than any fixed
// slot width. V1's fixed six-slot lind_marshal_dispatch (below) and a V2
// generated adapter's own unrolled prepare/invoke/finish sequence both call
// these same functions, so a correctness fix to pointer/handle/copy-back
// safety logic applies to both transports at once instead of needing to be
// made -- and kept in sync -- twice.
// ---------------------------------------------------------------------------

// Prepares one argument for the real call and returns the value to pass it:
// a LIND_ARG_SCALAR's raw value unchanged; a LIND_ARG_HANDLE's real pointer
// (0 passes through as "no handle"; a nonzero token that fails to translate
// is fail-closed); or, for LIND_ARG_PTR, the shadow address after validating
// and copying via _lind_pre_ptr. A shadow entry is appended (bumping
// *nshadows) only when a real shadow copy was made -- a NULL source pointer
// passes through with no entry, matching every existing caller.
static inline uint64_t _lind_marshal_prepare_arg(
    uint32_t arg_index,
    const struct lind_arg_spec *as,
    const uint64_t *raw_args, uint32_t nargs,
    uint64_t source_cage, uint64_t grate_cage,
    struct _lind_shadow *shadows, uint32_t *nshadows,
    const char *dbg_name)
{
    uint64_t raw = raw_args[arg_index];

    switch (as->kind) {
        case LIND_ARG_SCALAR:
            return raw;

        case LIND_ARG_HANDLE:
            if (raw == 0) return 0;
            {
                int found;
                uint64_t translated =
                    lind_translate_handle_checked(as->handle_class, raw, &found);
                if (!found) _lind_marshal_abort("handle arg: invalid token");
                return translated;
            }

        case LIND_ARG_PTR: {
            if (raw == 0) return 0;

            struct _lind_ptr_field_track *ptf = NULL;
            uint32_t n_ptf = 0;
            void *shadow = _lind_pre_ptr(raw, as, source_cage, grate_cage,
                                          raw_args, nargs, 0, &ptf, &n_ptf);

            size_t shadow_size = (as->layout != NULL)
                ? as->layout->struct_size
                : _lind_compute_size(as, raw_args, nargs, source_cage, grate_cage);
            if (as->size_kind == LIND_SIZE_CSTR && shadow_size == 0)
                shadow_size = _lind_measure_cstr(raw, source_cage, grate_cage);
            _lind_dbg_ptr_size(dbg_name, as->size_kind, (uint64_t)shadow_size);

            if (shadow != (void *)(uintptr_t)raw) {
                shadows[*nshadows].arg_index    = arg_index;
                shadows[*nshadows].source_ptr   = raw;
                shadows[*nshadows].shadow_ptr   = shadow;
                shadows[*nshadows].size         = shadow_size;
                shadows[*nshadows].direction    = as->ptr_direction;
                shadows[*nshadows].source_cage  = source_cage;
                shadows[*nshadows].grate_cage   = grate_cage;
                shadows[*nshadows].layout       = as->layout;
                shadows[*nshadows].ptr_fields   = ptf;
                shadows[*nshadows].n_ptr_fields = n_ptf;
                (*nshadows)++;
            }
            return (uint64_t)(uintptr_t)shadow;
        }
    }
    _lind_marshal_abort("prepare_arg: unknown arg kind");
    return 0; // unreachable (abort traps)
}

// Finishes one shadow after the real call: copies OUT/INOUT results back to
// the source cage -- a flat buffer, a nested struct (_lind_post_struct), or
// an OUT pointer-to-pointer that aliases another argument (strtol's char**
// endptr; see lind_arg_spec.out_ptr_into_arg1's doc). `spec_args` is the
// full per-call argument spec array (to look up the aliased argument's own
// spec) and `shadows`/`nshadows` the full shadow set for this call (to find
// the aliased argument's own shadow).
static inline void _lind_marshal_finish_shadow(
    uint32_t shadow_index,
    const struct lind_arg_spec *spec_args,
    const struct _lind_shadow *shadows, uint32_t nshadows,
    uint64_t source_cage, uint64_t grate_cage)
{
    const struct _lind_shadow *s = &shadows[shadow_index];
    const struct lind_arg_spec *sas = &spec_args[s->arg_index];

    // `inner` is entirely callee-controlled -- never expose it, or an
    // address derived from it, to the source cage without confirming it's a
    // valid position within the aliased argument's own shadow allocation;
    // fail closed otherwise (an out-of-bounds value here is either a
    // library bug or a deliberate attempt to leak a grate-process address
    // to the source cage).
    if (sas->out_ptr_into_arg1 != 0) {
        uint32_t target = sas->out_ptr_into_arg1 - 1;
        uint32_t inner = *(uint32_t *)s->shadow_ptr;  // what the callee wrote
        uint32_t translated = 0;                      // default: NULL
        if (inner != 0) {
            const struct _lind_shadow *tshadow = NULL;
            for (uint32_t t = 0; t < nshadows; t++) {
                if (shadows[t].arg_index == target) { tshadow = &shadows[t]; break; }
            }
            if (!tshadow)
                _lind_marshal_abort("OUT ptr-to-ptr: aliased argument has no shadow");
            _lind_check_shadow_owner(tshadow->source_cage, tshadow->grate_cage,
                                      source_cage, grate_cage,
                                      "OUT ptr-to-ptr: aliased shadow does not belong to this call's cages");
            translated = (uint32_t)_lind_translate_shadow_ptr_or_abort(
                (uintptr_t)tshadow->shadow_ptr, tshadow->size,
                (sas->flags & LIND_ARGSPEC_ALLOW_ONE_PAST) != 0,
                tshadow->source_ptr, (uint64_t)inner,
                "OUT ptr-to-ptr: value outside the aliased argument's shadow buffer");
        }
        _lind_copy_or_abort(grate_cage, source_cage,
            (uint64_t)(uintptr_t)&translated, grate_cage,
            s->source_ptr, source_cage, 4, 0);
        return;
    }

    if (s->layout != NULL) {
        _lind_post_struct(s, source_cage, grate_cage);
    } else if (s->size > 0 &&
               (s->direction == LIND_PTR_OUT || s->direction == LIND_PTR_INOUT)) {
        _lind_copy_or_abort(grate_cage, source_cage,
            (uint64_t)(uintptr_t)s->shadow_ptr, grate_cage,
            s->source_ptr, source_cage,
            (uint64_t)s->size, 0);
    }
}

// Translates the real call's return value per `ret`. `raw_args`/`nargs` are
// needed for LIND_RET_PTR_ALIAS_ARG (the original source-cage pointer of
// arg[alias_arg_index]); `shadows`/`nshadows` for LIND_RET_PTR_INTO_ARG
// (finding that argument's own shadow to translate a callee-returned
// pointer into it).
static inline uint64_t _lind_marshal_translate_return(
    const struct lind_return_spec *ret,
    const uint64_t *raw_args, uint32_t nargs,
    const struct _lind_shadow *shadows, uint32_t nshadows,
    uint64_t handler_ret,
    uint64_t source_cage, uint64_t grate_cage)
{
    switch (ret->kind) {
        case LIND_RET_VOID:
            return 0;

        case LIND_RET_PTR_ALIAS_ARG:
            // alias_arg_index comes from the spec, not the calling cage, but
            // a misconfigured/corrupt spec must not turn into an
            // out-of-bounds read of raw_args -- fail closed like every
            // other spec-supplied index in this file.
            if (ret->alias_arg_index >= nargs)
                _lind_marshal_abort("alias_arg_index out of range");
            return raw_args[ret->alias_arg_index];

        case LIND_RET_PTR_INTO_ARG: {
            // handler_ret is a pointer into a shadow buffer -- entirely
            // callee-controlled. Translate it to the source cage's
            // equivalent address only once confirmed to lie within the
            // aliased argument's own shadow allocation; never fall back to
            // exposing the raw handler_ret (a grate-process address) to the
            // source cage.
            uint32_t idx = ret->alias_arg_index;
            if (handler_ret == 0)
                return 0;  // NULL return (not found)
            const struct _lind_shadow *rshadow = NULL;
            for (uint32_t s = 0; s < nshadows; s++) {
                if (shadows[s].arg_index == idx) { rshadow = &shadows[s]; break; }
            }
            if (!rshadow)
                _lind_marshal_abort("pointer-into-arg return: aliased argument has no shadow");
            _lind_check_shadow_owner(rshadow->source_cage, rshadow->grate_cage,
                                      source_cage, grate_cage,
                                      "pointer-into-arg return: aliased shadow does not belong to this call's cages");
            return _lind_translate_shadow_ptr_or_abort(
                (uintptr_t)rshadow->shadow_ptr, rshadow->size,
                (ret->flags & LIND_ARGSPEC_ALLOW_ONE_PAST) != 0,
                rshadow->source_ptr, handler_ret,
                "pointer-into-arg return: value outside the aliased argument's shadow buffer");
        }

        case LIND_RET_HANDLE: {
            // 0 means the handle table is full -- app_token is documented
            // as never 0, so returning 0 to the source cage here would be
            // indistinguishable from a real token. Fail closed instead.
            uint64_t token = lind_register_handle(ret->handle_class, handler_ret);
            if (token == 0) _lind_marshal_abort("handle table exhausted");
            return token;
        }

        case LIND_RET_FORCE_LOCAL:
        case LIND_RET_SCALAR:
        default:
            return handler_ret;
    }
}

// ---------------------------------------------------------------------------
// V2 float/double <-> uint64_t bit reinterpretation.
//
// V1's single generic dispatcher calls every real function through one
// blindly-cast lind_handler6_t pointer, relying on --fpcast-emu to patch the
// resulting ABI mismatch at the binary level (see FuncCastEmulation) --
// including for a float/double-returning function, whose bits simply land
// in the right place because of that binary-level trick, not because of any
// C-level cast. A V2 generated adapter instead makes a real, correctly
// prototyped C call to the real function, so there is no such trick to rely
// on: a float/double value crossing into/out of the shared marshalling
// primitives' uniform uint64_t needs an explicit, ordinary bit
// reinterpretation instead. A plain C cast (`(uint64_t)some_double`) would
// be wrong here -- it performs a NUMERIC conversion, not a bit
// reinterpretation (3.0 would become 3, not the double's actual bit
// pattern) -- exactly the kind of corruption this file's arithmetic checks
// elsewhere exist to prevent.
// ---------------------------------------------------------------------------

// Unions, not memcpy: this header must stay includable without <string.h>
// (see LIND_MARSHAL_NO_LIBC_HEADERS for freestanding grates).
static inline uint64_t _lind_v2_bits_from_f64(double v) {
    union { double d; uint64_t u; } c;
    c.d = v;
    return c.u;
}

static inline uint64_t _lind_v2_bits_from_f32(float v) {
    union { float f; uint32_t u; } c;
    c.f = v;
    return (uint64_t)c.u;
}

static inline double _lind_v2_f64_from_bits(uint64_t bits) {
    union { double d; uint64_t u; } c;
    c.u = bits;
    return c.d;
}

static inline float _lind_v2_f32_from_bits(uint64_t bits) {
    union { float f; uint32_t u; } c;
    c.u = (uint32_t)bits;
    return c.f;
}

// ---------------------------------------------------------------------------
// Core dispatch
// ---------------------------------------------------------------------------

static inline uint64_t lind_marshal_dispatch(
    void                           *typed_handler,
    const struct lind_marshal_spec *spec,
    uint64_t                        source_cage,
    uint64_t                        grate_cage,
    uint64_t                       *raw_args,
    uint32_t                        nargs,
    const char                     *_dbg_name)
{
    // raw_args and the handler cast below are both fixed at LIND_RAW_ARGS_MAX
    // slots (the pass_fptr_to_wt/register_lib_handler transport width); a
    // spec with more args than that would read raw_args out of bounds and
    // silently drop everything past slot 6 into the handler call.
    if (spec->nargs > LIND_RAW_ARGS_MAX)
        _lind_marshal_abort("marshal spec exceeds raw ABI slot capacity");

    _lind_dbg_call(_dbg_name);
    _lind_marshal_reset();
    _lind_marshal_source_cage = source_cage;
    _lind_marshal_grate_cage  = grate_cage;

    uint64_t handler_args[16] = {0};
    struct _lind_shadow shadows[16];
    uint32_t nshadows = 0;

    // --- Pre-call ---
    uint32_t effective_nargs = nargs < spec->nargs ? nargs : spec->nargs;
    for (uint32_t i = 0; i < effective_nargs; i++) {
        handler_args[i] = _lind_marshal_prepare_arg(
            i, &spec->args[i], raw_args, nargs, source_cage, grate_cage,
            shadows, &nshadows, _dbg_name);
    }

    // --- Handler ---
    uint64_t handler_ret = ((lind_handler6_t)typed_handler)(
        handler_args[0], handler_args[1], handler_args[2],
        handler_args[3], handler_args[4], handler_args[5]);

    // --- Post-call ---
    for (uint32_t s = 0; s < nshadows; s++) {
        _lind_marshal_finish_shadow(s, spec->args, shadows, nshadows,
                                     source_cage, grate_cage);
    }

    // --- Return translation ---
    uint64_t result = _lind_marshal_translate_return(
        &spec->ret, raw_args, nargs, shadows, nshadows, handler_ret,
        source_cage, grate_cage);

    _lind_marshal_reset();
    return result;
}

// ---------------------------------------------------------------------------
// Macro: generate raw handler wrapper for register_lib_handler.
// Defines: int64_t lind_mh_##name(uint64_t cageid, u64 a1, u64 a1c, ...)
// Source cage inferred from first non-zero argNcage.
//
// Returns the full 64-bit lind_marshal_dispatch() result (not truncated to
// int) so 64-bit scalar returns (double, int64_t, pointers) survive the
// round trip through the wasm-level call/host dispatch/wasm-level return.
// ---------------------------------------------------------------------------

#define LIND_DEFINE_MARSHAL_HANDLER(name, spec_ptr, typed_fn)                  \
static int64_t lind_mh_##name(                                                  \
    uint64_t _cageid,                                                           \
    uint64_t _a1, uint64_t _a1c,                                                \
    uint64_t _a2, uint64_t _a2c,                                                \
    uint64_t _a3, uint64_t _a3c,                                                \
    uint64_t _a4, uint64_t _a4c,                                                \
    uint64_t _a5, uint64_t _a5c,                                                \
    uint64_t _a6, uint64_t _a6c)                                                \
{                                                                               \
    uint64_t _raw[6]   = { _a1, _a2, _a3, _a4, _a5, _a6 };                    \
    uint64_t _cages[6] = { _a1c, _a2c, _a3c, _a4c, _a5c, _a6c };              \
    uint64_t _src_cage = 0;                                                     \
    for (int _i = 0; _i < 6 && _src_cage == 0; _i++)                           \
        _src_cage = _cages[_i];                                                 \
    return (int64_t)lind_marshal_dispatch(                                      \
        (void *)(uintptr_t)(typed_fn),                                          \
        (spec_ptr), _src_cage, _cageid, _raw,                                   \
        (spec_ptr)->nargs, #name);                                             \
}
