// lind_marshal.h — Stage-1 automated argument marshalling for Lind grates.
//
// Include this header in a grate that wants automatic copy-in/copy-out for
// simple pointer arguments.  The grate registers a raw handler function
// generated by LIND_DEFINE_MARSHAL_HANDLER, which invokes lind_marshal_dispatch
// to do pre-call shadow-copy-in and post-call copy-out automatically.
//
// Supported argument categories (Stage 1):
//   LIND_ARG_SCALAR  — passed directly; no memory copy
//   LIND_ARG_PTR     — shadow memory allocated; copy-in/copy-out per direction
//                      NULL pointer: passed through as NULL, no alloc/copy
//
// Supported return categories:
//   LIND_RET_VOID          — return 0
//   LIND_RET_SCALAR        — return handler's return value directly
//   LIND_RET_PTR_ALIAS_ARG — return original source-cage pointer of arg[i]
//
// Handler signature requirement:
//   Due to WASM's strict indirect-call type checking, all handlers MUST have
//   the uniform signature:
//     uint64_t handler_foo(uint64_t a0, uint64_t a1, uint64_t a2,
//                          uint64_t a3, uint64_t a4, uint64_t a5);
//   Use the LIND_AS_PTR / LIND_AS_SIZE / LIND_AS_INT / LIND_RET_PTR /
//   LIND_RET_INT helper macros to reduce casting boilerplate.
//   The handler receives shadow pointers valid in grate-local memory and can
//   call standard C functions (memcpy, strncpy, ...) directly — no manual
//   copy_data_between_cages required.
//
// Usage:
//   #include "lind_marshal.h"
//
//   static struct lind_marshal_spec memcpy_spec = { ... };
//
//   static uint64_t handler_memcpy(uint64_t dest, uint64_t src, uint64_t n,
//                                  uint64_t, uint64_t, uint64_t) {
//       return LIND_RET_PTR(memcpy(LIND_AS_PTR(dest), LIND_AS_PTR(src),
//                                  LIND_AS_SIZE(n)));
//   }
//   LIND_DEFINE_MARSHAL_HANDLER(memcpy, &memcpy_spec, handler_memcpy)
//   // defines: lind_mh_memcpy — the raw handler to pass to register_lib_handler

#pragma once

#include <lind_syscall.h>
#include <stdint.h>
#include <stddef.h>
#include <string.h>

// ---------------------------------------------------------------------------
// Handler argument / return helpers
// (use these inside a handler to avoid explicit cast boilerplate)
// ---------------------------------------------------------------------------

#define LIND_AS_PTR(u)    ((void *)(uintptr_t)(u))
#define LIND_AS_CPTR(u)   ((const void *)(uintptr_t)(u))
#define LIND_AS_STR(u)    ((char *)(uintptr_t)(u))
#define LIND_AS_CSTR(u)   ((const char *)(uintptr_t)(u))
#define LIND_AS_SIZE(u)   ((size_t)(u))
#define LIND_AS_INT(u)    ((int)(u))
#define LIND_AS_UINT(u)   ((unsigned int)(u))
#define LIND_AS_LONG(u)   ((long)(u))
#define LIND_AS_ULONG(u)  ((unsigned long)(u))

#define LIND_RET_PTR(p)   ((uint64_t)(uintptr_t)(p))
#define LIND_RET_INT(v)   ((uint64_t)(uint32_t)(int)(v))
#define LIND_RET_LONG(v)  ((uint64_t)(long)(v))
#define LIND_RET_ULONG(v) ((uint64_t)(unsigned long)(v))

// Uniform handler function type — all handlers passed to lind_marshal_dispatch
// must match this signature.
typedef uint64_t (*lind_handler6_t)(uint64_t, uint64_t, uint64_t,
                                    uint64_t, uint64_t, uint64_t);

// ---------------------------------------------------------------------------
// Metadata types
// ---------------------------------------------------------------------------

enum lind_arg_kind {
    LIND_ARG_SCALAR = 0,
    LIND_ARG_PTR    = 1,
};

enum lind_ptr_direction {
    LIND_PTR_IN    = 0,
    LIND_PTR_OUT   = 1,
    LIND_PTR_INOUT = 2,
};

enum lind_size_kind {
    LIND_SIZE_NONE      = 0,  // pointer has no meaningful size (unused in stage 1)
    LIND_SIZE_CONST     = 1,  // size is const_size bytes
    LIND_SIZE_FROM_ARG  = 2,  // size is the scalar value of raw_args[size_arg_index]
};

enum lind_return_kind {
    LIND_RET_VOID          = 0,
    LIND_RET_SCALAR        = 1,
    LIND_RET_PTR_ALIAS_ARG = 2,  // return original source-cage pointer of arg[alias_arg_index]
};

struct lind_arg_spec {
    enum lind_arg_kind      kind;
    enum lind_ptr_direction ptr_direction;
    enum lind_size_kind     size_kind;
    uint64_t                const_size;
    uint32_t                size_arg_index;
    uint32_t                flags;
};

struct lind_return_spec {
    enum lind_return_kind kind;
    uint32_t              alias_arg_index;  // used when kind == LIND_RET_PTR_ALIAS_ARG
};

struct lind_marshal_spec {
    uint32_t              nargs;
    struct lind_arg_spec  args[16];
    struct lind_return_spec ret;
};

// ---------------------------------------------------------------------------
// Current-call cage ID accessors
//
// LIND_SOURCE_CAGE() — cage ID of the application cage that made the call
// LIND_GRATE_CAGE()  — cage ID of this grate (the handler's cage)
//
// Valid only while inside a lind_marshal_dispatch handler invocation.
// Use these when a handler still needs a manual copy_data_between_cages call
// (e.g. writing into a nested pointer that Stage 1 does not automatically chase).
// ---------------------------------------------------------------------------

static uint64_t _lind_marshal_source_cage = 0;
static uint64_t _lind_marshal_grate_cage  = 0;

#define LIND_SOURCE_CAGE() (_lind_marshal_source_cage)
#define LIND_GRATE_CAGE()  (_lind_marshal_grate_cage)

// ---------------------------------------------------------------------------
// Shadow memory bump allocator (per-grate static arena, reset after each call)
// ---------------------------------------------------------------------------

#define LIND_MARSHAL_ARENA_SIZE (64 * 1024)

static char   _lind_marshal_arena[LIND_MARSHAL_ARENA_SIZE];
static size_t _lind_marshal_arena_used = 0;

static inline void *_lind_marshal_alloc(size_t size) {
    // 8-byte alignment
    size_t aligned = (size + 7u) & ~7u;
    if (_lind_marshal_arena_used + aligned > LIND_MARSHAL_ARENA_SIZE)
        return NULL;
    void *ptr = _lind_marshal_arena + _lind_marshal_arena_used;
    _lind_marshal_arena_used += aligned;
    return ptr;
}

static inline void _lind_marshal_reset(void) {
    _lind_marshal_arena_used = 0;
}

// ---------------------------------------------------------------------------
// Shadow tracking
// ---------------------------------------------------------------------------

struct _lind_shadow {
    uint32_t              arg_index;
    uint64_t              source_ptr;   // original WASM vaddr in source cage
    void                 *shadow_ptr;   // local pointer in grate memory
    size_t                size;
    enum lind_ptr_direction direction;
};

// ---------------------------------------------------------------------------
// Core dispatch function
//
//   typed_handler : the typed C handler function pointer (cast to void*)
//   spec          : marshalling spec
//   source_cage   : cage ID of the calling cage
//   grate_cage    : cage ID of this grate
//   raw_args      : raw uint64_t arguments as received from pass_fptr_to_wt
//   nargs         : number of valid entries in raw_args (≤ 16)
//
// Returns the uint64_t result to hand back to the portal.
// ---------------------------------------------------------------------------

static inline uint64_t lind_marshal_dispatch(
    void                        *typed_handler,
    const struct lind_marshal_spec *spec,
    uint64_t                     source_cage,
    uint64_t                     grate_cage,
    uint64_t                    *raw_args,
    uint32_t                     nargs)
{
    _lind_marshal_reset();
    _lind_marshal_source_cage = source_cage;
    _lind_marshal_grate_cage  = grate_cage;

    uint64_t handler_args[16] = {0};
    struct _lind_shadow shadows[16];
    uint32_t nshadows = 0;

    // --- Pre-call phase: classify args, allocate shadows, copy-in ---
    for (uint32_t i = 0; i < nargs && i < spec->nargs; i++) {
        const struct lind_arg_spec *as = &spec->args[i];

        if (as->kind == LIND_ARG_SCALAR) {
            handler_args[i] = raw_args[i];
            continue;
        }

        // Pointer argument
        uint64_t src_ptr = raw_args[i];

        // NULL: pass through without allocation
        if (src_ptr == 0) {
            handler_args[i] = 0;
            continue;
        }

        // Compute size
        size_t size = 0;
        switch (as->size_kind) {
            case LIND_SIZE_CONST:
                size = (size_t)as->const_size;
                break;
            case LIND_SIZE_FROM_ARG:
                size = (size_t)raw_args[as->size_arg_index];
                break;
            default:
                // No size: treat as opaque scalar (pass value through)
                handler_args[i] = src_ptr;
                continue;
        }

        // Allocate shadow buffer
        void *shadow = _lind_marshal_alloc(size);
        if (!shadow) {
            // Arena exhausted — pass raw pointer through as fallback
            handler_args[i] = src_ptr;
            continue;
        }

        // Copy-in for IN and INOUT
        if (as->ptr_direction == LIND_PTR_IN || as->ptr_direction == LIND_PTR_INOUT) {
            copy_data_between_cages(
                grate_cage, source_cage,
                src_ptr,    source_cage,
                (uint64_t)(uintptr_t)shadow, grate_cage,
                (uint64_t)size, 0);
        }

        handler_args[i] = (uint64_t)(uintptr_t)shadow;

        shadows[nshadows].arg_index  = i;
        shadows[nshadows].source_ptr = src_ptr;
        shadows[nshadows].shadow_ptr = shadow;
        shadows[nshadows].size       = size;
        shadows[nshadows].direction  = as->ptr_direction;
        nshadows++;
    }

    // --- Handler invocation ---
    // typed_handler must be a lind_handler6_t (uint64_t × 6 → uint64_t).
    uint64_t handler_ret = ((lind_handler6_t)typed_handler)(
        handler_args[0], handler_args[1], handler_args[2],
        handler_args[3], handler_args[4], handler_args[5]);

    // --- Post-call phase: copy-out, translate return ---
    for (uint32_t s = 0; s < nshadows; s++) {
        if (shadows[s].direction == LIND_PTR_OUT ||
            shadows[s].direction == LIND_PTR_INOUT) {
            copy_data_between_cages(
                grate_cage, source_cage,
                (uint64_t)(uintptr_t)shadows[s].shadow_ptr, grate_cage,
                shadows[s].source_ptr, source_cage,
                (uint64_t)shadows[s].size, 0);
        }
    }

    uint64_t result;
    switch (spec->ret.kind) {
        case LIND_RET_VOID:
            result = 0;
            break;
        case LIND_RET_PTR_ALIAS_ARG:
            result = raw_args[spec->ret.alias_arg_index];
            break;
        case LIND_RET_SCALAR:
        default:
            result = handler_ret;
            break;
    }

    _lind_marshal_reset();
    return result;
}

// ---------------------------------------------------------------------------
// Macro: generate a raw handler wrapper suitable for register_lib_handler.
//
// Usage:
//   LIND_DEFINE_MARSHAL_HANDLER(name, spec_ptr, typed_fn)
//
// Defines:
//   int lind_mh_##name(uint64_t cageid, u64 a1, u64 a1c, ..., u64 a6, u64 a6c)
//
// Source cage is inferred from the first non-zero argNcage value.
// ---------------------------------------------------------------------------

#define LIND_DEFINE_MARSHAL_HANDLER(name, spec_ptr, typed_fn)                 \
static int lind_mh_##name(                                                     \
    uint64_t _cageid,                                                          \
    uint64_t _a1, uint64_t _a1c,                                               \
    uint64_t _a2, uint64_t _a2c,                                               \
    uint64_t _a3, uint64_t _a3c,                                               \
    uint64_t _a4, uint64_t _a4c,                                               \
    uint64_t _a5, uint64_t _a5c,                                               \
    uint64_t _a6, uint64_t _a6c)                                               \
{                                                                              \
    uint64_t _raw[6] = { _a1, _a2, _a3, _a4, _a5, _a6 };                     \
    uint64_t _cages[6] = { _a1c, _a2c, _a3c, _a4c, _a5c, _a6c };             \
    uint64_t _src_cage = 0;                                                    \
    for (int _i = 0; _i < 6 && _src_cage == 0; _i++)                          \
        _src_cage = _cages[_i];                                                \
    return (int)lind_marshal_dispatch(                                         \
        (void *)(uintptr_t)(typed_fn),                                         \
        (spec_ptr), _src_cage, _cageid, _raw,                                  \
        (spec_ptr)->nargs);                                                    \
}
