// @generated by tools/gen_stubs.sh from functions.txt — do not edit by hand.
// Regenerate with `make gen`.
//
// Native shared library whose exported symbols run their real implementations
// inside the lind/wasmtime sandbox. A native app links this like any other .so
// and calls the symbols with no knowledge that the work happens in a wasm guest.
// On the first call the lind runtime is brought up and the guest module is
// instantiated as a long-lived sandboxed library; later calls reuse it.

use std::sync::{Mutex, OnceLock};

use core::ffi::{CStr, c_char};

use lind_boot::{Arg, CliOptions, SandboxedLib, init_sandboxed_lib};

// Why the guest is initialized lazily (on the first call) rather than in a
// load-time constructor (C `__attribute__((constructor))` / Rust `#[ctor]`, which
// place a function in `.init_array` for the loader to run at dlopen/startup).
// `init_sandboxed_lib` is heavyweight — it brings up the whole lind runtime
// (RawPOSIX, the 3i trampoline + syscall handlers, the wasmtime engine, grate
// worker threads, a SIGUSR2 handler) and instantiates the guest. A constructor is
// the wrong place for that:
//
//   1. No error handling. A constructor returns void and runs before the app's
//      `main`. If init fails, the only option is to abort the whole process before
//      it starts — you cannot return an error the app can handle. Lazy init lets
//      the first call report failure normally.
//   2. Threads at load time. Init spawns threads (grate workers). Creating threads
//      from a constructor is hazardous: e.g. if the app later `fork()`s, only the
//      calling thread survives in the child, leaving the others' locks/state
//      broken. Many runtimes forbid pre-`main` thread creation.
//   3. Signal handlers at load time. Init installs a SIGUSR2 handler; doing that
//      during load can clobber the host app's signal setup before it is ready.
//   4. Ordering / dlopen lock. Constructors run while the dynamic loader holds its
//      internal lock and while other libraries' constructors and the language
//      runtime may not be fully up. Heavy init here (tokio, RawPOSIX, anything that
//      resolves symbols) risks deadlock and static-init-order fragility.
//   5. Pay only when used. If the app loads the .so but never calls a function, a
//      constructor still does all the expensive work; lazy init costs nothing until
//      first use.
//
// So `OnceLock` defers the heavy, thread-spawning, signal-installing work until the
// app actually calls in — by which point the process is fully initialized, we're on
// a normal thread, and errors can be handled. It runs the init exactly once (a cheap
// atomic load on every call thereafter). The `Mutex` serializes calls because a
// wasmtime `Store` is `Send` but not `Sync`.
static LIB: OnceLock<Mutex<SandboxedLib>> = OnceLock::new();

/// Path to the precompiled guest module. Overridable via `LIND_MODULE`; defaults
/// to `guest.cwasm` in the process's working directory.
fn module_path() -> String {
    std::env::var("LIND_MODULE").unwrap_or_else(|_| "guest.cwasm".to_string())
}

fn lib() -> &'static Mutex<SandboxedLib> {
    LIB.get_or_init(|| {
        let cli = CliOptions::for_sandboxed_lib(module_path());
        let sandboxed_lib = init_sandboxed_lib(cli)
            .unwrap_or_else(|e| panic!("lind sandboxed-lib init failed: {e:?}"));
        Mutex::new(sandboxed_lib)
    })
}

/// Read a host C string into an owned buffer INCLUDING the trailing NUL, so that
/// after it is copied into guest memory the guest still sees a valid C string.
unsafe fn cstr_bytes(p: *const c_char) -> Vec<u8> {
    if p.is_null() {
        return vec![0];
    }
    unsafe { CStr::from_ptr(p) }.to_bytes_with_nul().to_vec()
}

fn call_buf(name: &str, args: &[Arg]) -> i64 {
    lib()
        .lock()
        .unwrap()
        .call(name, args)
        .unwrap_or_else(|e| panic!("lind call `{name}` failed: {e:?}"))
}

#[unsafe(no_mangle)]
pub extern "C" fn str_len(a0: *const c_char) -> usize {
    let b0 = unsafe { cstr_bytes(a0) };
    call_buf("str_len", &[Arg::Buf(&b0)]) as usize
}
