// AUTO-GENERATED by tools/marshal-gen/gen_grate.py — do not edit by hand.
// Auto-interposition grate for libz: registers a generic marshalling
// handler for every inference-marshalable function, each bound to (spec, &real_fn).
//
// Compile:
//   lind-clang -s --compile-grate --fpcast-emu libz_auto_grate.c -- -I<lind_marshal.h dir> <libz.a>
// Run (from lindfs/):
//   lind-wasm --preload env=/lib/libz.so grates/libz_auto_grate.cwasm <app...>
#include <lind_syscall.h>
#include <stdio.h>
#include <sys/wait.h>
#include <unistd.h>
#include <assert.h>
#include <stdint.h>

#include "lind_marshal.h"

// --- real library functions (defined via static-linked libz.a) ---
// K&R-style extern decls: only need them callable/address-takeable; fpcast-emu
// adapts the ABI at the uniform-pointer call site.
extern long gzwrite();
extern long gzfwrite();
extern long gzputc();
extern long gzputs();
extern long gzflush();
extern long gzsetparams();
extern long gzclose_w();
extern long adler32_z();
extern long adler32();
extern long adler32_combine();
extern long adler32_combine64();
extern long compress2_z();
extern long compress2();
extern long compress_z();
extern long compress();
extern long compressBound_z();
extern long compressBound();
extern long gzread();
extern long gzfread();
extern long gzgetc();
extern long gzgetc_();
extern long gzungetc();
extern long gzgets();
extern long gzdirect();
extern long gzclose_r();
extern long zlibCompileFlags();
extern long uncompress2_z();
extern long uncompress2();
extern long uncompress_z();
extern long uncompress();
extern long crc32_z();
extern long crc32();
extern long crc32_combine64();
extern long crc32_combine();
extern long crc32_combine_gen64();
extern long crc32_combine_gen();
extern long crc32_combine_op();
extern long gzbuffer();
extern long gzrewind();
extern long gzseek64();
extern long gzseek();
extern long gztell64();
extern long gztell();
extern long gzoffset64();
extern long gzoffset();
extern long gzeof();
extern long gzclearerr();
extern long gzclose();

// --- per-function marshalling specs (translated from libz.marshal.json) ---
static struct lind_arg_spec fspec_1 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_2 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_3 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_4[] = {
    { .offset = 0, .spec = &fspec_1, .touched = 1 },
    { .offset = 4, .spec = &fspec_2, .touched = 1 },
    { .offset = 8, .spec = &fspec_3, .touched = 1 },
};
static struct lind_layout layout_5 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_4, .struct_size = 12 };
static struct lind_arg_spec fspec_6 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_7 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_8 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_9[] = {
    { .offset = 0, .spec = &fspec_6, .touched = 1 },
    { .offset = 4, .spec = &fspec_7, .touched = 1 },
    { .offset = 8, .spec = &fspec_8, .touched = 1 },
};
static struct lind_layout layout_10 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_9, .struct_size = 12 };
static struct lind_arg_spec fspec_11 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_12 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_13 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_14[] = {
    { .offset = 0, .spec = &fspec_11, .touched = 1 },
    { .offset = 4, .spec = &fspec_12, .touched = 1 },
    { .offset = 8, .spec = &fspec_13, .touched = 1 },
};
static struct lind_layout layout_15 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_14, .struct_size = 12 };
static struct lind_arg_spec fspec_16 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_17 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_18 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_19[] = {
    { .offset = 0, .spec = &fspec_16, .touched = 1 },
    { .offset = 4, .spec = &fspec_17, .touched = 1 },
    { .offset = 8, .spec = &fspec_18, .touched = 1 },
};
static struct lind_layout layout_20 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_19, .struct_size = 12 };
static struct lind_arg_spec fspec_21 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_22 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_23 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_24[] = {
    { .offset = 0, .spec = &fspec_21, .touched = 1 },
    { .offset = 4, .spec = &fspec_22, .touched = 1 },
    { .offset = 8, .spec = &fspec_23, .touched = 1 },
};
static struct lind_layout layout_25 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_24, .struct_size = 12 };
static struct lind_arg_spec fspec_26 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_27 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_28 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_29[] = {
    { .offset = 0, .spec = &fspec_26, .touched = 1 },
    { .offset = 4, .spec = &fspec_27, .touched = 1 },
    { .offset = 8, .spec = &fspec_28, .touched = 1 },
};
static struct lind_layout layout_30 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_29, .struct_size = 12 };
static struct lind_arg_spec fspec_31 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_32 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_33 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_34[] = {
    { .offset = 0, .spec = &fspec_31, .touched = 1 },
    { .offset = 4, .spec = &fspec_32, .touched = 1 },
    { .offset = 8, .spec = &fspec_33, .touched = 1 },
};
static struct lind_layout layout_35 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_34, .struct_size = 12 };
static struct lind_arg_spec fspec_36 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_37 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_38 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_39[] = {
    { .offset = 0, .spec = &fspec_36, .touched = 1 },
    { .offset = 4, .spec = &fspec_37, .touched = 1 },
    { .offset = 8, .spec = &fspec_38, .touched = 1 },
};
static struct lind_layout layout_40 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_39, .struct_size = 12 };
static struct lind_arg_spec fspec_41 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_42 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_43 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_44[] = {
    { .offset = 0, .spec = &fspec_41, .touched = 1 },
    { .offset = 4, .spec = &fspec_42, .touched = 1 },
    { .offset = 8, .spec = &fspec_43, .touched = 1 },
};
static struct lind_layout layout_45 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_44, .struct_size = 12 };
static struct lind_arg_spec fspec_46 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_47 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_48 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_49[] = {
    { .offset = 0, .spec = &fspec_46, .touched = 1 },
    { .offset = 4, .spec = &fspec_47, .touched = 1 },
    { .offset = 8, .spec = &fspec_48, .touched = 1 },
};
static struct lind_layout layout_50 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_49, .struct_size = 12 };
static struct lind_arg_spec fspec_51 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_52 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_53 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_54[] = {
    { .offset = 0, .spec = &fspec_51, .touched = 1 },
    { .offset = 4, .spec = &fspec_52, .touched = 1 },
    { .offset = 8, .spec = &fspec_53, .touched = 1 },
};
static struct lind_layout layout_55 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_54, .struct_size = 12 };
static struct lind_arg_spec fspec_56 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_57 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_58 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_59[] = {
    { .offset = 0, .spec = &fspec_56, .touched = 1 },
    { .offset = 4, .spec = &fspec_57, .touched = 1 },
    { .offset = 8, .spec = &fspec_58, .touched = 1 },
};
static struct lind_layout layout_60 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_59, .struct_size = 12 };
static struct lind_arg_spec fspec_61 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_62 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_63 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_64[] = {
    { .offset = 0, .spec = &fspec_61, .touched = 1 },
    { .offset = 4, .spec = &fspec_62, .touched = 1 },
    { .offset = 8, .spec = &fspec_63, .touched = 1 },
};
static struct lind_layout layout_65 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_64, .struct_size = 12 };
static struct lind_arg_spec fspec_66 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_67 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_68 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_69[] = {
    { .offset = 0, .spec = &fspec_66, .touched = 1 },
    { .offset = 4, .spec = &fspec_67, .touched = 1 },
    { .offset = 8, .spec = &fspec_68, .touched = 1 },
};
static struct lind_layout layout_70 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_69, .struct_size = 12 };
static struct lind_arg_spec fspec_71 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_72 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_73 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_74[] = {
    { .offset = 0, .spec = &fspec_71, .touched = 1 },
    { .offset = 4, .spec = &fspec_72, .touched = 1 },
    { .offset = 8, .spec = &fspec_73, .touched = 1 },
};
static struct lind_layout layout_75 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_74, .struct_size = 12 };
static struct lind_arg_spec fspec_76 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_77 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_78 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_79[] = {
    { .offset = 0, .spec = &fspec_76, .touched = 1 },
    { .offset = 4, .spec = &fspec_77, .touched = 1 },
    { .offset = 8, .spec = &fspec_78, .touched = 1 },
};
static struct lind_layout layout_80 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_79, .struct_size = 12 };
static struct lind_arg_spec fspec_81 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_82 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_83 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_84[] = {
    { .offset = 0, .spec = &fspec_81, .touched = 1 },
    { .offset = 4, .spec = &fspec_82, .touched = 1 },
    { .offset = 8, .spec = &fspec_83, .touched = 1 },
};
static struct lind_layout layout_85 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_84, .struct_size = 12 };
static struct lind_arg_spec fspec_86 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_87 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_88 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_89[] = {
    { .offset = 0, .spec = &fspec_86, .touched = 1 },
    { .offset = 4, .spec = &fspec_87, .touched = 1 },
    { .offset = 8, .spec = &fspec_88, .touched = 1 },
};
static struct lind_layout layout_90 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_89, .struct_size = 12 };
static struct lind_arg_spec fspec_91 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_92 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_93 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_94[] = {
    { .offset = 0, .spec = &fspec_91, .touched = 1 },
    { .offset = 4, .spec = &fspec_92, .touched = 1 },
    { .offset = 8, .spec = &fspec_93, .touched = 1 },
};
static struct lind_layout layout_95 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_94, .struct_size = 12 };
static struct lind_arg_spec fspec_96 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_97 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_98 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_99[] = {
    { .offset = 0, .spec = &fspec_96, .touched = 1 },
    { .offset = 4, .spec = &fspec_97, .touched = 1 },
    { .offset = 8, .spec = &fspec_98, .touched = 1 },
};
static struct lind_layout layout_100 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_99, .struct_size = 12 };
static struct lind_arg_spec fspec_101 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_102 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_103 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_104[] = {
    { .offset = 0, .spec = &fspec_101, .touched = 1 },
    { .offset = 4, .spec = &fspec_102, .touched = 1 },
    { .offset = 8, .spec = &fspec_103, .touched = 1 },
};
static struct lind_layout layout_105 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_104, .struct_size = 12 };
static struct lind_arg_spec fspec_106 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_107 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_108 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_109[] = {
    { .offset = 0, .spec = &fspec_106, .touched = 1 },
    { .offset = 4, .spec = &fspec_107, .touched = 1 },
    { .offset = 8, .spec = &fspec_108, .touched = 1 },
};
static struct lind_layout layout_110 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_109, .struct_size = 12 };
static struct lind_arg_spec fspec_111 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_112 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_113 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_114[] = {
    { .offset = 0, .spec = &fspec_111, .touched = 1 },
    { .offset = 4, .spec = &fspec_112, .touched = 1 },
    { .offset = 8, .spec = &fspec_113, .touched = 1 },
};
static struct lind_layout layout_115 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_114, .struct_size = 12 };
static struct lind_arg_spec fspec_116 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_117 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_118 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_119[] = {
    { .offset = 0, .spec = &fspec_116, .touched = 1 },
    { .offset = 4, .spec = &fspec_117, .touched = 1 },
    { .offset = 8, .spec = &fspec_118, .touched = 1 },
};
static struct lind_layout layout_120 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_119, .struct_size = 12 };
static struct lind_arg_spec fspec_121 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_122 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_123 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_124[] = {
    { .offset = 0, .spec = &fspec_121, .touched = 1 },
    { .offset = 4, .spec = &fspec_122, .touched = 1 },
    { .offset = 8, .spec = &fspec_123, .touched = 1 },
};
static struct lind_layout layout_125 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_124, .struct_size = 12 };
static struct lind_arg_spec fspec_126 = { .kind = LIND_ARG_SCALAR };
static struct lind_arg_spec fspec_127 = { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR };
static struct lind_arg_spec fspec_128 = { .kind = LIND_ARG_SCALAR };
static struct lind_field fields_129[] = {
    { .offset = 0, .spec = &fspec_126, .touched = 1 },
    { .offset = 4, .spec = &fspec_127, .touched = 1 },
    { .offset = 8, .spec = &fspec_128, .touched = 1 },
};
static struct lind_layout layout_130 = { .kind = LIND_LO_STRUCT, .nfields = 3, .fields = fields_129, .struct_size = 12 };
static struct lind_marshal_spec spec_gzwrite = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_5 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 2 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzfwrite = {
    .nargs = 4,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 1 },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_10 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzputc = {
    .nargs = 2,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_15 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzputs = {
    .nargs = 2,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_20 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzflush = {
    .nargs = 2,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_25 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzsetparams = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_30 },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzclose_w = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_35 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_adler32_z = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 2 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_adler32 = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 2 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_adler32_combine = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_adler32_combine64 = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_compress2_z = {
    .nargs = 5,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_FROM_ARG_POINTEE, .size_arg_index = 1 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 4 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 3 },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_compress2 = {
    .nargs = 5,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_FROM_ARG_POINTEE, .size_arg_index = 1 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 4 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 3 },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_compress_z = {
    .nargs = 4,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_FROM_ARG_POINTEE, .size_arg_index = 1 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 4 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 3 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_compress = {
    .nargs = 4,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_FROM_ARG_POINTEE, .size_arg_index = 1 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 4 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 3 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_compressBound_z = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_compressBound = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzread = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_40 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 2 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzfread = {
    .nargs = 4,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 1 },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_45 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzgetc = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_50 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzgetc_ = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_55 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzungetc = {
    .nargs = 2,
    .args = {
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_60 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzgets = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_65 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_OUT, .size_kind = LIND_SIZE_CSTR },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_PTR_ALIAS_ARG, .alias_arg_index = 1 },
};
static struct lind_marshal_spec spec_gzdirect = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_70 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzclose_r = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_75 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_zlibCompileFlags = {
    .nargs = 0,
    .args = {

    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_uncompress2_z = {
    .nargs = 4,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_FROM_ARG_POINTEE, .size_arg_index = 1 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 4 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG_POINTEE, .size_arg_index = 3 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 4 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_uncompress2 = {
    .nargs = 4,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_FROM_ARG_POINTEE, .size_arg_index = 1 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 4 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG_POINTEE, .size_arg_index = 3 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 4 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_uncompress_z = {
    .nargs = 4,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_FROM_ARG_POINTEE, .size_arg_index = 1 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 4 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 3 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_uncompress = {
    .nargs = 4,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_FROM_ARG_POINTEE, .size_arg_index = 1 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 4 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 3 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_crc32_z = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 2 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_crc32 = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 2 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_crc32_combine64 = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_crc32_combine = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_crc32_combine_gen64 = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_crc32_combine_gen = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_crc32_combine_op = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzbuffer = {
    .nargs = 2,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_80 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzrewind = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_85 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzseek64 = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_90 },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzseek = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_95 },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gztell64 = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_100 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gztell = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_105 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzoffset64 = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_110 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzoffset = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_115 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzeof = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_120 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_gzclearerr = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_INOUT, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_125 },
    },
    .ret = { .kind = LIND_RET_VOID },
};
static struct lind_marshal_spec spec_gzclose = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CONST, .const_size = 12, .layout = &layout_130 },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};

// --- per-symbol dispatch contexts ---
struct libctx { const struct lind_marshal_spec *spec; void *real_fn; };

struct reg_entry { const char *name; struct libctx ctx; };
static struct reg_entry g_table[] = {
    { "gzwrite", { &spec_gzwrite, (void *)(uintptr_t)&gzwrite } },
    { "gzfwrite", { &spec_gzfwrite, (void *)(uintptr_t)&gzfwrite } },
    { "gzputc", { &spec_gzputc, (void *)(uintptr_t)&gzputc } },
    { "gzputs", { &spec_gzputs, (void *)(uintptr_t)&gzputs } },
    { "gzflush", { &spec_gzflush, (void *)(uintptr_t)&gzflush } },
    { "gzsetparams", { &spec_gzsetparams, (void *)(uintptr_t)&gzsetparams } },
    { "gzclose_w", { &spec_gzclose_w, (void *)(uintptr_t)&gzclose_w } },
    { "adler32_z", { &spec_adler32_z, (void *)(uintptr_t)&adler32_z } },
    { "adler32", { &spec_adler32, (void *)(uintptr_t)&adler32 } },
    { "adler32_combine", { &spec_adler32_combine, (void *)(uintptr_t)&adler32_combine } },
    { "adler32_combine64", { &spec_adler32_combine64, (void *)(uintptr_t)&adler32_combine64 } },
    { "compress2_z", { &spec_compress2_z, (void *)(uintptr_t)&compress2_z } },
    { "compress2", { &spec_compress2, (void *)(uintptr_t)&compress2 } },
    { "compress_z", { &spec_compress_z, (void *)(uintptr_t)&compress_z } },
    { "compress", { &spec_compress, (void *)(uintptr_t)&compress } },
    { "compressBound_z", { &spec_compressBound_z, (void *)(uintptr_t)&compressBound_z } },
    { "compressBound", { &spec_compressBound, (void *)(uintptr_t)&compressBound } },
    { "gzread", { &spec_gzread, (void *)(uintptr_t)&gzread } },
    { "gzfread", { &spec_gzfread, (void *)(uintptr_t)&gzfread } },
    { "gzgetc", { &spec_gzgetc, (void *)(uintptr_t)&gzgetc } },
    { "gzgetc_", { &spec_gzgetc_, (void *)(uintptr_t)&gzgetc_ } },
    { "gzungetc", { &spec_gzungetc, (void *)(uintptr_t)&gzungetc } },
    { "gzgets", { &spec_gzgets, (void *)(uintptr_t)&gzgets } },
    { "gzdirect", { &spec_gzdirect, (void *)(uintptr_t)&gzdirect } },
    { "gzclose_r", { &spec_gzclose_r, (void *)(uintptr_t)&gzclose_r } },
    { "zlibCompileFlags", { &spec_zlibCompileFlags, (void *)(uintptr_t)&zlibCompileFlags } },
    { "uncompress2_z", { &spec_uncompress2_z, (void *)(uintptr_t)&uncompress2_z } },
    { "uncompress2", { &spec_uncompress2, (void *)(uintptr_t)&uncompress2 } },
    { "uncompress_z", { &spec_uncompress_z, (void *)(uintptr_t)&uncompress_z } },
    { "uncompress", { &spec_uncompress, (void *)(uintptr_t)&uncompress } },
    { "crc32_z", { &spec_crc32_z, (void *)(uintptr_t)&crc32_z } },
    { "crc32", { &spec_crc32, (void *)(uintptr_t)&crc32 } },
    { "crc32_combine64", { &spec_crc32_combine64, (void *)(uintptr_t)&crc32_combine64 } },
    { "crc32_combine", { &spec_crc32_combine, (void *)(uintptr_t)&crc32_combine } },
    { "crc32_combine_gen64", { &spec_crc32_combine_gen64, (void *)(uintptr_t)&crc32_combine_gen64 } },
    { "crc32_combine_gen", { &spec_crc32_combine_gen, (void *)(uintptr_t)&crc32_combine_gen } },
    { "crc32_combine_op", { &spec_crc32_combine_op, (void *)(uintptr_t)&crc32_combine_op } },
    { "gzbuffer", { &spec_gzbuffer, (void *)(uintptr_t)&gzbuffer } },
    { "gzrewind", { &spec_gzrewind, (void *)(uintptr_t)&gzrewind } },
    { "gzseek64", { &spec_gzseek64, (void *)(uintptr_t)&gzseek64 } },
    { "gzseek", { &spec_gzseek, (void *)(uintptr_t)&gzseek } },
    { "gztell64", { &spec_gztell64, (void *)(uintptr_t)&gztell64 } },
    { "gztell", { &spec_gztell, (void *)(uintptr_t)&gztell } },
    { "gzoffset64", { &spec_gzoffset64, (void *)(uintptr_t)&gzoffset64 } },
    { "gzoffset", { &spec_gzoffset, (void *)(uintptr_t)&gzoffset } },
    { "gzeof", { &spec_gzeof, (void *)(uintptr_t)&gzeof } },
    { "gzclearerr", { &spec_gzclearerr, (void *)(uintptr_t)&gzclearerr } },
    { "gzclose", { &spec_gzclose, (void *)(uintptr_t)&gzclose } },
};
#define G_TABLE_N ((int)(sizeof(g_table)/sizeof(g_table[0])))

// --- generic dispatcher: registered value is a struct libctx* ---
int pass_fptr_to_wt(uint64_t ctx_ptr_u64, uint64_t cageid,
                    uint64_t a1, uint64_t a1c, uint64_t a2, uint64_t a2c,
                    uint64_t a3, uint64_t a3c, uint64_t a4, uint64_t a4c,
                    uint64_t a5, uint64_t a5c, uint64_t a6, uint64_t a6c) {
    if (ctx_ptr_u64 == 0) { fprintf(stderr, "[libz-grate] null ctx\n"); assert(0); }
    struct libctx *ctx = (struct libctx *)(uintptr_t)ctx_ptr_u64;
    uint64_t raw[6]   = { a1, a2, a3, a4, a5, a6 };
    uint64_t cages[6] = { a1c, a2c, a3c, a4c, a5c, a6c };
    uint64_t src = 0;
    for (int i = 0; i < 6 && src == 0; i++) src = cages[i];
    return (int)lind_marshal_dispatch(ctx->real_fn, ctx->spec, src, cageid,
                                      raw, ctx->spec->nargs);
}

int main(int argc, char *argv[]) {
    if (argc < 2) { fprintf(stderr, "Usage: %s <app> [args...]\n", argv[0]); assert(0); }
    int grateid = getpid();
    pid_t pid = fork();
    if (pid < 0) { perror("fork"); assert(0); }
    if (pid == 0) {
        int cageid = getpid();
        int ok = 0, fail = 0;
        for (int i = 0; i < G_TABLE_N; i++) {
            int r = register_lib_handler(cageid, "env", g_table[i].name,
                        grateid, (uint64_t)(uintptr_t)&g_table[i].ctx);
            if (r == 0) ok++;
            else { fail++; fprintf(stderr, "[libz-grate] register %s failed: %d\n",
                                    g_table[i].name, r); }
        }
        fprintf(stderr, "[libz-grate] registered %d/%d handlers\n", ok, ok + fail);
        if (execv(argv[1], &argv[1]) == -1) { perror("execv"); assert(0); }
    }
    int status;
    while (wait(&status) > 0) {}
    int ce = WIFEXITED(status) ? WEXITSTATUS(status) : -1;
    fprintf(stderr, "[libz-grate] app exited %d\n", ce);
    return ce == 0 ? 0 : 1;
}
