// @generated by tools/gen_stubs.sh from functions.txt — do not edit by hand.
// Regenerate with `make gen`.
//
// Native shared library whose exported symbols run their real implementations
// inside the lind/wasmtime sandbox. A native app links this like any other .so
// and calls the symbols with no knowledge that the work happens in a wasm guest.
// On the first call the lind runtime is brought up and the guest module is
// instantiated as a long-lived sandboxed library; later calls reuse it.
//
// Scope (scalar stage): i32 in/out only, a single global instance, and a global
// lock serializing every call (a wasmtime Store is not Sync).

use std::sync::{Mutex, OnceLock};

use lind_boot::{CliOptions, SandboxedLib, init_sandboxed_lib};

static LIB: OnceLock<Mutex<SandboxedLib>> = OnceLock::new();

/// Path to the precompiled guest module. Overridable via `LIND_MODULE`; defaults
/// to `guest.cwasm` in the process's working directory.
fn module_path() -> String {
    std::env::var("LIND_MODULE").unwrap_or_else(|_| "guest.cwasm".to_string())
}

fn lib() -> &'static Mutex<SandboxedLib> {
    LIB.get_or_init(|| {
        let cli = CliOptions::for_sandboxed_lib(module_path());
        let sandboxed_lib = init_sandboxed_lib(cli)
            .unwrap_or_else(|e| panic!("lind sandboxed-lib init failed: {e:?}"));
        Mutex::new(sandboxed_lib)
    })
}

fn call(name: &str, args: &[i32]) -> i32 {
    lib()
        .lock()
        .unwrap()
        .call_scalar(name, args)
        .unwrap_or_else(|e| panic!("lind call `{name}` failed: {e:?}"))
}

#[unsafe(no_mangle)]
pub extern "C" fn add(a0: i32, a1: i32) -> i32 {
    call("add", &[a0, a1])
}

#[unsafe(no_mangle)]
pub extern "C" fn subtract(a0: i32, a1: i32) -> i32 {
    call("subtract", &[a0, a1])
}
