#!/usr/bin/env bash
# Generate the extern "C" stub layer (stub/src/lib.rs) for a sandboxed-lib example
# from a functions.txt manifest.
#
#   Usage: gen_stubs.sh <functions.txt> > stub/src/lib.rs
#
# functions.txt format (one per line; '#' comments and blank lines ignored):
#
#   <name> <ret-type> <arg-type>...
#
# Types understood so far:
#   i32    a scalar int, passed by value (a wasm i32 IS a native int)
#   usize  a size_t-shaped return (widened from the wasm i32/i64 result)
#   cstr   a `const char*`: the host string is copied into guest memory and the
#          call receives the resulting guest offset (this is *marshalling*)
#
# A function whose args and return are all `i32` gets a trivial pass-through stub.
# Any `cstr` arg (or non-i32 return) makes it a *marshalled* stub that bounces the
# buffer through the guest allocator. This is the seam where richer types (buffers,
# structs, ...) get added later.
set -euo pipefail

funcs="${1:?usage: gen_stubs.sh <functions.txt>}"

# --- pass 1: classify what helpers/imports we need -------------------------------
has_scalar=0     # at least one all-i32 function -> emit the scalar `call` helper
has_marshal=0    # at least one marshalled function -> emit Arg/cstr helpers + imports
while IFS= read -r line; do
    line="${line%%#*}"
    [ -z "${line// /}" ] && continue
    # shellcheck disable=SC2086
    set -- $line
    _name="$1"; shift
    ret="$1"; shift
    marshal=0
    [ "$ret" != "i32" ] && marshal=1
    for t in "$@"; do [ "$t" != "i32" ] && marshal=1; done
    if [ "$marshal" -eq 1 ]; then has_marshal=1; else has_scalar=1; fi
done < "$funcs"

# --- header: banner ---------------------------------------------------------------
cat <<'HEADER'
// @generated by tools/gen_stubs.sh from functions.txt — do not edit by hand.
// Regenerate with `make gen`.
//
// Native shared library whose exported symbols run their real implementations
// inside the lind/wasmtime sandbox. A native app links this like any other .so
// and calls the symbols with no knowledge that the work happens in a wasm guest.
// On the first call the lind runtime is brought up and the guest module is
// instantiated as a long-lived sandboxed library; later calls reuse it.

use std::sync::{Mutex, OnceLock};
HEADER

# --- header: imports (marshalling pulls in a couple more) -------------------------
if [ "$has_marshal" -eq 1 ]; then
    printf '\nuse core::ffi::{CStr, c_char};\n'
    printf '\nuse lind_boot::{Arg, CliOptions, SandboxedLib, init_sandboxed_lib};\n'
else
    printf '\nuse lind_boot::{CliOptions, SandboxedLib, init_sandboxed_lib};\n'
fi

# --- header: lazy-init rationale + the resident instance --------------------------
cat <<'CORE'

// Why the guest is initialized lazily (on the first call) rather than in a
// load-time constructor (C `__attribute__((constructor))` / Rust `#[ctor]`, which
// place a function in `.init_array` for the loader to run at dlopen/startup).
// `init_sandboxed_lib` is heavyweight — it brings up the whole lind runtime
// (RawPOSIX, the 3i trampoline + syscall handlers, the wasmtime engine, grate
// worker threads, a SIGUSR2 handler) and instantiates the guest. A constructor is
// the wrong place for that:
//
//   1. No error handling. A constructor returns void and runs before the app's
//      `main`. If init fails, the only option is to abort the whole process before
//      it starts — you cannot return an error the app can handle. Lazy init lets
//      the first call report failure normally.
//   2. Threads at load time. Init spawns threads (grate workers). Creating threads
//      from a constructor is hazardous: e.g. if the app later `fork()`s, only the
//      calling thread survives in the child, leaving the others' locks/state
//      broken. Many runtimes forbid pre-`main` thread creation.
//   3. Signal handlers at load time. Init installs a SIGUSR2 handler; doing that
//      during load can clobber the host app's signal setup before it is ready.
//   4. Ordering / dlopen lock. Constructors run while the dynamic loader holds its
//      internal lock and while other libraries' constructors and the language
//      runtime may not be fully up. Heavy init here (tokio, RawPOSIX, anything that
//      resolves symbols) risks deadlock and static-init-order fragility.
//   5. Pay only when used. If the app loads the .so but never calls a function, a
//      constructor still does all the expensive work; lazy init costs nothing until
//      first use.
//
// So `OnceLock` defers the heavy, thread-spawning, signal-installing work until the
// app actually calls in — by which point the process is fully initialized, we're on
// a normal thread, and errors can be handled. It runs the init exactly once (a cheap
// atomic load on every call thereafter). The `Mutex` serializes calls because a
// wasmtime `Store` is `Send` but not `Sync`.
static LIB: OnceLock<Mutex<SandboxedLib>> = OnceLock::new();

/// Path to the precompiled guest module. Overridable via `LIND_MODULE`; defaults
/// to `guest.cwasm` in the process's working directory.
fn module_path() -> String {
    std::env::var("LIND_MODULE").unwrap_or_else(|_| "guest.cwasm".to_string())
}

fn lib() -> &'static Mutex<SandboxedLib> {
    LIB.get_or_init(|| {
        let cli = CliOptions::for_sandboxed_lib(module_path());
        let sandboxed_lib = init_sandboxed_lib(cli)
            .unwrap_or_else(|e| panic!("lind sandboxed-lib init failed: {e:?}"));
        Mutex::new(sandboxed_lib)
    })
}
CORE

# --- header: the scalar forwarding helper (only if needed) ------------------------
if [ "$has_scalar" -eq 1 ]; then
    cat <<'SCALAR'

fn call(name: &str, args: &[i32]) -> i32 {
    lib()
        .lock()
        .unwrap()
        .call_scalar(name, args)
        .unwrap_or_else(|e| panic!("lind call `{name}` failed: {e:?}"))
}
SCALAR
fi

# --- header: the marshalling helpers (only if needed) -----------------------------
if [ "$has_marshal" -eq 1 ]; then
    cat <<'MARSHAL'

/// Read a host C string into an owned buffer INCLUDING the trailing NUL, so that
/// after it is copied into guest memory the guest still sees a valid C string.
unsafe fn cstr_bytes(p: *const c_char) -> Vec<u8> {
    if p.is_null() {
        return vec![0];
    }
    unsafe { CStr::from_ptr(p) }.to_bytes_with_nul().to_vec()
}

fn call_buf(name: &str, args: &[Arg]) -> i64 {
    lib()
        .lock()
        .unwrap()
        .call(name, args)
        .unwrap_or_else(|e| panic!("lind call `{name}` failed: {e:?}"))
}
MARSHAL
fi

# --- per-function stubs -----------------------------------------------------------
while IFS= read -r line; do
    line="${line%%#*}"
    [ -z "${line// /}" ] && continue
    # shellcheck disable=SC2086
    set -- $line
    name="$1"; shift
    ret="$1"; shift

    # is this a plain scalar function (all i32 args + i32 return)?
    scalar=1
    [ "$ret" != "i32" ] && scalar=0
    for t in "$@"; do [ "$t" != "i32" ] && scalar=0; done

    if [ "$scalar" -eq 1 ]; then
        # trivial pass-through: extern "C" fn NAME(a0: i32, ...) -> i32
        params=""; slice=""; i=0
        for _ in "$@"; do
            [ "$i" -gt 0 ] && { params="$params, "; slice="$slice, "; }
            params="${params}a${i}: i32"
            slice="${slice}a${i}"
            i=$((i + 1))
        done
        printf '\n#[unsafe(no_mangle)]\npub extern "C" fn %s(%s) -> i32 {\n    call("%s", &[%s])\n}\n' \
            "$name" "$params" "$name" "$slice"
    else
        # marshalled: build the param list, any copy-in preamble, and the Arg list.
        params=""; preamble=""; argexpr=""; i=0
        for t in "$@"; do
            [ "$i" -gt 0 ] && { params="$params, "; argexpr="$argexpr, "; }
            case "$t" in
                i32)
                    params="${params}a${i}: i32"
                    argexpr="${argexpr}Arg::I32(a${i})"
                    ;;
                cstr)
                    params="${params}a${i}: *const c_char"
                    preamble="${preamble}    let b${i} = unsafe { cstr_bytes(a${i}) };\n"
                    argexpr="${argexpr}Arg::Buf(&b${i})"
                    ;;
                *)
                    echo "gen_stubs.sh: unknown arg type '$t' for '$name'" >&2
                    exit 2
                    ;;
            esac
            i=$((i + 1))
        done
        case "$ret" in
            i32)   rust_ret="i32";   ret_cast=" as i32" ;;
            usize) rust_ret="usize"; ret_cast=" as usize" ;;
            i64)   rust_ret="i64";   ret_cast="" ;;
            *)
                echo "gen_stubs.sh: unknown return type '$ret' for '$name'" >&2
                exit 2
                ;;
        esac
        printf '\n#[unsafe(no_mangle)]\npub extern "C" fn %s(%s) -> %s {\n' \
            "$name" "$params" "$rust_ret"
        [ -n "$preamble" ] && printf '%b' "$preamble"
        printf '    call_buf("%s", &[%s])%s\n}\n' "$name" "$argexpr" "$ret_cast"
    fi
done < "$funcs"
