#!/usr/bin/env bash
# Generate the extern "C" stub layer (stub/src/lib.rs) for a sandboxed-lib example
# from a functions.txt manifest.
#
#   Usage: gen_stubs.sh <functions.txt> > stub/src/lib.rs
#
# functions.txt format (one per line; '#' comments and blank lines ignored):
#
#   <name> <ret-type> <arg-spec>...
#
# Return types:  i32 | usize | void
#
# Argument specs:
#   i32                     scalar int, passed by value
#   usize                   scalar size_t, passed by value
#   cstr                    const char* input — copied INTO the guest (marshalling)
#   outbuf,cap=C,len=X      caller-allocated char* output buffer:
#                             cap=C  capacity is the value of arg #C (1-based)
#                             len=X  how many bytes to copy back out — one of:
#                                      ret    = the function's return value
#                                      nul    = up to & including the first NUL
#                                      cap    = the whole buffer (capacity)
#                                      arg<M> = the value the guest wrote into outlen arg #M
#   outlen                  size_t* output param — the guest writes a length there,
#                             read back into the caller's size_t and usable as len=arg<M>
#
# A function whose args + return are all `i32` gets a trivial pass-through stub.
# Anything else is a *marshalled* stub built from an `Arg` array. This is the seam
# where richer types get added later.
set -euo pipefail

funcs="${1:?usage: gen_stubs.sh <functions.txt>}"

# --- pass 1: classify what helpers/imports we need -------------------------------
has_scalar=0   # an all-i32 function -> emit the scalar `call` helper
has_marshal=0  # any marshalled function -> emit Arg-array helpers + imports
has_cstr=0     # any cstr arg -> need CStr + cstr_bytes
has_ptr=0      # any cstr/outbuf/outlen arg -> need c_char / pointer params
while IFS= read -r line; do
    line="${line%%#*}"
    [ -z "${line// /}" ] && continue
    # shellcheck disable=SC2086
    set -- $line
    _name="$1"; shift
    ret="$1"; shift
    marshal=0
    [ "$ret" != "i32" ] && marshal=1
    for t in "$@"; do
        case "$t" in
            i32) ;;
            usize) marshal=1 ;;
            cstr) marshal=1; has_cstr=1; has_ptr=1 ;;
            outbuf,*) marshal=1; has_ptr=1 ;;
            outlen) marshal=1; has_ptr=1 ;;
            *) echo "gen_stubs.sh: unknown arg spec '$t'" >&2; exit 2 ;;
        esac
    done
    if [ "$marshal" -eq 1 ]; then has_marshal=1; else has_scalar=1; fi
done < "$funcs"

# --- header: banner ---------------------------------------------------------------
cat <<'HEADER'
// @generated by tools/gen_stubs.sh from functions.txt — do not edit by hand.
// Regenerate with `make gen`.
//
// Native shared library whose exported symbols run their real implementations
// inside the lind/wasmtime sandbox. A native app links this like any other .so
// and calls the symbols with no knowledge that the work happens in a wasm guest.
// On the first call the lind runtime is brought up and the guest module is
// instantiated as a long-lived sandboxed library; later calls reuse it.

use std::sync::{Mutex, OnceLock};
HEADER

# --- header: imports (marshalling pulls in a couple more) -------------------------
if [ "$has_cstr" -eq 1 ]; then
    printf '\nuse core::ffi::{CStr, c_char};\n'
elif [ "$has_ptr" -eq 1 ]; then
    printf '\nuse core::ffi::c_char;\n'
fi
if [ "$has_marshal" -eq 1 ]; then
    printf '\nuse lind_boot::{Arg, CliOptions, OutLen, SandboxedLib, init_sandboxed_lib};\n'
else
    printf '\nuse lind_boot::{CliOptions, SandboxedLib, init_sandboxed_lib};\n'
fi

# --- header: lazy-init rationale + the resident instance --------------------------
cat <<'CORE'

// Why the guest is initialized lazily (on the first call) rather than in a
// load-time constructor (C `__attribute__((constructor))` / Rust `#[ctor]`, which
// place a function in `.init_array` for the loader to run at dlopen/startup).
// `init_sandboxed_lib` is heavyweight — it brings up the whole lind runtime
// (RawPOSIX, the 3i trampoline + syscall handlers, the wasmtime engine, grate
// worker threads, a SIGUSR2 handler) and instantiates the guest. A constructor is
// the wrong place for that:
//
//   1. No error handling. A constructor returns void and runs before the app's
//      `main`. If init fails, the only option is to abort the whole process before
//      it starts — you cannot return an error the app can handle. Lazy init lets
//      the first call report failure normally.
//   2. Threads at load time. Init spawns threads (grate workers). Creating threads
//      from a constructor is hazardous: e.g. if the app later `fork()`s, only the
//      calling thread survives in the child, leaving the others' locks/state
//      broken. Many runtimes forbid pre-`main` thread creation.
//   3. Signal handlers at load time. Init installs a SIGUSR2 handler; doing that
//      during load can clobber the host app's signal setup before it is ready.
//   4. Ordering / dlopen lock. Constructors run while the dynamic loader holds its
//      internal lock and while other libraries' constructors and the language
//      runtime may not be fully up. Heavy init here (tokio, RawPOSIX, anything that
//      resolves symbols) risks deadlock and static-init-order fragility.
//   5. Pay only when used. If the app loads the .so but never calls a function, a
//      constructor still does all the expensive work; lazy init costs nothing until
//      first use.
//
// So `OnceLock` defers the heavy, thread-spawning, signal-installing work until the
// app actually calls in — by which point the process is fully initialized, we're on
// a normal thread, and errors can be handled. It runs the init exactly once (a cheap
// atomic load on every call thereafter). The `Mutex` serializes calls because a
// wasmtime `Store` is `Send` but not `Sync`.
static LIB: OnceLock<Mutex<SandboxedLib>> = OnceLock::new();

/// Path to the precompiled guest module. Overridable via `LIND_MODULE`; defaults
/// to `guest.cwasm` in the process's working directory.
fn module_path() -> String {
    std::env::var("LIND_MODULE").unwrap_or_else(|_| "guest.cwasm".to_string())
}

fn lib() -> &'static Mutex<SandboxedLib> {
    LIB.get_or_init(|| {
        let cli = CliOptions::for_sandboxed_lib(module_path());
        let sandboxed_lib = init_sandboxed_lib(cli)
            .unwrap_or_else(|e| panic!("lind sandboxed-lib init failed: {e:?}"));
        Mutex::new(sandboxed_lib)
    })
}
CORE

# --- header: the scalar forwarding helper (only if needed) ------------------------
if [ "$has_scalar" -eq 1 ]; then
    cat <<'SCALAR'

fn call(name: &str, args: &[i32]) -> i32 {
    lib()
        .lock()
        .unwrap()
        .call_scalar(name, args)
        .unwrap_or_else(|e| panic!("lind call `{name}` failed: {e:?}"))
}
SCALAR
fi

# --- header: the marshalling helpers (only if needed) -----------------------------
if [ "$has_cstr" -eq 1 ]; then
    cat <<'CSTR'

/// Read a host C string into an owned buffer INCLUDING the trailing NUL, so that
/// after it is copied into guest memory the guest still sees a valid C string.
unsafe fn cstr_bytes(p: *const c_char) -> Vec<u8> {
    if p.is_null() {
        return vec![0];
    }
    unsafe { CStr::from_ptr(p) }.to_bytes_with_nul().to_vec()
}
CSTR
fi
if [ "$has_marshal" -eq 1 ]; then
    cat <<'MARSHAL'

fn call_buf(name: &str, args: &mut [Arg]) -> i64 {
    lib()
        .lock()
        .unwrap()
        .call(name, args)
        .unwrap_or_else(|e| panic!("lind call `{name}` failed: {e:?}"))
}
MARSHAL
fi

# --- per-function stubs -----------------------------------------------------------
while IFS= read -r line; do
    line="${line%%#*}"
    [ -z "${line// /}" ] && continue
    # shellcheck disable=SC2086
    set -- $line
    name="$1"; shift
    ret="$1"; shift

    # scalar fast path: all-i32 args + i32 return.
    scalar=1
    [ "$ret" != "i32" ] && scalar=0
    for t in "$@"; do [ "$t" != "i32" ] && scalar=0; done

    if [ "$scalar" -eq 1 ]; then
        params=""; slice=""; i=0
        for _ in "$@"; do
            [ "$i" -gt 0 ] && { params="$params, "; slice="$slice, "; }
            params="${params}a${i}: i32"
            slice="${slice}a${i}"
            i=$((i + 1))
        done
        printf '\n#[unsafe(no_mangle)]\npub extern "C" fn %s(%s) -> i32 {\n    call("%s", &[%s])\n}\n' \
            "$name" "$params" "$name" "$slice"
        continue
    fi

    # marshalled path: build params, a copy-in/alloc preamble, and the Arg array.
    params=""; preamble=""; argexpr=""; i=0
    for t in "$@"; do
        [ "$i" -gt 0 ] && { params="$params, "; argexpr="$argexpr,"; }
        case "$t" in
            i32)
                params="${params}a${i}: i32"
                argexpr="${argexpr}\n        Arg::I32(a${i})"
                ;;
            usize)
                params="${params}a${i}: usize"
                argexpr="${argexpr}\n        Arg::USize(a${i})"
                ;;
            cstr)
                params="${params}a${i}: *const c_char"
                preamble="${preamble}    let in${i} = unsafe { cstr_bytes(a${i}) };\n"
                argexpr="${argexpr}\n        Arg::Buf(&in${i})"
                ;;
            outbuf,*)
                # parse cap=C and len=X out of the comma-separated spec
                cap=""; lenspec=""
                IFS=, read -ra fields <<< "$t"
                for f in "${fields[@]}"; do
                    case "$f" in
                        cap=*) cap="${f#cap=}" ;;
                        len=*) lenspec="${f#len=}" ;;
                    esac
                done
                [ -z "$cap" ] && { echo "gen_stubs.sh: outbuf missing cap= in '$t' ($name)" >&2; exit 2; }
                capidx=$((cap - 1))   # 1-based arg # -> 0-based param name
                case "$lenspec" in
                    ret) outlen="OutLen::Ret" ;;
                    nul) outlen="OutLen::Nul" ;;
                    cap) outlen="OutLen::Cap" ;;
                    arg*) outlen="OutLen::FromArg($(( ${lenspec#arg} - 1 )))" ;;
                    *) echo "gen_stubs.sh: outbuf bad len='$lenspec' in '$t' ($name)" >&2; exit 2 ;;
                esac
                params="${params}a${i}: *mut c_char"
                preamble="${preamble}    let out${i} = unsafe { core::slice::from_raw_parts_mut(a${i} as *mut u8, a${capidx} as usize) };\n"
                argexpr="${argexpr}\n        Arg::Out { dst: out${i}, len: ${outlen} }"
                ;;
            outlen)
                params="${params}a${i}: *mut usize"
                preamble="${preamble}    let len${i} = unsafe { &mut *a${i} };\n"
                argexpr="${argexpr}\n        Arg::OutLen(len${i})"
                ;;
        esac
        i=$((i + 1))
    done

    case "$ret" in
        i32)   sig_ret=" -> i32";   ret_expr="    call_buf(\"$name\", &mut args) as i32\n" ;;
        usize) sig_ret=" -> usize"; ret_expr="    call_buf(\"$name\", &mut args) as usize\n" ;;
        void)  sig_ret="";          ret_expr="    call_buf(\"$name\", &mut args);\n" ;;
        *)     echo "gen_stubs.sh: unknown return type '$ret' for '$name'" >&2; exit 2 ;;
    esac

    printf '\n#[unsafe(no_mangle)]\npub extern "C" fn %s(%s)%s {\n' "$name" "$params" "$sig_ret"
    [ -n "$preamble" ] && printf '%b' "$preamble"
    printf '    let mut args = [%b\n    ];\n' "$argexpr"
    printf '%b}\n' "$ret_expr"
done < "$funcs"
