[package]
name = "wasmtime-grateos-dylink"
version.workspace = true
authors.workspace = true
description = "grateos dynamic loading implementation inside wasmtime"
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
rand = "0.8"
wasmtime = { workspace = true, features = ['threads'] }
wasmtime-environ = { workspace = true }
rawposix = { path = "../rawposix" }
threei = { path = "../threei" }
wasmtime-grateos-multi-process = { path = "../grateos-multi-process" }
wasmtime-grateos-utils = { path = "../grateos-utils" }
sysdefs = { path = "../sysdefs" }
cage = { path = "../cage" }
typemap = { path = "../typemap" }

[features]
grateos-logging = ["sysdefs/grateos-logging"]
