// AUTO-GENERATED by tools/marshal-gen/gen_grate.py — do not edit by hand.
// Auto-interposition grate for libc: registers a generic marshalling
// handler for every inference-marshalable function, each bound to (spec, &real_fn).
//
// Compile:
//   lind-clang -s --compile-grate --fpcast-emu libc_auto_grate.c -- -I<lind_marshal.h dir> <libc.a>
// Run (from lindfs/):
//   lind-wasm --preload env=/lib/libc.so grates/libc_auto_grate.cwasm <app...>
#include <lind_syscall.h>
#include <stdio.h>
#include <sys/wait.h>
#include <unistd.h>
#include <assert.h>
#include <stdint.h>

#include "lind_marshal.h"

// --- real library functions (defined via static-linked libc.a) ---
// K&R-style extern decls: only need them callable/address-takeable; fpcast-emu
// adapts the ABI at the uniform-pointer call site.
#include <stdlib.h>
// (no extern decls: real functions come from the included headers)

// --- per-function marshalling specs (translated from libc.marshal.json) ---
static struct lind_marshal_spec spec_strchr = {
    .nargs = 2,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_PTR_INTO_ARG, .alias_arg_index = 0 },
};
static struct lind_marshal_spec spec_strnlen = {
    .nargs = 2,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 1 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_strtol = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_OUT, .size_kind = LIND_SIZE_CONST, .const_size = 4, .out_ptr_into_arg1 = 1 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_strcmp = {
    .nargs = 2,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_strlen = {
    .nargs = 1,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_CSTR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_memchr = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 2 },
        { .kind = LIND_ARG_SCALAR },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_PTR_INTO_ARG, .alias_arg_index = 0 },
};
static struct lind_marshal_spec spec_memcmp = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 2 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 2 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};
static struct lind_marshal_spec spec_strncmp = {
    .nargs = 3,
    .args = {
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 2 },
        { .kind = LIND_ARG_PTR, .ptr_direction = LIND_PTR_IN, .size_kind = LIND_SIZE_FROM_ARG, .size_arg_index = 2 },
        { .kind = LIND_ARG_SCALAR },
    },
    .ret = { .kind = LIND_RET_SCALAR },
};

// --- per-symbol dispatch contexts ---
struct libctx { const struct lind_marshal_spec *spec; void *real_fn; };

struct reg_entry { const char *name; struct libctx ctx; };
static struct reg_entry g_table[] = {
    { "strchr", { &spec_strchr, (void *)(uintptr_t)&strchr } },
    { "strnlen", { &spec_strnlen, (void *)(uintptr_t)&strnlen } },
    { "strtol", { &spec_strtol, (void *)(uintptr_t)&strtol } },
    { "strcmp", { &spec_strcmp, (void *)(uintptr_t)&strcmp } },
    { "strlen", { &spec_strlen, (void *)(uintptr_t)&strlen } },
    { "memchr", { &spec_memchr, (void *)(uintptr_t)&memchr } },
    { "memcmp", { &spec_memcmp, (void *)(uintptr_t)&memcmp } },
    { "strncmp", { &spec_strncmp, (void *)(uintptr_t)&strncmp } },
};
#define G_TABLE_N ((int)(sizeof(g_table)/sizeof(g_table[0])))

// --- generic dispatcher: registered value is a struct libctx* ---
int pass_fptr_to_wt(uint64_t ctx_ptr_u64, uint64_t cageid,
                    uint64_t a1, uint64_t a1c, uint64_t a2, uint64_t a2c,
                    uint64_t a3, uint64_t a3c, uint64_t a4, uint64_t a4c,
                    uint64_t a5, uint64_t a5c, uint64_t a6, uint64_t a6c) {
    if (ctx_ptr_u64 == 0) { fprintf(stderr, "[libc-grate] null ctx\n"); assert(0); }
    struct libctx *ctx = (struct libctx *)(uintptr_t)ctx_ptr_u64;
    uint64_t raw[6]   = { a1, a2, a3, a4, a5, a6 };
    uint64_t cages[6] = { a1c, a2c, a3c, a4c, a5c, a6c };
    uint64_t src = 0;
    for (int i = 0; i < 6 && src == 0; i++) src = cages[i];
    return (int)lind_marshal_dispatch(ctx->real_fn, ctx->spec, src, cageid,
                                      raw, ctx->spec->nargs);
}

int main(int argc, char *argv[]) {
    if (argc < 2) { fprintf(stderr, "Usage: %s <app> [args...]\n", argv[0]); assert(0); }
    int grateid = getpid();
    pid_t pid = fork();
    if (pid < 0) { perror("fork"); assert(0); }
    if (pid == 0) {
        int cageid = getpid();
        int ok = 0, fail = 0;
        for (int i = 0; i < G_TABLE_N; i++) {
            int r = register_lib_handler(cageid, "env", g_table[i].name,
                        grateid, (uint64_t)(uintptr_t)&g_table[i].ctx);
            if (r == 0) ok++;
            else { fail++; fprintf(stderr, "[libc-grate] register %s failed: %d\n",
                                    g_table[i].name, r); }
        }
        fprintf(stderr, "[libc-grate] registered %d/%d handlers\n", ok, ok + fail);
        if (execv(argv[1], &argv[1]) == -1) { perror("execv"); assert(0); }
    }
    int status;
    while (wait(&status) > 0) {}
    int ce = WIFEXITED(status) ? WEXITSTATUS(status) : -1;
    fprintf(stderr, "[libc-grate] app exited %d\n", ce);
    return ce == 0 ? 0 : 1;
}
