# This is a GitHub Actions workflow that automatically posts a comment
# on every new Pull Request (PR), using a markdown template stored in the repo.

name: Comment on PR with Template

# Trigger this workflow when a new pull request is opened
on:
  pull_request:
    types: [opened]

jobs:
  # Define a job named 'comment' that runs on the latest Ubuntu runner
  comment:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the contents of the repository
      # This ensures the markdown template file is available for later steps
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Read the markdown template and post it as a comment on the PR
      # Uses GitHub's REST API via the github-script action
      - name: Read PR checklist and post comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = '.github/templates/PR_Checklist.md';
            const body = fs.readFileSync(path, 'utf8');

            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
