name: Zizmor GitHub Actions security check

on:
  pull_request:

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Run zizmor
        id: zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa
        with:
          inputs: |
            .github/workflows
          advanced-security: false

      - name: Fail if issues found
        if: failure()
        run: exit 1