name: Zizmor GitHub Actions security check

on:
  pull_request:

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Run zizmor
        id: zizmor
        uses: zizmorcore/zizmor-action@70fb788f84895a7701f5643d103d587e460b5c99
        with:
          inputs: |
            .github/workflows
          advanced-security: false

      - name: Fail if issues found
        if: failure()
        run: exit 1